CLASS zcl_gogen_luw_seam DEFINITION PUBLIC FINAL CREATE PUBLIC.
 PUBLIC SECTION.
 CLASS-METHODS commit.
 CLASS-METHODS commit_wait.
 CLASS-METHODS rollback.
 CLASS-METHODS update.
 CLASS-METHODS ordinary.
 CLASS-METHODS raising.
 CLASS-METHODS wait.
ENDCLASS.
CLASS zcl_gogen_luw_seam IMPLEMENTATION.
 METHOD commit.
 COMMIT WORK.
 ENDMETHOD.
 METHOD commit_wait.
 COMMIT WORK AND WAIT.
 ENDMETHOD.
 METHOD rollback.
 ROLLBACK WORK.
 ENDMETHOD.
 METHOD update.
 CALL FUNCTION 'ZGOGEN_LUW_UPDATE'.
 ENDMETHOD.
 METHOD ordinary.
 CALL FUNCTION 'ZGOGEN_LUW_ORDINARY'.
 ENDMETHOD.
 METHOD raising.
 CALL FUNCTION 'ZGOGEN_LUW_UPDATE' EXPORTING iv_boom = 1 EXCEPTIONS boom = 1.
 ENDMETHOD.
 METHOD wait.
 WAIT UP TO 0 SECONDS.
 ENDMETHOD.
ENDCLASS.
