* Generated by tools/dsl-l2.mjs from {{source}}; do not edit.
* Rule {{rule}}: {{title}}
CLASS {{class}} DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS check
      IMPORTING iv_date TYPE d
      RETURNING VALUE(rt_alerts) TYPE string_table.
ENDCLASS.

CLASS {{class}} IMPLEMENTATION.
  METHOD check.
    " one query: the tables joined, never a SELECT per row of the first
    TYPES: BEGIN OF ty_join,
{{#join.fields}}
             {{name}} TYPE {{table}}-{{column}},
{{/join.fields}}
           END OF ty_join.
    DATA {{join.itab}} TYPE STANDARD TABLE OF ty_join WITH DEFAULT KEY.
    DATA {{join.wa}} TYPE ty_join.
    DATA lv_alert TYPE string.
    SELECT
{{#join.fields}}
        {{source}} AS {{name}}
{{/join.fields}}
      FROM {{for.table}} AS {{for.alias}}
        INNER JOIN {{forbid.table}} AS {{forbid.alias}}
{{#join.on}}
          {{#@first}}ON{{/@first}}{{^@first}} AND{{/@first}} {{lhs}} {{op}} {{sref}}
{{/join.on}}
      INTO CORRESPONDING FIELDS OF TABLE {{join.itab}}
{{#join.where}}
      {{#@first}}WHERE{{/@first}}{{^@first}}  AND{{/@first}} {{lhs}} {{op}} {{#is_literal}}{{value | literal}}{{/is_literal}}{{^is_literal}}{{sref}}{{/is_literal}}
{{/join.where}}
      ORDER BY
{{#join.order}}
        {{source}}{{#@last}}.{{/@last}}
{{/join.order}}
    LOOP AT {{join.itab}} INTO {{join.wa}}.
{{#alert.parts}}
      {{#@first}}lv_alert = {{/@first}}{{^@first}}  && {{/@first}}{{#is_text}}{{value | literal}}{{/is_text}}{{^is_text}}{{jref}}{{/is_text}}{{#@last}}.{{/@last}}
{{/alert.parts}}
      APPEND lv_alert TO rt_alerts.
    ENDLOOP.
  ENDMETHOD.
ENDCLASS.
