* Generated by tools/dsl-l2.mjs from {{source}}; do not edit.
* Rule {{rule}}: {{title}}
CLASS {{class}} DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS check
      IMPORTING iv_date TYPE d
      RETURNING VALUE(rt_alerts) TYPE string_table.
ENDCLASS.

CLASS {{class}} IMPLEMENTATION.
  METHOD check.
    " {{comment}}
{{#queries}}
    TYPES: BEGIN OF {{type}},
{{#fields}}
             {{name}} TYPE {{table}}-{{column}},
{{/fields}}
           END OF {{type}}.
    DATA {{itab}} TYPE STANDARD TABLE OF {{type}} WITH DEFAULT KEY.
    DATA {{wa}} TYPE {{type}}.
{{#limit}}
    DATA ls_prev TYPE {{type}}.
{{/limit}}
{{/queries}}
    DATA lv_alert TYPE string.
{{#threshold}}
    DATA lv_count TYPE i.
    DATA lv_count_text TYPE c LENGTH 12.
{{/threshold}}
{{#queries}}
    SELECT
{{#fields}}
        {{source}} AS {{name}}
{{/fields}}
{{#from}}
      FROM {{table}} AS {{alias}}
{{/from}}
{{#joins}}
        INNER JOIN {{table}} AS {{alias}}
{{#on}}
          {{#@first}}ON{{/@first}}{{^@first}} AND{{/@first}} {{lhs}} {{op}} {{sref}}
{{/on}}
{{/joins}}
      INTO CORRESPONDING FIELDS OF TABLE {{itab}}
{{#where}}
      {{pre}}{{#is_cmp}}{{lhs}} {{op}} {{#is_literal}}{{value | literal}}{{/is_literal}}{{^is_literal}}{{sref}}{{/is_literal}}{{/is_cmp}}{{^is_cmp}}{{text}}{{/is_cmp}}{{post}}
{{/where}}
      ORDER BY
{{#order}}
        {{source}}{{#@last}}.{{/@last}}
{{/order}}
    LOOP AT {{itab}} INTO {{wa}}.
{{#limit}}
      IF lv_count > 0 AND ( {{key_change}} ).
        IF lv_count {{op}} {{value}}.
          lv_count_text = lv_count.
          CONDENSE lv_count_text NO-GAPS.
{{/limit}}
{{#alert_parts}}
{{#limit}}    {{/limit}}      {{#@first}}lv_alert = {{/@first}}{{^@first}}  && {{/@first}}{{#is_text}}{{value | literal}}{{/is_text}}{{^is_text}}{{jref}}{{/is_text}}{{#@last}}.{{/@last}}
{{/alert_parts}}
{{#limit}}
          APPEND lv_alert TO rt_alerts.
        ENDIF.
        CLEAR lv_count.
      ENDIF.
      ADD 1 TO lv_count.
      ls_prev = {{wa}}.
{{/limit}}
{{^limit}}
      APPEND lv_alert TO rt_alerts.
{{/limit}}
    ENDLOOP.
{{#limit}}
    IF lv_count {{op}} {{value}}.
      lv_count_text = lv_count.
      CONDENSE lv_count_text NO-GAPS.
{{#alert_parts}}
      {{#@first}}lv_alert = {{/@first}}{{^@first}}  && {{/@first}}{{#is_text}}{{value | literal}}{{/is_text}}{{^is_text}}{{jref}}{{/is_text}}{{#@last}}.{{/@last}}
{{/alert_parts}}
      APPEND lv_alert TO rt_alerts.
    ENDIF.
{{/limit}}
{{/queries}}
  ENDMETHOD.
ENDCLASS.
