* Generated by tools/dsl-l3.mjs from {{source}}; do not edit.
* Set {{set}}: {{title}}
CLASS {{class}} DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    TYPES: BEGIN OF ty_rule,
             rule TYPE zosd_l3_alert-rule_name,
             model_hash TYPE zosd_l3_alert-model_hash,
             jobname TYPE tbtcjob-jobname,
             jobcount TYPE tbtcjob-jobcount,
             status TYPE c LENGTH 12,
             alerts TYPE i,
             failed TYPE i,
{{#planned}}
             piles TYPE i,
             piles_done TYPE i,
{{/planned}}
{{#staged}}
             stage_no TYPE i,
             filter TYPE abap_bool,
             keys TYPE i,
{{/staged}}
           END OF ty_rule.
    TYPES tt_rule TYPE STANDARD TABLE OF ty_rule WITH DEFAULT KEY.
{{#planned}}
    TYPES tt_pile TYPE STANDARD TABLE OF zosd_l3_pile WITH DEFAULT KEY.
{{/planned}}
{{#staged}}
    " a stage of the run: WAITING, OPEN, SUBMITTED, DONE, PARTIAL or NOT-RUN
    TYPES: BEGIN OF ty_stage,
             stage_no TYPE i,
             stage TYPE zosd_l3_stage-stage_name,
             status TYPE c LENGTH 12,
             piles TYPE i,
             piles_done TYPE i,
           END OF ty_stage.
    TYPES tt_stage TYPE STANDARD TABLE OF ty_stage WITH DEFAULT KEY.
{{/staged}}
{{#resilience}}
    " a row of the doctor's report and of ZOSD_L3_DOCTOR: what it did to which
    " run, stage, rule and pile, and why
    TYPES: BEGIN OF ty_doctor,
             run_id TYPE zosd_l3_doctor-run_id,
             check_date TYPE d,
             stage_no TYPE i,
             rule_name TYPE zosd_l3_doctor-rule_name,
             pile_no TYPE i,
             doc_action TYPE zosd_l3_doctor-doc_action,
             reason TYPE zosd_l3_doctor-reason,
           END OF ty_doctor.
    TYPES tt_doctor TYPE STANDARD TABLE OF ty_doctor WITH DEFAULT KEY.
{{/resilience}}
{{#stages}}
{{#piles}}
    TYPES tt_range_{{no}} TYPE RANGE OF {{source.table}}-{{source.key}}.
{{/piles}}
{{/stages}}
{{#with_params}}
    " the set parameters; run( ) gives a component that is initial its default
    TYPES: BEGIN OF ty_params,
{{/with_params}}
{{#params}}
             {{name}} TYPE {{type_name}},
{{/params}}
{{#with_params}}
           END OF ty_params.
{{/with_params}}
    TYPES: BEGIN OF ty_result,
             set_name TYPE zosd_l3_alert-set_name,
             run_id TYPE zosd_l3_alert-run_id,
             check_date TYPE d,
             mode TYPE c LENGTH 1,
             alerts TYPE i,
             rules TYPE tt_rule,
{{#planned}}
             bind TYPE string,
             status TYPE c LENGTH 12,
{{/planned}}
{{#staged}}
             stages TYPE tt_stage,
{{#with_params}}
             params TYPE ty_params,
{{/with_params}}
{{/staged}}
{{#resilience}}
             " a dry run: the rows a real run would have written to the log
             dry TYPE {{sink_iface}}=>tt_rows,
{{/resilience}}
           END OF ty_result.
    CONSTANTS c_set TYPE zosd_l3_alert-set_name VALUE {{set | literal}}.
    CONSTANTS c_sequential TYPE c LENGTH 1 VALUE 'S'.
    CONSTANTS c_parallel TYPE c LENGTH 1 VALUE 'P'.
{{#piles}}
    " keys of {{source.table}}-{{source.key}} per pile, read through port {{source.name}}
    CONSTANTS c_pile_size TYPE i VALUE {{size}}.
{{/piles}}
{{#rules}}
    CONSTANTS c_rule_{{index}} TYPE zosd_l3_alert-rule_name VALUE {{name | literal}}.
    CONSTANTS c_hash_{{index}} TYPE zosd_l3_alert-model_hash VALUE {{hash | literal}}.
{{/rules}}
{{#disabled}}
    " not run: {{name}} ({{file}}), enabled: false in the set
{{/disabled}}
{{#stages}}
    " stage {{no}}{{#filter}}, a filter: its rules fill worklist {{worklist.name}}{{/filter}}{{#piles}}, piles of {{size}} keys of {{source.table}}-{{source.key}}{{#over_worklist}} in worklist {{name}}{{/over_worklist}}{{/piles}}
    CONSTANTS c_stage_{{no}} TYPE zosd_l3_stage-stage_name VALUE {{name | literal}}.
{{/stages}}
{{#staged}}
    CONSTANTS c_stages TYPE i VALUE {{count}}.
{{/staged}}
{{#schedule}}
    " the driver job of the schedule: every {{every}}, system time
    CONSTANTS c_driver TYPE tbtcjob-jobname VALUE {{driver | literal}}.
{{/schedule}}
{{#resilience}}
{{#retry}}
    " a FAILED or vanished pile is submitted again up to c_retry_max times,
    " c_backoff seconds after it failed, doubled per attempt
    CONSTANTS c_retry_max TYPE i VALUE {{max}}.
    CONSTANTS c_backoff TYPE i VALUE {{backoff}}.
{{/retry}}
{{#stale}}
    " seconds after which a HELD lock, a pile without its job or an OPEN gate
    " without piles is the doctor's
    CONSTANTS c_stale TYPE i VALUE {{seconds}}.
{{#job}}
    " the doctor's own periodic job, every {{word}}
    CONSTANTS c_doctor TYPE tbtcjob-jobname VALUE {{name | literal}}.
{{/job}}
{{/stale}}
{{#keep}}
    " the plan, worklist, gate and doctor rows of a final run are kept this many days
    CONSTANTS c_keep_days TYPE i VALUE {{days}}.
{{/keep}}
{{/resilience}}
{{#fused}}
    " the fuse: a rule writes at most c_max_alerts alerts in a run
    CONSTANTS c_max_alerts TYPE i VALUE {{count}}.
{{/fused}}
    " iv_bind: the variant of each port for this run, "port=variant,port=variant";
    " a port it does not name keeps the manifest's binding. A source that is not
    " live replaces table content in the caller's LUW: a test and dev seam, never
    " production, and refused unless iv_allow_replay says so.
    CLASS-METHODS run
      IMPORTING iv_date TYPE d
                iv_mode TYPE c DEFAULT 'S'
                iv_bind TYPE string OPTIONAL
{{#with_params}}
                is_params TYPE ty_params OPTIONAL
{{/with_params}}
{{#piles}}
                iv_pile_size TYPE i DEFAULT c_pile_size
{{/piles}}
                iv_allow_replay TYPE abap_bool DEFAULT abap_false
{{#resilience}}
{{#dry_run}}
                iv_dry_run TYPE abap_bool DEFAULT {{value}}
{{/dry_run}}
{{/resilience}}
      RETURNING VALUE(rs_result) TYPE ty_result.
{{#piles}}
    " the plan of a run: one row per rule and pile, PLANNED
    CLASS-METHODS plan
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d
                iv_bind TYPE string OPTIONAL
                iv_size TYPE i DEFAULT c_pile_size
      RETURNING VALUE(rt_piles) TYPE tt_pile.
{{/piles}}
{{#staged}}
    " the plan of one stage, made when the stage opens: a row per rule and pile
    CLASS-METHODS plan
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d
                iv_stage TYPE i
                iv_bind TYPE string OPTIONAL
      RETURNING VALUE(rt_piles) TYPE tt_pile.
    " the gate, called by a pile's job once its pile is DONE and committed:
    " when every pile of iv_stage is DONE the next stage opens, once
    CLASS-METHODS advance
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d
                iv_stage TYPE i
                iv_bind TYPE string OPTIONAL
{{#with_params}}
                is_params TYPE ty_params OPTIONAL
{{/with_params}}
      RETURNING VALUE(rv_opened) TYPE abap_bool.
{{/staged}}
    CLASS-METHODS run_rule
      IMPORTING iv_rule TYPE csequence
                iv_date TYPE d
                iv_run TYPE csequence
{{#planned}}
                iv_pile TYPE i
{{/planned}}
                iv_bind TYPE string OPTIONAL
{{#with_params}}
                is_params TYPE ty_params OPTIONAL
{{/with_params}}
      RETURNING VALUE(rs_rule) TYPE ty_rule.
    CLASS-METHODS collect
      IMPORTING is_result TYPE ty_result
      RETURNING VALUE(rs_result) TYPE ty_result.
    CLASS-METHODS rules
      RETURNING VALUE(rt_rules) TYPE tt_rule.
{{#schedule}}
    " the set as a periodic background job: ZL3_<SET> with p_mode = 'D' (one
    " run in jobs for the current date) every {{every}}, first at the time
    " schedule: names, in system time (sy-datum, sy-uzeit), never the user's
    " a second call while an instance waits answers that instance's count and
    " opens no second chain
    CLASS-METHODS schedule
      RETURNING VALUE(rv_jobcount) TYPE tbtcjob-jobcount.
    " the count of the driver's instance waiting for its start (status S) for
    " this user, or initial when the set is not scheduled
    CLASS-METHODS scheduled
      RETURNING VALUE(rv_jobcount) TYPE tbtcjob-jobcount.
    " deletes the waiting instance of the driver, which ends the chain
    CLASS-METHODS unschedule
      RETURNING VALUE(rv_deleted) TYPE i.
{{/schedule}}
{{#resilience}}
    " continues an open run, one that still holds its lock: piles PLANNED
    " without a job and FAILED piles within the retry budget are submitted
    " again at once, a gate whose stage is complete advances
    CLASS-METHODS resume
      IMPORTING iv_run TYPE csequence
                iv_bind TYPE string OPTIONAL
{{#with_params}}
                is_params TYPE ty_params OPTIONAL
{{/with_params}}
                iv_now TYPE timestamp OPTIONAL
      RETURNING VALUE(rt_report) TYPE tt_doctor.
    " one pass over the set's open runs: dead jobs, retries, lost plans,
    " stale locks; then purge( ). Safe beside jobs and another doctor
    CLASS-METHODS doctor
      IMPORTING iv_now TYPE timestamp OPTIONAL
      RETURNING VALUE(rt_report) TYPE tt_doctor.
    " the plan, worklist, gate and doctor rows of final runs older than
    " c_keep_days; never an alert, never anything of an open run
    CLASS-METHODS purge
      IMPORTING iv_now TYPE timestamp OPTIONAL
      RETURNING VALUE(rt_report) TYPE tt_doctor.
{{/resilience}}
{{#killable}}
    " true while {{table}} holds a row of the set: the kill switch
    CLASS-METHODS killed
      RETURNING VALUE(rv_killed) TYPE abap_bool.
{{/killable}}
  PRIVATE SECTION.
    CLASS-METHODS write
      IMPORTING iv_date TYPE d
                iv_run TYPE csequence
{{#planned}}
                iv_pile TYPE i
{{/planned}}
                iv_class TYPE csequence
                iv_file TYPE csequence
                iv_line TYPE i
                it_alerts TYPE string_table
                iv_bind TYPE string OPTIONAL
      CHANGING cs_rule TYPE ty_rule.
{{#planned}}
    " one run of the set per check date at a time: ZOSD_L3_RUN
    CLASS-METHODS lock
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d
      RETURNING VALUE(rv_locked) TYPE abap_bool.
    CLASS-METHODS release
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d.
    CLASS-METHODS finalise
      IMPORTING iv_rule TYPE csequence
                iv_hash TYPE csequence
                iv_date TYPE d
                iv_run TYPE csequence
                iv_bind TYPE string.
{{/planned}}
{{#staged}}
    CLASS-METHODS stages
      RETURNING VALUE(rt_stages) TYPE tt_stage.
    " a filter rule's keys into the run's worklist (ZOSD_L3_WORK)
    CLASS-METHODS fill
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d
                iv_worklist TYPE csequence
                it_keys TYPE string_table
      CHANGING cs_rule TYPE ty_rule.
{{/staged}}
{{#stages}}
{{#piles}}
    " the range of a pile of stage {{no}}, from its plan row{{#over_worklist}} and worklist {{name}}{{/over_worklist}}
    CLASS-METHODS range_{{no}}
      IMPORTING is_pile TYPE zosd_l3_pile
      RETURNING VALUE(rt_range) TYPE tt_range_{{no}}.
{{/piles}}
{{/stages}}
{{#sources}}
    " puts the rows of {{table}} back after a replay: the rows kept before it
    CLASS-METHODS restore_{{index}}
      IMPORTING it_keep TYPE {{iface}}=>tt_rows.
{{/sources}}
    CLASS-METHODS submit
      IMPORTING iv_date TYPE d
                iv_run TYPE csequence
                iv_bind TYPE string OPTIONAL
{{#with_params}}
                is_params TYPE ty_params OPTIONAL
{{/with_params}}
{{^planned}}
      CHANGING cs_rule TYPE ty_rule.
{{/planned}}
{{#planned}}
                iv_jobname TYPE csequence
      CHANGING cs_pile TYPE zosd_l3_pile.
{{/planned}}
{{#resilience}}
    " a dry run: run( ) in this step with the alerts bound to capture
    CLASS-METHODS dry
      IMPORTING iv_date TYPE d
                iv_bind TYPE string OPTIONAL
{{#with_params}}
                is_params TYPE ty_params OPTIONAL
{{/with_params}}
                iv_allow_replay TYPE abap_bool DEFAULT abap_false
      RETURNING VALUE(rs_result) TYPE ty_result.
    " the doctor's work on one open run (iv_force: resume( ), no waiting)
    CLASS-METHODS heal
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d
                iv_now TYPE timestamp
                iv_force TYPE abap_bool
                iv_bind TYPE string OPTIONAL
{{#with_params}}
                is_params TYPE ty_params OPTIONAL
{{/with_params}}
      CHANGING ct_report TYPE tt_doctor.
    " a FAILED pile is due again once its backoff has passed
    CLASS-METHODS due
      IMPORTING is_pile TYPE zosd_l3_pile
                iv_now TYPE timestamp
                iv_force TYPE abap_bool
      RETURNING VALUE(rv_due) TYPE abap_bool.
    CLASS-METHODS ago
      IMPORTING iv_now TYPE timestamp
                iv_secs TYPE i
      RETURNING VALUE(rv_stamp) TYPE timestamp.
    " a row of the report, and of ZOSD_L3_DOCTOR unless iv_audit is off
    CLASS-METHODS act
      IMPORTING iv_run TYPE csequence
                iv_date TYPE d OPTIONAL
                iv_stage TYPE i OPTIONAL
                iv_rule TYPE csequence OPTIONAL
                iv_pile TYPE i OPTIONAL
                iv_action TYPE csequence
                iv_reason TYPE csequence
                iv_now TYPE timestamp OPTIONAL
                iv_audit TYPE abap_bool DEFAULT abap_true
      CHANGING ct_report TYPE tt_doctor.
{{#scheduled}}
    CLASS-METHODS schedule_doctor.
    CLASS-METHODS unschedule_doctor
      RETURNING VALUE(rv_deleted) TYPE i.
{{/scheduled}}
{{/resilience}}
ENDCLASS.

CLASS {{class}} IMPLEMENTATION.
  METHOD run.
{{^planned}}
    " mode S runs every rule in this step; mode P submits one job per rule,
    " and collect( ) reads their states once they have run
{{/planned}}
{{#staged}}
    " stage by stage: a stage opens through its gate row in ZOSD_L3_STAGE
    " (WAITING to OPEN), is planned then (a later stage reads the worklist an
    " earlier one filled) and runs. Mode S runs every stage in this step and
    " stops at a stage that is not DONE; mode P submits the piles of the first
    " stage that has any, and the job that ends a stage opens the next one
{{/staged}}
{{#piles}}
    " the plan first: a row per rule and pile. Mode S then runs every pile in
    " this step; mode P submits one job per pile, and collect( ) reads the plan
    " and the jobs' states once they have run
{{/piles}}
    DATA lt_rules TYPE tt_rule.
    DATA ls_rule TYPE ty_rule.
{{#planned}}
    DATA lt_piles TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA ls_part TYPE ty_rule.
{{/planned}}
{{#piles}}
    DATA lv_lost TYPE i.
{{/piles}}
{{#staged}}
    DATA lt_stages TYPE tt_stage.
    DATA ls_stage TYPE ty_stage.
    DATA ls_gate TYPE zosd_l3_stage.
    DATA lv_stop TYPE abap_bool.
    DATA lv_open TYPE abap_bool.
{{/staged}}
{{#fused}}
    DATA lv_fused TYPE abap_bool.
{{/fused}}
    DATA lv_stamp TYPE timestampl.
    DATA lv_parallel TYPE abap_bool.
    DATA lx_error TYPE REF TO cx_root.
{{#sources}}
    DATA li_src_{{index}} TYPE REF TO {{iface}}.
    DATA lv_swap_{{index}} TYPE abap_bool.
    DATA lt_keep_{{index}} TYPE {{iface}}=>tt_rows.
    DATA lt_scope_{{index}} TYPE {{iface}}=>tt_rows.
    FIELD-SYMBOLS <ls_row_{{index}}> TYPE {{table}}.
{{/sources}}
{{#resilience}}
{{#dry_run}}
    " a dry run: every check in this step, nothing to the log (dry( ))
    IF iv_dry_run = abap_true.
      rs_result = dry( iv_date = iv_date
                       iv_bind = iv_bind
{{#with_params}}
                       is_params = is_params
{{/with_params}}
                       iv_allow_replay = iv_allow_replay ).
      RETURN.
    ENDIF.
{{/dry_run}}
{{/resilience}}
    IF iv_mode = c_parallel.
      lv_parallel = abap_true.
    ENDIF.
    {{ports_class}}=>check( iv_bind = iv_bind
                          iv_parallel = lv_parallel
                          iv_allow_replay = iv_allow_replay ).
    rs_result-set_name = c_set.
    rs_result-mode = iv_mode.
{{#planned}}
    rs_result-bind = iv_bind.
{{/planned}}
{{#staged}}
{{#with_params}}
    rs_result-params = is_params.
{{/with_params}}
{{/staged}}
{{#date}}
    rs_result-check_date = iv_date.
{{#today}}
    IF rs_result-check_date IS INITIAL.
      rs_result-check_date = sy-datum.
    ENDIF.
{{/today}}
{{/date}}
    TRY.
        rs_result-run_id = cl_system_uuid=>create_uuid_c32_static( ).
      CATCH cx_uuid_error.
        GET TIME STAMP FIELD lv_stamp.
        rs_result-run_id = lv_stamp.
    ENDTRY.
{{#killable}}
    " the kill switch: while {{table}} holds a row of the set no run starts
    IF killed( ) = abap_true.
      rs_result-status = 'KILLED'.
      RETURN.
    ENDIF.
{{/killable}}
{{#planned}}
    " one run of the set per check date at a time: a run that finds the lock
    " held by another answers BUSY and plans nothing
    IF lock( iv_run = rs_result-run_id iv_date = rs_result-check_date ) = abap_false.
      rs_result-status = 'BUSY'.
      RETURN.
    ENDIF.
{{/planned}}
    lt_rules = rules( ).
    " a source that is not live replaces table content for this run, and the
    " table is put back whatever happens: after the loop, or when an exception
    " leaves this method (CATCH and RAISE, which does what CLEANUP would; the
    " transpiler drops CLEANUP, ANORMALIES.md). Nothing in here commits.
    TRY.
{{#sources}}
        " {{table}}: the table's own rows are kept, the source's rows stand
        " in their place, and the rules read them as they read the table
        IF {{ports_class}}=>swaps( iv_port = {{name | literal}} iv_bind = iv_bind ) = abap_true.
          li_src_{{index}} = {{ports_class}}=>get_{{name}}( {{ports_class}}=>variant( iv_port = {{name | literal}} iv_bind = iv_bind ) ).
          SELECT * FROM {{table}} INTO TABLE lt_keep_{{index}}.
          lt_scope_{{index}} = li_src_{{index}}->read( ).
{{#has_client}}
          LOOP AT lt_scope_{{index}} ASSIGNING <ls_row_{{index}}>.
            <ls_row_{{index}}>-{{client}} = sy-mandt.
          ENDLOOP.
{{/has_client}}
          lv_swap_{{index}} = abap_true.
          DELETE FROM {{table}}.
          INSERT {{table}} FROM TABLE lt_scope_{{index}}.
        ENDIF.
{{/sources}}
{{^planned}}
        LOOP AT lt_rules INTO ls_rule.
          IF iv_mode = c_parallel.
            submit( EXPORTING iv_date = rs_result-check_date
                              iv_run = rs_result-run_id
                              iv_bind = iv_bind
{{#with_params}}
                              is_params = is_params
{{/with_params}}
                    CHANGING cs_rule = ls_rule ).
          ELSE.
            ls_rule = run_rule( iv_rule = ls_rule-rule
                                iv_date = rs_result-check_date
                                iv_run = rs_result-run_id
                                iv_bind = iv_bind{{#with_params}} is_params = is_params{{/with_params}} ).
            rs_result-alerts = rs_result-alerts + ls_rule-alerts.
          ENDIF.
          APPEND ls_rule TO rs_result-rules.
        ENDLOOP.
{{/planned}}
{{#piles}}
        lt_piles = plan( iv_run = rs_result-run_id
                         iv_date = rs_result-check_date
                         iv_bind = iv_bind
                         iv_size = iv_pile_size ).
        INSERT zosd_l3_pile FROM TABLE lt_piles.
        LOOP AT lt_rules INTO ls_rule.
          lv_lost = 0.
          LOOP AT lt_piles INTO ls_pile WHERE rule_name = ls_rule-rule.
            ls_rule-piles = ls_rule-piles + 1.
            IF iv_mode = c_parallel.
              submit( EXPORTING iv_date = rs_result-check_date
                                iv_run = rs_result-run_id
                                iv_bind = iv_bind
{{#with_params}}
                                is_params = is_params
{{/with_params}}
                                iv_jobname = ls_rule-jobname
                      CHANGING cs_pile = ls_pile ).
              IF ls_pile-status = 'FAILED'.
                lv_lost = lv_lost + 1.
              ENDIF.
            ELSE.
              ls_part = run_rule( iv_rule = ls_rule-rule
                                  iv_date = rs_result-check_date
                                  iv_run = rs_result-run_id
                                  iv_pile = ls_pile-pile_no
                                  iv_bind = iv_bind{{#with_params}} is_params = is_params{{/with_params}} ).
              ls_rule-alerts = ls_rule-alerts + ls_part-alerts.
              ls_rule-failed = ls_rule-failed + ls_part-failed.
              ls_rule-piles_done = ls_rule-piles_done + ls_part-piles_done.
            ENDIF.
          ENDLOOP.
          " a rule is DONE when every pile is; only then do the rows an older
          " run left (under other pile bounds) go. A pile that did not finish
          " leaves the rule PARTIAL and the older rows where they are
          IF iv_mode = c_parallel AND lv_lost > 0.
            ls_rule-status = 'PARTIAL'.
          ELSEIF iv_mode = c_parallel.
            ls_rule-status = 'SUBMITTED'.
          ELSEIF ls_rule-piles_done = ls_rule-piles.
            ls_rule-status = 'DONE'.
            finalise( iv_rule = ls_rule-rule
                      iv_hash = ls_rule-model_hash
                      iv_date = rs_result-check_date
                      iv_run = rs_result-run_id
                      iv_bind = iv_bind ).
          ELSE.
            ls_rule-status = 'PARTIAL'.
          ENDIF.
          rs_result-alerts = rs_result-alerts + ls_rule-alerts.
          APPEND ls_rule TO rs_result-rules.
        ENDLOOP.
        " mode P holds the lock until collect( ) finds every pile final
        IF iv_mode = c_parallel.
          rs_result-status = 'SUBMITTED'.
        ELSE.
          rs_result-status = 'DONE'.
          LOOP AT rs_result-rules INTO ls_rule WHERE status <> 'DONE'.
            rs_result-status = 'PARTIAL'.
          ENDLOOP.
          release( iv_run = rs_result-run_id iv_date = rs_result-check_date ).
        ENDIF.
{{/piles}}
{{#staged}}
        " the gate rows: every stage WAITING; a stage opens once, WAITING to OPEN
        lt_stages = stages( ).
        ls_gate-set_name = c_set.
        ls_gate-run_id = rs_result-run_id.
        ls_gate-check_date = rs_result-check_date.
        ls_gate-status = 'WAITING'.
        LOOP AT lt_stages INTO ls_stage.
          ls_gate-stage_no = ls_stage-stage_no.
          ls_gate-stage_name = ls_stage-stage.
          INSERT zosd_l3_stage FROM ls_gate.
        ENDLOOP.
        LOOP AT lt_stages INTO ls_stage.
          IF lv_stop = abap_true.
            " after a stage that did not end DONE, or after the stage whose
            " jobs were just submitted: not opened by this step
            ls_stage-status = 'WAITING'.
            LOOP AT lt_rules INTO ls_rule WHERE stage_no = ls_stage-stage_no.
              ls_rule-status = 'WAITING'.
              APPEND ls_rule TO rs_result-rules.
            ENDLOOP.
            APPEND ls_stage TO rs_result-stages.
            CONTINUE.
          ENDIF.
          GET TIME STAMP FIELD lv_stamp.
          UPDATE zosd_l3_stage SET status = 'OPEN' opened = lv_stamp
            WHERE run_id = rs_result-run_id
              AND stage_no = ls_stage-stage_no
              AND status = 'WAITING'.
          lt_piles = plan( iv_run = rs_result-run_id
                           iv_date = rs_result-check_date
                           iv_stage = ls_stage-stage_no
                           iv_bind = iv_bind ).
          INSERT zosd_l3_pile FROM TABLE lt_piles.
          ls_stage-piles = lines( lt_piles ).
          IF iv_mode = c_parallel AND lt_piles IS NOT INITIAL.
            " mode P: this stage's piles as jobs; the job that ends the stage opens the next
            LOOP AT lt_rules INTO ls_rule WHERE stage_no = ls_stage-stage_no.
              ls_rule-status = 'SUBMITTED'.
              LOOP AT lt_piles INTO ls_pile WHERE rule_name = ls_rule-rule.
                ls_rule-piles = ls_rule-piles + 1.
                submit( EXPORTING iv_date = rs_result-check_date
                                  iv_run = rs_result-run_id
                                  iv_bind = iv_bind
{{#with_params}}
                                  is_params = is_params
{{/with_params}}
                                  iv_jobname = ls_rule-jobname
                        CHANGING cs_pile = ls_pile ).
                IF ls_pile-status = 'FAILED'.
                  ls_rule-status = 'PARTIAL'.
                ENDIF.
              ENDLOOP.
              APPEND ls_rule TO rs_result-rules.
            ENDLOOP.
            ls_stage-status = 'SUBMITTED'.
            lv_stop = abap_true.
            lv_open = abap_true.
          ELSE.
            " mode S, or a stage without a pile: every pile in this step. A
            " rule is DONE when every pile is, and only then finalised
            LOOP AT lt_rules INTO ls_rule WHERE stage_no = ls_stage-stage_no.
{{#fused}}
              CLEAR lv_fused.
{{/fused}}
              LOOP AT lt_piles INTO ls_pile WHERE rule_name = ls_rule-rule.
                ls_rule-piles = ls_rule-piles + 1.
                ls_part = run_rule( iv_rule = ls_rule-rule
                                    iv_date = rs_result-check_date
                                    iv_run = rs_result-run_id
                                    iv_pile = ls_pile-pile_no
                                    iv_bind = iv_bind{{#with_params}} is_params = is_params{{/with_params}} ).
                ls_rule-alerts = ls_rule-alerts + ls_part-alerts.
                ls_rule-keys = ls_rule-keys + ls_part-keys.
                ls_rule-failed = ls_rule-failed + ls_part-failed.
                ls_rule-piles_done = ls_rule-piles_done + ls_part-piles_done.
{{#fused}}
                IF ls_part-status = 'FUSED'.
                  lv_fused = abap_true.
                ENDIF.
{{/fused}}
              ENDLOOP.
              IF ls_rule-piles_done = ls_rule-piles.
                ls_rule-status = 'DONE'.
                finalise( iv_rule = ls_rule-rule
                          iv_hash = ls_rule-model_hash
                          iv_date = rs_result-check_date
                          iv_run = rs_result-run_id
                          iv_bind = iv_bind ).
              ELSE.
                ls_rule-status = 'PARTIAL'.
              ENDIF.
{{#fused}}
              " a pile past the fuse: the rule is FUSED and was not finalised
              IF lv_fused = abap_true.
                ls_rule-status = 'FUSED'.
              ENDIF.
{{/fused}}
              ls_stage-piles_done = ls_stage-piles_done + ls_rule-piles_done.
              rs_result-alerts = rs_result-alerts + ls_rule-alerts.
              APPEND ls_rule TO rs_result-rules.
            ENDLOOP.
            IF ls_stage-piles_done = ls_stage-piles.
              ls_stage-status = 'DONE'.
            ELSE.
              ls_stage-status = 'PARTIAL'.
              lv_stop = abap_true.
            ENDIF.
            GET TIME STAMP FIELD lv_stamp.
            UPDATE zosd_l3_stage SET status = ls_stage-status ended = lv_stamp
              WHERE run_id = rs_result-run_id
                AND stage_no = ls_stage-stage_no.
          ENDIF.
          APPEND ls_stage TO rs_result-stages.
        ENDLOOP.
        " mode P holds the lock while a stage's jobs are open; else the run is final
        IF lv_open = abap_true.
          rs_result-status = 'SUBMITTED'.
        ELSE.
          rs_result-status = 'DONE'.
          LOOP AT rs_result-stages INTO ls_stage WHERE status <> 'DONE'.
            rs_result-status = 'PARTIAL'.
          ENDLOOP.
          release( iv_run = rs_result-run_id iv_date = rs_result-check_date ).
        ENDIF.
{{/staged}}
      CATCH cx_root INTO lx_error.
{{#planned}}
        release( iv_run = rs_result-run_id iv_date = rs_result-check_date ).
{{/planned}}
{{#sources}}
        IF lv_swap_{{index}} = abap_true.
          restore_{{index}}( lt_keep_{{index}} ).
        ENDIF.
{{/sources}}
        RAISE EXCEPTION lx_error.
    ENDTRY.
{{#sources}}
    IF lv_swap_{{index}} = abap_true.
      restore_{{index}}( lt_keep_{{index}} ).
    ENDIF.
{{/sources}}
  ENDMETHOD.

{{#piles}}
  METHOD plan.
    " the keys through port {{source.name}}, with an empty range (every row the
    " bound variant gives), sorted and without repeats, cut into consecutive
    " chunks of iv_size: a chunk is one pile, its first and last key the
    " range I BT low high, or I EQ low when it holds one key. No key, no pile
    DATA li_source TYPE REF TO {{source.iface}}.
    DATA lt_keys TYPE {{source.iface}}=>tt_rows.
    DATA ls_key LIKE LINE OF lt_keys.
    DATA lt_cut TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lv_count TYPE i.
    DATA lv_size TYPE i.
    " a size below one is the manifest's
    lv_size = iv_size.
    IF lv_size < 1.
      lv_size = c_pile_size.
    ENDIF.
    li_source = {{ports_class}}=>get_{{source.name}}( {{ports_class}}=>variant( iv_port = {{source.name | literal}} iv_bind = iv_bind ) ).
    lt_keys = li_source->read( ).
    SORT lt_keys BY {{source.key}}.
    DELETE ADJACENT DUPLICATES FROM lt_keys COMPARING {{source.key}}.
    ls_pile-set_name = c_set.
    ls_pile-run_id = iv_run.
    ls_pile-check_date = iv_date.
    ls_pile-status = 'PLANNED'.
    LOOP AT lt_keys INTO ls_key.
      IF lv_count = 0.
        ls_pile-pile_no = ls_pile-pile_no + 1.
        ls_pile-range_low = ls_key-{{source.key}}.
      ENDIF.
      ls_pile-range_high = ls_key-{{source.key}}.
      lv_count = lv_count + 1.
      IF lv_count = lv_size.
        APPEND ls_pile TO lt_cut.
        lv_count = 0.
      ENDIF.
    ENDLOOP.
    IF lv_count > 0.
      APPEND ls_pile TO lt_cut.
    ENDIF.
{{#rules}}
{{#range}}
    " {{name}}: piled, its range: is the key
    LOOP AT lt_cut INTO ls_pile.
      ls_pile-rule_name = c_rule_{{index}}.
      ls_pile-model_hash = c_hash_{{index}}.
      APPEND ls_pile TO rt_piles.
    ENDLOOP.
{{/range}}
{{#unpiled}}
    " {{name}}: not piled (its range: is not the key), one pile over every row: 0
    CLEAR: ls_pile-pile_no, ls_pile-range_low, ls_pile-range_high.
    ls_pile-rule_name = c_rule_{{index}}.
    ls_pile-model_hash = c_hash_{{index}}.
    APPEND ls_pile TO rt_piles.
{{/unpiled}}
{{/rules}}
  ENDMETHOD.

{{/piles}}
{{#staged}}
  METHOD plan.
    " the plan of one stage, made when the stage opens. A piled stage reads
    " its keys through its source port (over a worklist: the port's worklist
    " variant, the keys an earlier stage of this run filled), sorted and
    " without repeats, cut into consecutive chunks of its size; a rule that
    " is not piled is one pile, number 0, over every row. No key, no pile
    DATA lt_cut TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lv_count TYPE i.
{{#stages}}
{{#piles}}
    DATA li_source_{{no}} TYPE REF TO {{source.iface}}.
    DATA lt_keys_{{no}} TYPE {{source.iface}}=>tt_rows.
    DATA ls_key_{{no}} LIKE LINE OF lt_keys_{{no}}.
{{/piles}}
{{/stages}}
    ls_pile-set_name = c_set.
    ls_pile-run_id = iv_run.
    ls_pile-check_date = iv_date.
    ls_pile-stage_no = iv_stage.
    ls_pile-status = 'PLANNED'.
    CASE iv_stage.
{{#stages}}
      WHEN {{no}}.
{{#piles}}
{{#over_worklist}}
        " the keys worklist {{name}} holds for this run
        {{class}}=>use( iv_run = iv_run iv_worklist = {{name | literal}} ).
        li_source_{{no}} = {{ports_class}}=>get_{{source.name}}( 'worklist' ).
{{/over_worklist}}
{{^over_worklist}}
        li_source_{{no}} = {{ports_class}}=>get_{{source.name}}( {{ports_class}}=>variant( iv_port = {{source.name | literal}} iv_bind = iv_bind ) ).
{{/over_worklist}}
        lt_keys_{{no}} = li_source_{{no}}->read( ).
        SORT lt_keys_{{no}} BY {{source.key}}.
        DELETE ADJACENT DUPLICATES FROM lt_keys_{{no}} COMPARING {{source.key}}.
        LOOP AT lt_keys_{{no}} INTO ls_key_{{no}}.
          IF lv_count = 0.
            ls_pile-pile_no = ls_pile-pile_no + 1.
            ls_pile-range_low = ls_key_{{no}}-{{source.key}}.
          ENDIF.
          ls_pile-range_high = ls_key_{{no}}-{{source.key}}.
          lv_count = lv_count + 1.
          IF lv_count = {{size}}.
            APPEND ls_pile TO lt_cut.
            lv_count = 0.
          ENDIF.
        ENDLOOP.
        IF lv_count > 0.
          APPEND ls_pile TO lt_cut.
        ENDIF.
{{/piles}}
{{#members}}
{{#range}}
        " {{name}}: piled, its range: is the key
        LOOP AT lt_cut INTO ls_pile.
          ls_pile-rule_name = c_rule_{{index}}.
          ls_pile-model_hash = c_hash_{{index}}.
          APPEND ls_pile TO rt_piles.
        ENDLOOP.
{{/range}}
{{#unpiled}}
        " {{name}}: not piled, one pile over every row: 0
        CLEAR: ls_pile-pile_no, ls_pile-range_low, ls_pile-range_high.
        ls_pile-rule_name = c_rule_{{index}}.
        ls_pile-model_hash = c_hash_{{index}}.
        APPEND ls_pile TO rt_piles.
{{/unpiled}}
{{/members}}
{{/stages}}
    ENDCASE.
  ENDMETHOD.

  METHOD stages.
    DATA ls_stage TYPE ty_stage.
{{#stages}}
    ls_stage-stage_no = {{no}}.
    ls_stage-stage = c_stage_{{no}}.
    APPEND ls_stage TO rt_stages.
{{/stages}}
  ENDMETHOD.

  METHOD advance.
    " every pile of stage iv_stage DONE: the stage is DONE and the next one
    " opens. The gate is one UPDATE from WAITING to OPEN, so of two jobs that
    " end the stage at once only the one that gets sy-dbcnt = 1 plans and
    " submits it. A stage without a pile is DONE at once and the one after it
    " opens; past the last stage the run is complete: every rule finalised
    " (all are DONE) and the lock released
    DATA lt_piles TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lt_rules TYPE tt_rule.
    DATA ls_rule TYPE ty_rule.
    DATA lv_stage TYPE i.
    DATA lv_stamp TYPE timestampl.
{{#killable}}
    " the kill switch: no gate opens while it is set; resume( ) opens it later
    IF killed( ) = abap_true.
      RETURN.
    ENDIF.
{{/killable}}
    SELECT COUNT(*) FROM zosd_l3_pile
      WHERE set_name = c_set
        AND run_id = iv_run
        AND stage_no = iv_stage
        AND status <> 'DONE'.
    IF sy-dbcnt > 0.
      RETURN.
    ENDIF.
    GET TIME STAMP FIELD lv_stamp.
    UPDATE zosd_l3_stage SET status = 'DONE' ended = lv_stamp
      WHERE run_id = iv_run
        AND stage_no = iv_stage
        AND status = 'OPEN'.
    lt_rules = rules( ).
    lv_stage = iv_stage + 1.
    WHILE lv_stage <= c_stages.
      UPDATE zosd_l3_stage SET status = 'OPEN' opened = lv_stamp
        WHERE run_id = iv_run
          AND stage_no = lv_stage
          AND status = 'WAITING'.
      IF sy-dbcnt <> 1.
        RETURN.
      ENDIF.
      rv_opened = abap_true.
      lt_piles = plan( iv_run = iv_run
                       iv_date = iv_date
                       iv_stage = lv_stage
                       iv_bind = iv_bind ).
      INSERT zosd_l3_pile FROM TABLE lt_piles.
      IF lt_piles IS NOT INITIAL.
        LOOP AT lt_piles INTO ls_pile.
          READ TABLE lt_rules INTO ls_rule WITH KEY rule = ls_pile-rule_name.
          submit( EXPORTING iv_date = iv_date
                            iv_run = iv_run
                            iv_bind = iv_bind
{{#with_params}}
                            is_params = is_params
{{/with_params}}
                            iv_jobname = ls_rule-jobname
                  CHANGING cs_pile = ls_pile ).
        ENDLOOP.
        RETURN.
      ENDIF.
      UPDATE zosd_l3_stage SET status = 'DONE' ended = lv_stamp
        WHERE run_id = iv_run
          AND stage_no = lv_stage.
      lv_stage = lv_stage + 1.
    ENDWHILE.
    LOOP AT lt_rules INTO ls_rule.
      finalise( iv_rule = ls_rule-rule
                iv_hash = ls_rule-model_hash
                iv_date = iv_date
                iv_run = iv_run
                iv_bind = iv_bind ).
    ENDLOOP.
    release( iv_run = iv_run iv_date = iv_date ).
  ENDMETHOD.

  METHOD fill.
    " a filter rule's keys go into the run's worklist, MODIFY on the full
    " key, so a retried pile writes the same rows; the alert log gets none
    DATA ls_work TYPE zosd_l3_work.
    DATA lv_key TYPE string.
    ls_work-set_name = c_set.
    ls_work-run_id = iv_run.
    ls_work-worklist = iv_worklist.
    ls_work-check_date = iv_date.
    LOOP AT it_keys INTO lv_key.
      ls_work-key_value = lv_key.
      MODIFY zosd_l3_work FROM ls_work.
      IF sy-subrc <> 0.
        cs_rule-failed = cs_rule-failed + 1.
      ENDIF.
    ENDLOOP.
    cs_rule-keys = lines( it_keys ).
    IF cs_rule-failed = 0.
      cs_rule-status = 'DONE'.
    ELSE.
      cs_rule-status = 'WRITE-FAILED'.
    ENDIF.
  ENDMETHOD.
{{#stages}}
{{#piles}}

  METHOD range_{{no}}.
{{#over_worklist}}
    " a pile over a worklist is the worklist's keys between its bounds, each
    " I EQ: a key between them that the filter did not select stays out
    DATA lt_values TYPE STANDARD TABLE OF zosd_l3_work-key_value WITH DEFAULT KEY.
    DATA lv_value TYPE zosd_l3_work-key_value.
{{/over_worklist}}
    DATA ls_range LIKE LINE OF rt_range.
    IF is_pile-pile_no = 0.
      RETURN.
    ENDIF.
    ls_range-sign = 'I'.
{{#over_worklist}}
    ls_range-option = 'EQ'.
    SELECT key_value FROM zosd_l3_work INTO TABLE lt_values
      WHERE run_id = is_pile-run_id
        AND worklist = {{name | literal}}
        AND key_value BETWEEN is_pile-range_low AND is_pile-range_high.
    LOOP AT lt_values INTO lv_value.
      ls_range-low = lv_value.
      APPEND ls_range TO rt_range.
    ENDLOOP.
    IF rt_range IS NOT INITIAL.
      RETURN.
    ENDIF.
    " no worklist row left: the bounds the plan recorded, each a key it held
    ls_range-low = is_pile-range_low.
    APPEND ls_range TO rt_range.
    ls_range-low = is_pile-range_high.
    APPEND ls_range TO rt_range.
{{/over_worklist}}
{{^over_worklist}}
    ls_range-low = is_pile-range_low.
    IF is_pile-range_high = is_pile-range_low.
      ls_range-option = 'EQ'.
    ELSE.
      ls_range-option = 'BT'.
      ls_range-high = is_pile-range_high.
    ENDIF.
    APPEND ls_range TO rt_range.
{{/over_worklist}}
  ENDMETHOD.
{{/piles}}
{{/stages}}

{{/staged}}
{{#sources}}
  METHOD restore_{{index}}.
    DELETE FROM {{table}}.
    INSERT {{table}} FROM TABLE it_keep.
  ENDMETHOD.

{{/sources}}
  METHOD rules.
    DATA ls_rule TYPE ty_rule.
{{#rules}}
    ls_rule-rule = c_rule_{{index}}.
    ls_rule-model_hash = c_hash_{{index}}.
    ls_rule-jobname = {{jobname | literal}}.
{{#staged}}
    ls_rule-stage_no = {{stage_no}}.
    ls_rule-filter = {{#filter}}abap_true{{/filter}}{{^filter}}abap_false{{/filter}}.
{{/staged}}
    APPEND ls_rule TO rt_rules.
{{/rules}}
  ENDMETHOD.

  METHOD run_rule.
{{^staged}}
    DATA lt_alerts TYPE string_table.
{{#piles}}
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lt_range TYPE RANGE OF {{source.table}}-{{source.key}}.
    DATA ls_range LIKE LINE OF lt_range.
{{/piles}}
{{#with_params}}
    DATA ls_params TYPE ty_params.
    ls_params = is_params.
{{/with_params}}
{{#params}}
{{#default}}
    IF ls_params-{{name}} IS INITIAL.
      ls_params-{{name}} = {{default | literal}}.
    ENDIF.
{{/default}}
{{/params}}
    rs_rule-rule = iv_rule.
{{#piles}}
    " the plan row of the pile: RUNNING now, DONE or FAILED at the end. A
    " pile that dumps leaves it as it was, and collect( ) reads the job
    SELECT SINGLE * FROM zosd_l3_pile INTO ls_pile
      WHERE set_name = c_set
        AND run_id = iv_run
        AND rule_name = iv_rule
        AND pile_no = iv_pile.
    IF sy-subrc <> 0.
      rs_rule-status = 'NO-PILE'.
      RETURN.
    ENDIF.
    rs_rule-piles = 1.
    ls_pile-status = 'RUNNING'.
    GET TIME STAMP FIELD ls_pile-started.
    UPDATE zosd_l3_pile FROM ls_pile.
    " the range is the plan row's, data and not a selection field; pile 0
    " is a rule that is not piled, over every row
    IF ls_pile-pile_no > 0.
      ls_range-sign = 'I'.
      ls_range-low = ls_pile-range_low.
      IF ls_pile-range_high = ls_pile-range_low.
        ls_range-option = 'EQ'.
      ELSE.
        ls_range-option = 'BT'.
        ls_range-high = ls_pile-range_high.
      ENDIF.
      APPEND ls_range TO lt_range.
    ENDIF.
{{/piles}}
    CASE iv_rule.
{{#rules}}
      WHEN c_rule_{{index}}.
        rs_rule-model_hash = c_hash_{{index}}.
        rs_rule-jobname = {{jobname | literal}}.
{{#param_args}}
{{#fallback}}
        IF ls_params-{{name}} IS INITIAL.
          ls_params-{{name}} = {{fallback | literal}}.
        ENDIF.
{{/fallback}}
{{/param_args}}
        lt_alerts = {{check_class}}=>check( iv_date{{#has_args}} = iv_date{{/has_args}}{{#piled}} it_range = lt_range{{/piled}}{{#param_args}} {{ref}} = ls_params-{{name}}{{/param_args}} ).
        write( EXPORTING iv_date = iv_date
                         iv_run = iv_run
{{#piles}}
                         iv_pile = iv_pile
{{/piles}}
                         iv_class = {{check_class | literal}}
                         iv_file = {{file | literal}}
                         iv_line = {{alert_line | literal}}
                         it_alerts = lt_alerts
                         iv_bind = iv_bind
               CHANGING cs_rule = rs_rule ).
{{/rules}}
      WHEN OTHERS.
        rs_rule-status = 'UNKNOWN'.
    ENDCASE.
{{#piles}}
    ls_pile-alerts = rs_rule-alerts.
    GET TIME STAMP FIELD ls_pile-ended.
    IF rs_rule-status = 'DONE'.
      ls_pile-status = 'DONE'.
      rs_rule-piles_done = 1.
    ELSE.
      ls_pile-status = 'FAILED'.
    ENDIF.
    UPDATE zosd_l3_pile FROM ls_pile.
{{/piles}}
{{/staged}}
{{#staged}}
    " a pile of one rule: its plan row RUNNING now, DONE or FAILED at the end;
    " a filter rule's keys go to its worklist, a check rule's alerts to the log
    DATA lt_alerts TYPE string_table.
    DATA lt_found TYPE string_table.
    DATA ls_pile TYPE zosd_l3_pile.
{{#stages}}
{{#piles}}
    DATA lt_range_{{no}} TYPE tt_range_{{no}}.
{{/piles}}
{{/stages}}
{{#rules}}
{{#filter}}
    DATA lt_keys_{{index}} TYPE {{check_class}}=>tt_range.
    DATA ls_key_{{index}} LIKE LINE OF lt_keys_{{index}}.
{{/filter}}
{{/rules}}
{{#with_params}}
    DATA ls_params TYPE ty_params.
    ls_params = is_params.
{{/with_params}}
{{#params}}
{{#default}}
    IF ls_params-{{name}} IS INITIAL.
      ls_params-{{name}} = {{default | literal}}.
    ENDIF.
{{/default}}
{{/params}}
    rs_rule-rule = iv_rule.
    SELECT SINGLE{{#resilience}} FOR UPDATE{{/resilience}} * FROM zosd_l3_pile INTO ls_pile
      WHERE set_name = c_set
        AND run_id = iv_run
        AND rule_name = iv_rule
        AND pile_no = iv_pile.
    IF sy-subrc <> 0.
      rs_rule-status = 'NO-PILE'.
      RETURN.
    ENDIF.
    rs_rule-piles = 1.
{{#resilience}}
    " only a PLANNED pile is worked. A job may start before the step that
    " submitted it commits: FOR UPDATE above makes it wait for that commit
    " and read the row as it was left, and a pile the doctor or collect( )
    " has taken as FAILED, or one another job runs, is not run twice
    IF ls_pile-status <> 'PLANNED'.
      rs_rule-status = 'NOT-PLANNED'.
      RETURN.
    ENDIF.
{{/resilience}}
{{#killable}}
    " the kill switch: the pile goes back to PLANNED without a job and its
    " attempt is not spent; resume( ) or the doctor submits it again
    IF killed( ) = abap_true.
      ls_pile-status = 'PLANNED'.
      ls_pile-reason = 'KILLED'.
      CLEAR: ls_pile-job_name, ls_pile-job_count.
      IF ls_pile-attempt > 0.
        ls_pile-attempt = ls_pile-attempt - 1.
      ENDIF.
      GET TIME STAMP FIELD ls_pile-ended.
      UPDATE zosd_l3_pile FROM ls_pile.
      rs_rule-status = 'KILLED'.
      RETURN.
    ENDIF.
{{/killable}}
    ls_pile-status = 'RUNNING'.
    GET TIME STAMP FIELD ls_pile-started.
    UPDATE zosd_l3_pile FROM ls_pile.
    CASE iv_rule.
{{#rules}}
      WHEN c_rule_{{index}}.
        rs_rule-model_hash = c_hash_{{index}}.
        rs_rule-jobname = {{jobname | literal}}.
        rs_rule-stage_no = {{stage_no}}.
{{#param_args}}
{{#fallback}}
        IF ls_params-{{name}} IS INITIAL.
          ls_params-{{name}} = {{fallback | literal}}.
        ENDIF.
{{/fallback}}
{{/param_args}}
{{#range}}
        lt_range_{{stage_no}} = range_{{stage_no}}( ls_pile ).
{{/range}}
{{#filter}}
        rs_rule-filter = abap_true.
        lt_keys_{{index}} = {{check_class}}=>keys( iv_date = iv_date{{#range}} it_range = lt_range_{{stage_no}}{{/range}}{{#param_args}} {{ref}} = ls_params-{{name}}{{/param_args}} ).
        LOOP AT lt_keys_{{index}} INTO ls_key_{{index}}.
          APPEND ls_key_{{index}}-low TO lt_found.
        ENDLOOP.
        fill( EXPORTING iv_run = iv_run
                        iv_date = iv_date
                        iv_worklist = {{worklist | literal}}
                        it_keys = lt_found
              CHANGING cs_rule = rs_rule ).
{{/filter}}
{{#check}}
        lt_alerts = {{check_class}}=>check( iv_date{{#has_args}} = iv_date{{/has_args}}{{#range}} it_range = lt_range_{{stage_no}}{{/range}}{{#param_args}} {{ref}} = ls_params-{{name}}{{/param_args}} ).
        write( EXPORTING iv_date = iv_date
                         iv_run = iv_run
                         iv_pile = iv_pile
                         iv_class = {{check_class | literal}}
                         iv_file = {{file | literal}}
                         iv_line = {{alert_line | literal}}
                         it_alerts = lt_alerts
                         iv_bind = iv_bind
               CHANGING cs_rule = rs_rule ).
{{/check}}
{{/rules}}
      WHEN OTHERS.
        rs_rule-status = 'UNKNOWN'.
    ENDCASE.
    " a filter pile's ALERTS column holds the keys it selected
    ls_pile-alerts = rs_rule-alerts + rs_rule-keys.
    GET TIME STAMP FIELD ls_pile-ended.
    IF rs_rule-status = 'DONE'.
      ls_pile-status = 'DONE'.
      rs_rule-piles_done = 1.
{{#fused}}
    ELSEIF rs_rule-status = 'FUSED'.
      " past the fuse: this pile wrote nothing and the rule stops for this run
      ls_pile-status = 'FUSED'.
      ls_pile-reason = 'MAX-ALERTS'.
{{/fused}}
    ELSE.
      ls_pile-status = 'FAILED'.
{{#resilience}}
      ls_pile-reason = rs_rule-status.
{{/resilience}}
    ENDIF.
    UPDATE zosd_l3_pile FROM ls_pile.
{{/staged}}
  ENDMETHOD.

  METHOD write.
    " the rows of one rule version and date go through the alert sink the run
    " is bound to ({{sink.name}}); the log variant is idempotent per (set,
    " rule, model hash, check date), see its class
{{#sink}}
    DATA ls_row TYPE {{table}}.
    DATA lt_rows TYPE {{iface}}=>tt_rows.
    DATA ls_group TYPE {{iface}}=>ty_group.
    DATA li_sink TYPE REF TO {{iface}}.
    DATA lv_alert TYPE string.
    DATA lv_count TYPE i.
{{#fused}}
    DATA lt_counts TYPE STANDARD TABLE OF zosd_l3_pile-alerts WITH DEFAULT KEY.
    DATA lv_before TYPE i.
    DATA lv_total TYPE i.
{{/fused}}
    ls_row-set_name = c_set.
    ls_row-rule_name = cs_rule-rule.
    ls_row-model_hash = cs_rule-model_hash.
    ls_row-check_date = iv_date.
{{#planned}}
    ls_row-pile_no = iv_pile.
{{/planned}}
    ls_row-run_id = iv_run.
    ls_row-rule_class = iv_class.
    ls_row-rule_file = iv_file.
    ls_row-rule_line = iv_line.
    GET TIME STAMP FIELD ls_row-run_ts.
    LOOP AT it_alerts INTO lv_alert.
      ls_row-alert_seq = sy-tabix.
      ls_row-alert_text = lv_alert.
      APPEND ls_row TO lt_rows.
    ENDLOOP.
    ls_group-set_name = c_set.
    ls_group-rule_name = cs_rule-rule.
    ls_group-model_hash = cs_rule-model_hash.
    ls_group-check_date = iv_date.
{{#planned}}
    ls_group-pile_no = iv_pile.
{{/planned}}
{{#fused}}
    " the fuse: the alerts the rule's DONE piles of this run wrote, and this
    " pile's: past c_max_alerts this pile writes nothing (its group's older
    " rows stay), and the rule is FUSED and never finalised in this run
    SELECT alerts FROM zosd_l3_pile INTO TABLE lt_counts
      WHERE set_name = c_set
        AND run_id = iv_run
        AND rule_name = cs_rule-rule
        AND status = 'DONE'.
    LOOP AT lt_counts INTO lv_before.
      lv_total = lv_total + lv_before.
    ENDLOOP.
    lv_total = lv_total + lines( lt_rows ).
    IF lv_total > c_max_alerts.
      cs_rule-failed = lines( lt_rows ).
      cs_rule-status = 'FUSED'.
      RETURN.
    ENDIF.
{{/fused}}
    li_sink = {{ports_class}}=>get_{{name}}( {{ports_class}}=>variant( iv_port = {{name | literal}} iv_bind = iv_bind ) ).
    lv_count = li_sink->put( it_rows = lt_rows
                             is_group = ls_group ).
    cs_rule-alerts = lines( lt_rows ).
    cs_rule-failed = cs_rule-alerts - lv_count.
{{/sink}}
    IF cs_rule-failed = 0.
      cs_rule-status = 'DONE'.
    ELSE.
      cs_rule-status = 'WRITE-FAILED'.
    ENDIF.
  ENDMETHOD.

{{#planned}}
  METHOD lock.
    " INSERT takes a set and date never run, UPDATE one whose last run
    " released it; each is one statement, so of two runs at once one wins.
    " The row stays after the release and names the latest run
    DATA ls_run TYPE zosd_l3_run.
    ls_run-set_name = c_set.
    ls_run-check_date = iv_date.
    ls_run-run_id = iv_run.
    ls_run-status = 'HELD'.
    GET TIME STAMP FIELD ls_run-started.
    INSERT zosd_l3_run FROM ls_run.
    IF sy-subrc = 0.
      rv_locked = abap_true.
      RETURN.
    ENDIF.
    UPDATE zosd_l3_run SET run_id = ls_run-run_id status = ls_run-status started = ls_run-started
      WHERE set_name = c_set
        AND check_date = iv_date
        AND status = 'RELEASED'.
    IF sy-dbcnt = 1.
      rv_locked = abap_true.
    ENDIF.
  ENDMETHOD.

  METHOD release.
    UPDATE zosd_l3_run SET status = 'RELEASED'
      WHERE set_name = c_set
        AND check_date = iv_date
        AND run_id = iv_run.
  ENDMETHOD.

  METHOD finalise.
    " every pile of the rule is DONE in this run: the rows of the same set,
    " rule, model hash and date that an older run wrote, under piles cut
    " elsewhere, go. The alert key has no run, so only the latest run of the
    " set and date may finalise: a late collect( ) of an older run would
    " delete the slots a newer run rewrote. Only the log keeps older runs; a
    " run bound to another variant of {{sink.name}} leaves the log as it is
    DATA lv_latest TYPE zosd_l3_run-run_id.
    SELECT SINGLE run_id FROM zosd_l3_run INTO lv_latest
      WHERE set_name = c_set
        AND check_date = iv_date.
    IF lv_latest <> iv_run.
      RETURN.
    ENDIF.
    IF {{ports_class}}=>variant( iv_port = {{sink.name | literal}} iv_bind = iv_bind ) <> 'log'.
      RETURN.
    ENDIF.
    DELETE FROM {{sink.table}}
      WHERE set_name = c_set
        AND rule_name = iv_rule
        AND model_hash = iv_hash
        AND check_date = iv_date
        AND run_id <> iv_run.
  ENDMETHOD.

{{/planned}}
  METHOD submit.
{{^planned}}
    " one job per rule: JOB_OPEN, SUBMIT ... VIA JOB, JOB_CLOSE started at
    " once; the rules do not depend on each other, so no job waits for one
{{/planned}}
{{#planned}}
    " one job per pile: JOB_OPEN, SUBMIT ... VIA JOB, JOB_CLOSE started at
    " once, named L3_<SET>_<nn>_<pppp> (the last four digits of the pile);
    " the job finds its range in the plan row by set, run, rule and pile
{{/planned}}
    DATA lv_jobname TYPE tbtcjob-jobname.
    DATA lv_jobcount TYPE tbtcjob-jobcount.
    DATA lv_released TYPE btch0000-char1.
{{^planned}}
    lv_jobname = cs_rule-jobname.
{{/planned}}
{{#planned}}
    DATA lv_pile TYPE n LENGTH 4.
    lv_pile = cs_pile-pile_no.
    CONCATENATE iv_jobname '_' lv_pile INTO lv_jobname.
{{#resilience}}
    " ATTEMPT counts the pile's submits: the first is 1, the doctor sets a retry's
    IF cs_pile-attempt = 0.
      cs_pile-attempt = 1.
    ENDIF.
{{/resilience}}
{{/planned}}
    CALL FUNCTION 'JOB_OPEN'
      EXPORTING
        jobname = lv_jobname
      IMPORTING
        jobcount = lv_jobcount
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
{{^planned}}
      cs_rule-status = 'OPEN-FAILED'.
{{/planned}}
{{#planned}}
      cs_pile-status = 'FAILED'.
{{#resilience}}
      cs_pile-reason = 'JOB-OPEN'.
      GET TIME STAMP FIELD cs_pile-ended.
{{/resilience}}
      UPDATE zosd_l3_pile FROM cs_pile.
{{/planned}}
      RETURN.
    ENDIF.
{{^planned}}
    cs_rule-jobcount = lv_jobcount.
    SUBMIT {{report}}
      WITH p_rule = cs_rule-rule
{{/planned}}
{{#planned}}
    cs_pile-job_name = lv_jobname.
    cs_pile-job_count = lv_jobcount.
    UPDATE zosd_l3_pile FROM cs_pile.
    SUBMIT {{report}}
      WITH p_rule = cs_pile-rule_name
{{/planned}}
      WITH p_date = iv_date
      WITH p_run = iv_run
{{#planned}}
      WITH p_pile = cs_pile-pile_no
{{/planned}}
      WITH p_bind = iv_bind
{{#params}}
      WITH {{screen}} = is_params-{{name}}
{{/params}}
      VIA JOB lv_jobname NUMBER lv_jobcount
      AND RETURN.
    CALL FUNCTION 'JOB_CLOSE'
      EXPORTING
        jobname = lv_jobname
        jobcount = lv_jobcount
        strtimmed = 'X'
      IMPORTING
        job_was_released = lv_released
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0 OR lv_released <> 'X'.
{{^planned}}
      cs_rule-status = 'CLOSE-FAILED'.
      RETURN.
{{/planned}}
{{#planned}}
      cs_pile-status = 'FAILED'.
{{#resilience}}
      cs_pile-reason = 'JOB-CLOSE'.
      GET TIME STAMP FIELD cs_pile-ended.
{{/resilience}}
      UPDATE zosd_l3_pile FROM cs_pile.
{{/planned}}
    ENDIF.
{{^planned}}
    cs_rule-status = 'SUBMITTED'.
{{/planned}}
  ENDMETHOD.

{{#schedule}}
  METHOD schedule.
    " JOB_OPEN, the driver as the job's step, JOB_CLOSE at a date and time with
    " a period ({{field}}): the job facade and a system both read SDLSTRTDT and
    " SDLSTRTTM as system time, which sy-datum and sy-uzeit are
    DATA lv_jobname TYPE tbtcjob-jobname.
    DATA lv_date TYPE d.
    DATA lv_time TYPE t.
    DATA lv_period TYPE tbtcjob-{{field}}.
    DATA lv_released TYPE btch0000-char1.
{{#resilience}}
    " the doctor goes with the schedule, as a periodic job of its own
    schedule_doctor( ).
{{/resilience}}
    " already scheduled: the waiting instance is the chain, a second would run the set twice
    rv_jobcount = scheduled( ).
    IF rv_jobcount IS NOT INITIAL.
      RETURN.
    ENDIF.
    lv_jobname = c_driver.
    lv_period = {{count}}.
    GET TIME.
    lv_date = sy-datum.
{{#at}}
    lv_time = {{at | literal}}.
    " a first start that has passed today is tomorrow's
    IF lv_time <= sy-uzeit.
      lv_date = lv_date + 1.
    ENDIF.
{{/at}}
{{^at}}
    lv_time = sy-uzeit.
{{/at}}
    CALL FUNCTION 'JOB_OPEN'
      EXPORTING
        jobname = lv_jobname
      IMPORTING
        jobcount = rv_jobcount
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      CLEAR rv_jobcount.
      RETURN.
    ENDIF.
    SUBMIT {{report}}
      WITH p_mode = 'D'
      VIA JOB lv_jobname NUMBER rv_jobcount
      AND RETURN.
    CALL FUNCTION 'JOB_CLOSE'
      EXPORTING
        jobname = lv_jobname
        jobcount = rv_jobcount
        sdlstrtdt = lv_date
        sdlstrttm = lv_time
        {{field}} = lv_period
      IMPORTING
        job_was_released = lv_released
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0 OR lv_released <> 'X'.
      " not released: the opened job goes, it would only wait unreleased
      CALL FUNCTION 'BP_JOB_DELETE'
        EXPORTING
          jobname = lv_jobname
          jobcount = rv_jobcount
        EXCEPTIONS
          OTHERS = 1.
      CLEAR rv_jobcount.
    ENDIF.
  ENDMETHOD.

  METHOD scheduled.
    DATA ls_select TYPE btcselect.
    DATA lt_jobs TYPE STANDARD TABLE OF tbtcjob WITH DEFAULT KEY.
    DATA ls_job TYPE tbtcjob.
    ls_select-jobname = c_driver.
    ls_select-username = sy-uname.
    ls_select-schedul = 'X'.
    CALL FUNCTION 'BP_JOB_SELECT'
      EXPORTING
        jobselect_dialog = 'N'
        jobsel_param_in = ls_select
      TABLES
        jobselect_joblist = lt_jobs
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      RETURN.
    ENDIF.
    LOOP AT lt_jobs INTO ls_job WHERE status = 'S'.
      rv_jobcount = ls_job-jobcount.
      RETURN.
    ENDLOOP.
  ENDMETHOD.

  METHOD unschedule.
    " the driver's instance that waits for its start (status S) is the chain:
    " a periodic job's successor is made when an instance starts, so deleting
    " the waiting one ends it (measured on a system, docs/job-standard-fms.md)
    DATA ls_select TYPE btcselect.
    DATA lt_jobs TYPE STANDARD TABLE OF tbtcjob WITH DEFAULT KEY.
    DATA ls_job TYPE tbtcjob.
{{#resilience}}
    " the doctor's job goes with the schedule
    rv_deleted = unschedule_doctor( ).
{{/resilience}}
    ls_select-jobname = c_driver.
    ls_select-username = sy-uname.
    ls_select-schedul = 'X'.
    CALL FUNCTION 'BP_JOB_SELECT'
      EXPORTING
        jobselect_dialog = 'N'
        jobsel_param_in = ls_select
      TABLES
        jobselect_joblist = lt_jobs
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      RETURN.
    ENDIF.
    LOOP AT lt_jobs INTO ls_job WHERE status = 'S'.
      CALL FUNCTION 'BP_JOB_DELETE'
        EXPORTING
          jobname = ls_job-jobname
          jobcount = ls_job-jobcount
        EXCEPTIONS
          OTHERS = 1.
      IF sy-subrc = 0.
        rv_deleted = rv_deleted + 1.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.

{{/schedule}}
  METHOD collect.
{{^planned}}
    " the jobs of the run, found by BP_JOB_SELECT, each read by SHOW_JOBSTATE;
    " a finished rule counts the rows its job wrote under this run
    DATA ls_select TYPE btcselect.
    DATA lt_jobs TYPE STANDARD TABLE OF tbtcjob WITH DEFAULT KEY.
{{/planned}}
{{#piles}}
    " the plan rows of the run, each open pile's job read by SHOW_JOBSTATE: a
    " pile is DONE when its job wrote so; a job that ended without that, or
    " none at all, leaves the pile FAILED. A rule is DONE (and finalised) when
    " every pile is, PARTIAL when a pile failed, else the state of an open job
    DATA lt_piles TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lv_open TYPE c LENGTH 12.
    DATA lv_state TYPE c LENGTH 12.
    DATA lv_lost TYPE abap_bool.
    DATA lv_final TYPE abap_bool VALUE abap_true.
{{/piles}}
{{#staged}}
    " the run's plan rows and gate rows. An open pile's job is read by
    " SHOW_JOBSTATE: a job that ended without its pile DONE, or no job at
    " all, makes the pile FAILED. A stage whose piles are all DONE while its
    " gate is still OPEN (its last job ended before it could advance) is
    " advanced here. A stage with a FAILED pile is PARTIAL once every pile of
    " it is final, and the stages after it are NOT-RUN: their gate closes, so
    " no late job opens one. The run is final when every stage is DONE, or a
    " stage is PARTIAL and the rest NOT-RUN; only then is the lock released
    DATA lt_piles TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lt_gates TYPE STANDARD TABLE OF zosd_l3_stage WITH DEFAULT KEY.
    DATA ls_gate TYPE zosd_l3_stage.
    DATA ls_stage TYPE ty_stage.
    DATA lv_state TYPE c LENGTH 12.
    DATA lv_open TYPE c LENGTH 12.
    DATA lv_lost TYPE abap_bool.
    DATA lv_final TYPE abap_bool VALUE abap_true.
    DATA lv_closed TYPE abap_bool.
    DATA lv_stamp TYPE timestampl.
{{/staged}}
{{#fused}}
    DATA lv_fused TYPE abap_bool.
{{/fused}}
    DATA ls_rule TYPE ty_rule.
    DATA lv_aborted TYPE btch0000-char1.
    DATA lv_finished TYPE btch0000-char1.
    DATA lv_running TYPE btch0000-char1.
    DATA lv_ready TYPE btch0000-char1.
    DATA lv_scheduled TYPE btch0000-char1.
    DATA lv_preliminary TYPE btch0000-char1.
    rs_result = is_result.
    CLEAR: rs_result-rules, rs_result-alerts.
{{^planned}}
    ls_select-jobname = {{jobs | literal}}.
    ls_select-username = sy-uname.
    CALL FUNCTION 'BP_JOB_SELECT'
      EXPORTING
        jobselect_dialog = 'N'
        jobsel_param_in = ls_select
      TABLES
        jobselect_joblist = lt_jobs
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      CLEAR lt_jobs.
    ENDIF.
    LOOP AT is_result-rules INTO ls_rule.
      IF ls_rule-jobcount IS NOT INITIAL.
        READ TABLE lt_jobs TRANSPORTING NO FIELDS
          WITH KEY jobname = ls_rule-jobname jobcount = ls_rule-jobcount.
        IF sy-subrc <> 0.
          ls_rule-status = 'NO-JOB'.
        ELSE.
          CLEAR: lv_aborted, lv_finished, lv_running, lv_ready, lv_scheduled, lv_preliminary.
          CALL FUNCTION 'SHOW_JOBSTATE'
            EXPORTING
              jobname = ls_rule-jobname
              jobcount = ls_rule-jobcount
            IMPORTING
              aborted = lv_aborted
              finished = lv_finished
              preliminary = lv_preliminary
              ready = lv_ready
              running = lv_running
              scheduled = lv_scheduled
            EXCEPTIONS
              OTHERS = 1.
          IF sy-subrc <> 0.
            ls_rule-status = 'NO-JOB'.
          ELSEIF lv_finished = 'X'.
            ls_rule-status = 'FINISHED'.
          ELSEIF lv_aborted = 'X'.
            ls_rule-status = 'ABORTED'.
          ELSEIF lv_running = 'X'.
            ls_rule-status = 'RUNNING'.
          ELSEIF lv_ready = 'X'.
            ls_rule-status = 'READY'.
          ELSEIF lv_scheduled = 'X'.
            ls_rule-status = 'SCHEDULED'.
          ELSEIF lv_preliminary = 'X'.
            ls_rule-status = 'PRELIMINARY'.
          ELSE.
            ls_rule-status = 'OTHER'.
          ENDIF.
        ENDIF.
      ENDIF.
      IF ls_rule-status = 'FINISHED' OR ls_rule-status = 'DONE'.
        SELECT COUNT(*) FROM zosd_l3_alert
          WHERE set_name = c_set
            AND rule_name = ls_rule-rule
            AND model_hash = ls_rule-model_hash
            AND check_date = is_result-check_date
            AND run_id = is_result-run_id.
        ls_rule-alerts = sy-dbcnt.
        rs_result-alerts = rs_result-alerts + ls_rule-alerts.
      ENDIF.
      APPEND ls_rule TO rs_result-rules.
    ENDLOOP.
{{/planned}}
{{#piles}}
    SELECT * FROM zosd_l3_pile INTO TABLE lt_piles
      WHERE set_name = c_set
        AND run_id = is_result-run_id
      ORDER BY PRIMARY KEY.
    LOOP AT is_result-rules INTO ls_rule.
      CLEAR: ls_rule-alerts, ls_rule-piles, ls_rule-piles_done, lv_open, lv_lost.
      LOOP AT lt_piles INTO ls_pile WHERE rule_name = ls_rule-rule.
        ls_rule-piles = ls_rule-piles + 1.
        IF ls_pile-status <> 'DONE' AND ls_pile-status <> 'FAILED'.
          lv_state = 'NO-JOB'.
          IF ls_pile-job_count IS NOT INITIAL.
            CLEAR: lv_aborted, lv_finished, lv_running, lv_ready, lv_scheduled, lv_preliminary.
            CALL FUNCTION 'SHOW_JOBSTATE'
              EXPORTING
                jobname = ls_pile-job_name
                jobcount = ls_pile-job_count
              IMPORTING
                aborted = lv_aborted
                finished = lv_finished
                preliminary = lv_preliminary
                ready = lv_ready
                running = lv_running
                scheduled = lv_scheduled
              EXCEPTIONS
                OTHERS = 1.
            IF sy-subrc <> 0.
              lv_state = 'NO-JOB'.
            ELSEIF lv_finished = 'X'.
              lv_state = 'FINISHED'.
            ELSEIF lv_aborted = 'X'.
              lv_state = 'ABORTED'.
            ELSEIF lv_running = 'X'.
              lv_state = 'RUNNING'.
            ELSEIF lv_ready = 'X'.
              lv_state = 'READY'.
            ELSEIF lv_scheduled = 'X'.
              lv_state = 'SCHEDULED'.
            ELSEIF lv_preliminary = 'X'.
              lv_state = 'PRELIMINARY'.
            ELSE.
              lv_state = 'OTHER'.
            ENDIF.
          ENDIF.
          IF lv_state = 'FINISHED' OR lv_state = 'ABORTED' OR lv_state = 'NO-JOB'.
            " the job is over: the row as it left it, DONE or not
            SELECT SINGLE * FROM zosd_l3_pile INTO ls_pile
              WHERE set_name = c_set
                AND run_id = ls_pile-run_id
                AND rule_name = ls_pile-rule_name
                AND pile_no = ls_pile-pile_no.
            IF ls_pile-status <> 'DONE'.
              ls_pile-status = 'FAILED'.
              GET TIME STAMP FIELD ls_pile-ended.
              UPDATE zosd_l3_pile FROM ls_pile.
            ENDIF.
          ELSE.
            lv_final = abap_false.
            IF lv_open IS INITIAL.
              lv_open = lv_state.
            ENDIF.
          ENDIF.
        ENDIF.
        IF ls_pile-status = 'DONE'.
          ls_rule-piles_done = ls_rule-piles_done + 1.
          ls_rule-alerts = ls_rule-alerts + ls_pile-alerts.
        ELSEIF ls_pile-status = 'FAILED'.
          lv_lost = abap_true.
        ENDIF.
      ENDLOOP.
      IF ls_rule-piles_done = ls_rule-piles.
        ls_rule-status = 'DONE'.
        finalise( iv_rule = ls_rule-rule
                  iv_hash = ls_rule-model_hash
                  iv_date = is_result-check_date
                  iv_run = is_result-run_id
                  iv_bind = is_result-bind ).
      ELSEIF lv_lost = abap_true.
        ls_rule-status = 'PARTIAL'.
      ELSE.
        ls_rule-status = lv_open.
      ENDIF.
      rs_result-alerts = rs_result-alerts + ls_rule-alerts.
      APPEND ls_rule TO rs_result-rules.
    ENDLOOP.
    " every pile final (DONE or FAILED): the run lets the next one in
    IF lv_final = abap_true.
      rs_result-status = 'DONE'.
      LOOP AT rs_result-rules INTO ls_rule WHERE status <> 'DONE'.
        rs_result-status = 'PARTIAL'.
      ENDLOOP.
      release( iv_run = is_result-run_id iv_date = is_result-check_date ).
    ELSE.
      rs_result-status = 'RUNNING'.
    ENDIF.
{{/piles}}
{{#staged}}
    CLEAR rs_result-stages.
    SELECT * FROM zosd_l3_pile INTO TABLE lt_piles
      WHERE set_name = c_set
        AND run_id = is_result-run_id
      ORDER BY PRIMARY KEY.
    LOOP AT lt_piles INTO ls_pile WHERE status <> 'DONE' AND status <> 'FAILED'{{#fused}} AND status <> 'FUSED'{{/fused}}.
      lv_state = 'NO-JOB'.
      IF ls_pile-job_count IS NOT INITIAL.
        CLEAR: lv_aborted, lv_finished, lv_running, lv_ready, lv_scheduled, lv_preliminary.
        CALL FUNCTION 'SHOW_JOBSTATE'
          EXPORTING
            jobname = ls_pile-job_name
            jobcount = ls_pile-job_count
          IMPORTING
            aborted = lv_aborted
            finished = lv_finished
            preliminary = lv_preliminary
            ready = lv_ready
            running = lv_running
            scheduled = lv_scheduled
          EXCEPTIONS
            OTHERS = 1.
        IF sy-subrc <> 0.
          lv_state = 'NO-JOB'.
        ELSEIF lv_finished = 'X'.
          lv_state = 'FINISHED'.
        ELSEIF lv_aborted = 'X'.
          lv_state = 'ABORTED'.
        ELSE.
          lv_state = 'OPEN'.
        ENDIF.
      ENDIF.
      IF lv_state <> 'OPEN'.
        " the job is over: the row as it left it, DONE or not
        SELECT SINGLE * FROM zosd_l3_pile INTO ls_pile
          WHERE set_name = c_set
            AND run_id = ls_pile-run_id
            AND rule_name = ls_pile-rule_name
            AND pile_no = ls_pile-pile_no.
        IF ls_pile-status <> 'DONE'{{#fused}} AND ls_pile-status <> 'FUSED'{{/fused}}.
          ls_pile-status = 'FAILED'.
          GET TIME STAMP FIELD ls_pile-ended.
          UPDATE zosd_l3_pile FROM ls_pile.
        ENDIF.
      ENDIF.
    ENDLOOP.
    " a gate the last job of its stage did not get to
    SELECT * FROM zosd_l3_stage INTO TABLE lt_gates
      WHERE run_id = is_result-run_id
      ORDER BY PRIMARY KEY.
    LOOP AT lt_gates INTO ls_gate WHERE status = 'OPEN'.
      advance( iv_run = is_result-run_id
               iv_date = is_result-check_date
               iv_stage = ls_gate-stage_no
               iv_bind = is_result-bind{{#with_params}} is_params = is_result-params{{/with_params}} ).
    ENDLOOP.
    SELECT * FROM zosd_l3_pile INTO TABLE lt_piles
      WHERE set_name = c_set
        AND run_id = is_result-run_id
      ORDER BY PRIMARY KEY.
    SELECT * FROM zosd_l3_stage INTO TABLE lt_gates
      WHERE run_id = is_result-run_id
      ORDER BY PRIMARY KEY.
    LOOP AT lt_gates INTO ls_gate.
      CLEAR ls_stage.
      ls_stage-stage_no = ls_gate-stage_no.
      ls_stage-stage = ls_gate-stage_name.
      CLEAR lv_lost.
      lv_open = ls_gate-status.
      LOOP AT lt_piles INTO ls_pile WHERE stage_no = ls_gate-stage_no.
        ls_stage-piles = ls_stage-piles + 1.
        IF ls_pile-status = 'DONE'.
          ls_stage-piles_done = ls_stage-piles_done + 1.
        ELSEIF ls_pile-status = 'FAILED'.
          lv_lost = abap_true.
{{#fused}}
        ELSEIF ls_pile-status = 'FUSED'.
          lv_lost = abap_true.
{{/fused}}
        ELSE.
          lv_open = 'RUNNING'.
        ENDIF.
      ENDLOOP.
      GET TIME STAMP FIELD lv_stamp.
      IF ls_gate-status = 'WAITING' AND lv_closed = abap_true.
        " after a PARTIAL stage: never opened, and now never opens
        UPDATE zosd_l3_stage SET status = 'NOT-RUN' ended = lv_stamp
          WHERE run_id = is_result-run_id
            AND stage_no = ls_gate-stage_no
            AND status = 'WAITING'.
        ls_stage-status = 'NOT-RUN'.
      ELSEIF ls_gate-status = 'WAITING'.
        ls_stage-status = 'WAITING'.
        lv_final = abap_false.
      ELSEIF ls_gate-status = 'NOT-RUN'.
        ls_stage-status = 'NOT-RUN'.
        lv_closed = abap_true.
      ELSEIF lv_open = 'RUNNING'.
        ls_stage-status = 'RUNNING'.
        lv_final = abap_false.
      ELSEIF lv_lost = abap_true.
        UPDATE zosd_l3_stage SET status = 'PARTIAL' ended = lv_stamp
          WHERE run_id = is_result-run_id
            AND stage_no = ls_gate-stage_no.
        ls_stage-status = 'PARTIAL'.
        lv_closed = abap_true.
      ELSE.
        ls_stage-status = ls_gate-status.
        IF ls_stage-status = 'PARTIAL'.
          lv_closed = abap_true.
        ELSEIF ls_stage-status <> 'DONE'.
          lv_final = abap_false.
        ENDIF.
      ENDIF.
      APPEND ls_stage TO rs_result-stages.
    ENDLOOP.
    LOOP AT is_result-rules INTO ls_rule.
      CLEAR: ls_rule-alerts, ls_rule-keys, ls_rule-piles, ls_rule-piles_done, lv_open, lv_lost.
{{#fused}}
      CLEAR lv_fused.
{{/fused}}
      LOOP AT lt_piles INTO ls_pile WHERE rule_name = ls_rule-rule.
        ls_rule-piles = ls_rule-piles + 1.
        IF ls_pile-status = 'DONE'.
          ls_rule-piles_done = ls_rule-piles_done + 1.
          IF ls_rule-filter = abap_true.
            ls_rule-keys = ls_rule-keys + ls_pile-alerts.
          ELSE.
            ls_rule-alerts = ls_rule-alerts + ls_pile-alerts.
          ENDIF.
        ELSEIF ls_pile-status = 'FAILED'.
          lv_lost = abap_true.
{{#fused}}
        ELSEIF ls_pile-status = 'FUSED'.
          lv_fused = abap_true.
{{/fused}}
        ELSEIF lv_open IS INITIAL.
          lv_open = ls_pile-status.
        ENDIF.
      ENDLOOP.
      READ TABLE rs_result-stages INTO ls_stage WITH KEY stage_no = ls_rule-stage_no.
      IF ls_stage-status = 'WAITING' OR ls_stage-status = 'NOT-RUN'.
        ls_rule-status = ls_stage-status.
      ELSEIF ls_rule-piles_done = ls_rule-piles.
        ls_rule-status = 'DONE'.
        finalise( iv_rule = ls_rule-rule
                  iv_hash = ls_rule-model_hash
                  iv_date = is_result-check_date
                  iv_run = is_result-run_id
                  iv_bind = is_result-bind ).
      ELSEIF lv_open IS NOT INITIAL.
        ls_rule-status = lv_open.
      ELSE.
        ls_rule-status = 'PARTIAL'.
      ENDIF.
{{#fused}}
      " a pile past the fuse: the rule is FUSED, and was not finalised
      IF lv_fused = abap_true.
        ls_rule-status = 'FUSED'.
      ENDIF.
{{/fused}}
      rs_result-alerts = rs_result-alerts + ls_rule-alerts.
      APPEND ls_rule TO rs_result-rules.
    ENDLOOP.
    IF lv_final = abap_true.
      rs_result-status = 'DONE'.
      LOOP AT rs_result-stages INTO ls_stage WHERE status <> 'DONE'.
        rs_result-status = 'PARTIAL'.
      ENDLOOP.
      release( iv_run = is_result-run_id iv_date = is_result-check_date ).
    ELSE.
      rs_result-status = 'RUNNING'.
    ENDIF.
{{/staged}}
  ENDMETHOD.
{{#resilience}}

  METHOD dry.
    " a dry run: every stage planned and every check run in this step, the
    " alerts into the capture variant of {{sink.name}} instead of the log,
    " and no finalise (it runs for the log only). The result says DRY and
    " holds the rows a real run would have written
    DATA lv_bind TYPE string.
    DATA ls_rule TYPE ty_rule.
{{#dry_run}}
    {{capture}}=>reset( ).
{{/dry_run}}
    CONCATENATE iv_bind ',{{sink.name}}=capture' INTO lv_bind.
    rs_result = run( iv_date = iv_date
                     iv_mode = c_sequential
                     iv_bind = lv_bind
{{#with_params}}
                     is_params = is_params
{{/with_params}}
                     iv_allow_replay = iv_allow_replay
                     iv_dry_run = abap_false ).
{{#dry_run}}
    rs_result-dry = {{capture}}=>rows( ).
{{/dry_run}}
    IF rs_result-status = 'DONE'.
      rs_result-status = 'DRY'.
    ENDIF.
    LOOP AT rs_result-rules INTO ls_rule WHERE status = 'DONE'.
      ls_rule-status = 'DRY'.
      MODIFY rs_result-rules FROM ls_rule.
    ENDLOOP.
  ENDMETHOD.

  METHOD resume.
    " an open run is one whose lock names it HELD; a run without it is final
    " and is not resumed. The work is heal( ) with no waiting
    DATA lv_now TYPE timestamp.
    DATA ls_gate TYPE zosd_l3_stage.
    DATA ls_lock TYPE zosd_l3_run.
    lv_now = iv_now.
    IF lv_now IS INITIAL.
      GET TIME STAMP FIELD lv_now.
    ENDIF.
{{#killable}}
    IF killed( ) = abap_true.
      act( EXPORTING iv_run = iv_run
                     iv_action = 'KILLED'
                     iv_reason = 'the kill switch is set'
                     iv_audit = abap_false
           CHANGING ct_report = rt_report ).
      RETURN.
    ENDIF.
{{/killable}}
    SELECT SINGLE * FROM zosd_l3_stage INTO ls_gate
      WHERE run_id = iv_run
        AND stage_no = 1.
    SELECT SINGLE * FROM zosd_l3_run INTO ls_lock
      WHERE set_name = c_set
        AND check_date = ls_gate-check_date.
    IF sy-subrc <> 0 OR ls_lock-run_id <> iv_run OR ls_lock-status <> 'HELD'.
      act( EXPORTING iv_run = iv_run
                     iv_date = ls_gate-check_date
                     iv_action = 'NOT-OPEN'
                     iv_reason = 'the run does not hold its lock'
                     iv_audit = abap_false
           CHANGING ct_report = rt_report ).
      RETURN.
    ENDIF.
    heal( EXPORTING iv_run = ls_lock-run_id
                    iv_date = ls_lock-check_date
                    iv_now = lv_now
                    iv_force = abap_true
                    iv_bind = iv_bind
{{#with_params}}
                    is_params = is_params
{{/with_params}}
          CHANGING ct_report = rt_report ).
  ENDMETHOD.

  METHOD doctor.
    " heal( ) every open run of the set (a lock HELD); then the lock of a run
    " that is stale goes: with every pile final (DONE, FUSED, or FAILED past
    " the retry budget) and no gate that could still advance, released and
    " made final as collect( ) does; with no plan row at all, released. Each
    " release is one UPDATE from HELD, and only its sy-dbcnt = 1 acts. Then
    " purge( ). The kill switch set: one row KILLED and nothing else
    DATA lv_now TYPE timestamp.
    DATA lv_stale TYPE timestamp.
    DATA lt_locks TYPE STANDARD TABLE OF zosd_l3_run WITH DEFAULT KEY.
    DATA ls_lock TYPE zosd_l3_run.
    DATA lt_piles TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lt_gates TYPE STANDARD TABLE OF zosd_l3_stage WITH DEFAULT KEY.
    DATA ls_gate TYPE zosd_l3_stage.
    DATA lv_final TYPE abap_bool.
    DATA lv_open TYPE i.
    DATA lv_prev TYPE i.
    DATA ls_prev TYPE zosd_l3_stage.
    DATA lv_reason TYPE zosd_l3_doctor-reason.
    DATA ls_result TYPE ty_result.
    DATA lt_purged TYPE tt_doctor.
    lv_now = iv_now.
    IF lv_now IS INITIAL.
      GET TIME STAMP FIELD lv_now.
    ENDIF.
{{#killable}}
    IF killed( ) = abap_true.
      act( EXPORTING iv_run = ''
                     iv_action = 'KILLED'
                     iv_reason = 'the kill switch is set'
                     iv_audit = abap_false
           CHANGING ct_report = rt_report ).
      RETURN.
    ENDIF.
{{/killable}}
    lv_stale = ago( iv_now = lv_now iv_secs = c_stale ).
    SELECT * FROM zosd_l3_run INTO TABLE lt_locks
      WHERE set_name = c_set
        AND status = 'HELD'
      ORDER BY PRIMARY KEY.
    LOOP AT lt_locks INTO ls_lock.
      heal( EXPORTING iv_run = ls_lock-run_id
                      iv_date = ls_lock-check_date
                      iv_now = lv_now
                      iv_force = abap_false
            CHANGING ct_report = rt_report ).
      IF ls_lock-started > lv_stale.
        CONTINUE.
      ENDIF.
      SELECT * FROM zosd_l3_pile INTO TABLE lt_piles
        WHERE set_name = c_set
          AND run_id = ls_lock-run_id
        ORDER BY PRIMARY KEY.
      SELECT * FROM zosd_l3_stage INTO TABLE lt_gates
        WHERE run_id = ls_lock-run_id
        ORDER BY PRIMARY KEY.
      IF lt_piles IS INITIAL AND lt_gates IS INITIAL.
        lv_reason = 'NO-PLAN'.
      ELSE.
        " final: no pile can still run or be retried, no gate can still advance
        lv_final = abap_true.
        LOOP AT lt_piles INTO ls_pile.
          IF ls_pile-status = 'DONE' OR ls_pile-status = 'FUSED'.
            CONTINUE.
          ENDIF.
          IF ls_pile-status = 'FAILED' AND ls_pile-attempt > c_retry_max.
            CONTINUE.
          ENDIF.
          lv_final = abap_false.
        ENDLOOP.
        LOOP AT lt_gates INTO ls_gate WHERE status = 'OPEN'.
          lv_open = 0.
          LOOP AT lt_piles INTO ls_pile WHERE stage_no = ls_gate-stage_no AND status <> 'DONE'.
            lv_open = lv_open + 1.
          ENDLOOP.
          IF lv_open = 0.
            lv_final = abap_false.
          ENDIF.
        ENDLOOP.
        " nor a stage DONE whose next gate never opened (its advance( ) was stopped)
        LOOP AT lt_gates INTO ls_gate WHERE status = 'WAITING' AND stage_no > 1.
          lv_prev = ls_gate-stage_no - 1.
          READ TABLE lt_gates INTO ls_prev WITH KEY stage_no = lv_prev.
          IF sy-subrc = 0 AND ls_prev-status = 'DONE'.
            lv_final = abap_false.
          ENDIF.
        ENDLOOP.
        IF lv_final = abap_false.
          CONTINUE.
        ENDIF.
        lv_reason = 'ALL-FINAL'.
      ENDIF.
      UPDATE zosd_l3_run SET status = 'RELEASED'
        WHERE set_name = c_set
          AND check_date = ls_lock-check_date
          AND run_id = ls_lock-run_id
          AND status = 'HELD'.
      IF sy-dbcnt <> 1.
        CONTINUE.
      ENDIF.
      IF lv_reason = 'ALL-FINAL'.
        " made final as collect( ) makes it: a stage with a lost pile PARTIAL,
        " the stages after it NOT-RUN, every DONE rule finalised
        CLEAR ls_result.
        ls_result-set_name = c_set.
        ls_result-run_id = ls_lock-run_id.
        ls_result-check_date = ls_lock-check_date.
        ls_result-mode = c_parallel.
        ls_result-rules = rules( ).
        ls_result = collect( ls_result ).
      ENDIF.
      act( EXPORTING iv_run = ls_lock-run_id
                     iv_date = ls_lock-check_date
                     iv_action = 'RELEASE'
                     iv_reason = lv_reason
                     iv_now = lv_now
           CHANGING ct_report = rt_report ).
    ENDLOOP.
    lt_purged = purge( lv_now ).
    APPEND LINES OF lt_purged TO rt_report.
  ENDMETHOD.

  METHOD heal.
    " one open run. Every change is one UPDATE on the state it read, so of two
    " callers at once only the one that gets sy-dbcnt = 1 acts: a pile whose
    " job is over without the pile DONE is FAILED; a FAILED pile within the
    " retry budget goes again once due( ), a PLANNED pile without a job once
    " it is stale; an OPEN gate with no pile is planned again once stale, one
    " whose piles are all DONE advances. iv_force (resume( )): no waiting
    DATA lt_piles TYPE tt_pile.
    DATA ls_pile TYPE zosd_l3_pile.
    DATA lt_new TYPE tt_pile.
    DATA lt_gates TYPE STANDARD TABLE OF zosd_l3_stage WITH DEFAULT KEY.
    DATA ls_gate TYPE zosd_l3_stage.
    DATA lt_rules TYPE tt_rule.
    DATA ls_rule TYPE ty_rule.
    DATA lv_stale TYPE timestamp.
    DATA lv_since TYPE timestamp.
    DATA lv_reason TYPE zosd_l3_pile-reason.
    DATA lv_next TYPE i.
    DATA lv_count TYPE i.
    DATA lv_open TYPE i.
    DATA lv_prev TYPE i.
    DATA ls_prev TYPE zosd_l3_stage.
    DATA lv_aborted TYPE btch0000-char1.
    DATA lv_finished TYPE btch0000-char1.
    DATA lv_running TYPE btch0000-char1.
    DATA lv_ready TYPE btch0000-char1.
    DATA lv_scheduled TYPE btch0000-char1.
    DATA lv_preliminary TYPE btch0000-char1.
    lv_stale = ago( iv_now = iv_now iv_secs = c_stale ).
    lt_rules = rules( ).
    SELECT * FROM zosd_l3_stage INTO TABLE lt_gates
      WHERE run_id = iv_run
      ORDER BY PRIMARY KEY.
    SELECT * FROM zosd_l3_pile INTO TABLE lt_piles
      WHERE set_name = c_set
        AND run_id = iv_run
      ORDER BY PRIMARY KEY.
    LOOP AT lt_piles INTO ls_pile WHERE status = 'PLANNED' OR status = 'RUNNING' OR status = 'FAILED'.
      " a job that is over without its pile DONE (the pair, name and count), or
      " a pile RUNNING without a job: the pile is FAILED, with the reason
      CLEAR lv_reason.
      IF ls_pile-status = 'RUNNING' AND ls_pile-job_count IS INITIAL.
        lv_reason = 'NO-JOB'.
      ELSEIF ls_pile-status <> 'FAILED' AND ls_pile-job_count IS NOT INITIAL.
        CLEAR: lv_aborted, lv_finished, lv_running, lv_ready, lv_scheduled, lv_preliminary.
        CALL FUNCTION 'SHOW_JOBSTATE'
          EXPORTING
            jobname = ls_pile-job_name
            jobcount = ls_pile-job_count
          IMPORTING
            aborted = lv_aborted
            finished = lv_finished
            preliminary = lv_preliminary
            ready = lv_ready
            running = lv_running
            scheduled = lv_scheduled
          EXCEPTIONS
            OTHERS = 1.
        IF sy-subrc <> 0.
          lv_reason = 'JOB-GONE'.
        ELSEIF lv_finished = 'X' OR lv_aborted = 'X'.
          lv_reason = 'JOB-ENDED'.
        ENDIF.
      ENDIF.
      IF lv_reason IS NOT INITIAL.
        UPDATE zosd_l3_pile SET status = 'FAILED' reason = lv_reason ended = iv_now
          WHERE run_id = ls_pile-run_id
            AND rule_name = ls_pile-rule_name
            AND pile_no = ls_pile-pile_no
            AND status = ls_pile-status
            AND job_count = ls_pile-job_count.
        IF sy-dbcnt <> 1.
          CONTINUE.
        ENDIF.
        act( EXPORTING iv_run = iv_run
                       iv_date = iv_date
                       iv_stage = ls_pile-stage_no
                       iv_rule = ls_pile-rule_name
                       iv_pile = ls_pile-pile_no
                       iv_action = 'FAILED'
                       iv_reason = lv_reason
                       iv_now = iv_now
             CHANGING ct_report = ct_report ).
        ls_pile-status = 'FAILED'.
        ls_pile-ended = iv_now.
      ENDIF.
      " the retry budget: ATTEMPT counts the submits, c_retry_max the ones after the first
      IF ls_pile-attempt > c_retry_max.
        CONTINUE.
      ENDIF.
      IF ls_pile-status = 'FAILED'.
        IF due( is_pile = ls_pile iv_now = iv_now iv_force = iv_force ) = abap_false.
          CONTINUE.
        ENDIF.
        lv_reason = 'RETRY'.
      ELSEIF ls_pile-status = 'PLANNED' AND ls_pile-job_count IS INITIAL.
        " planned and never given a job, or sent back by the kill switch:
        " stale from the later of its own time and its gate's opening
        lv_since = ls_pile-ended.
        READ TABLE lt_gates INTO ls_gate WITH KEY stage_no = ls_pile-stage_no.
        IF sy-subrc = 0 AND ls_gate-opened > lv_since.
          lv_since = ls_gate-opened.
        ENDIF.
        IF iv_force = abap_false AND lv_since > lv_stale.
          CONTINUE.
        ENDIF.
        lv_reason = 'STALE-PLAN'.
      ELSE.
        CONTINUE.
      ENDIF.
      " the claim: PLANNED again with the next attempt, on the row as it was read
      lv_next = ls_pile-attempt + 1.
      UPDATE zosd_l3_pile SET status = 'PLANNED' attempt = lv_next reason = lv_reason
                              job_name = ' ' job_count = ' '
        WHERE run_id = ls_pile-run_id
          AND rule_name = ls_pile-rule_name
          AND pile_no = ls_pile-pile_no
          AND status = ls_pile-status
          AND attempt = ls_pile-attempt.
      IF sy-dbcnt <> 1.
        CONTINUE.
      ENDIF.
      ls_pile-status = 'PLANNED'.
      ls_pile-attempt = lv_next.
      ls_pile-reason = lv_reason.
      CLEAR: ls_pile-job_name, ls_pile-job_count.
      READ TABLE lt_rules INTO ls_rule WITH KEY rule = ls_pile-rule_name.
      submit( EXPORTING iv_date = iv_date
                        iv_run = iv_run
                        iv_bind = iv_bind
{{#with_params}}
                        is_params = is_params
{{/with_params}}
                        iv_jobname = ls_rule-jobname
              CHANGING cs_pile = ls_pile ).
      act( EXPORTING iv_run = iv_run
                     iv_date = iv_date
                     iv_stage = ls_pile-stage_no
                     iv_rule = ls_pile-rule_name
                     iv_pile = ls_pile-pile_no
                     iv_action = 'RESUBMIT'
                     iv_reason = lv_reason
                     iv_now = iv_now
           CHANGING ct_report = ct_report ).
    ENDLOOP.
    " the gates, against the plan as it is now
    SELECT * FROM zosd_l3_pile INTO TABLE lt_piles
      WHERE set_name = c_set
        AND run_id = iv_run
      ORDER BY PRIMARY KEY.
    LOOP AT lt_gates INTO ls_gate WHERE status = 'OPEN'.
      lv_count = 0.
      lv_open = 0.
      LOOP AT lt_piles INTO ls_pile WHERE stage_no = ls_gate-stage_no.
        lv_count = lv_count + 1.
        IF ls_pile-status <> 'DONE'.
          lv_open = lv_open + 1.
        ENDIF.
      ENDLOOP.
      IF lv_count = 0.
        " OPEN without a pile: the plan was lost between the gate and its
        " piles; planned again once stale, and only by the caller whose
        " UPDATE of the gate as it was read lands
        IF iv_force = abap_false AND ls_gate-opened > lv_stale.
          CONTINUE.
        ENDIF.
        UPDATE zosd_l3_stage SET opened = iv_now
          WHERE run_id = iv_run
            AND stage_no = ls_gate-stage_no
            AND status = 'OPEN'
            AND opened = ls_gate-opened.
        IF sy-dbcnt <> 1.
          CONTINUE.
        ENDIF.
        lt_new = plan( iv_run = iv_run
                       iv_date = iv_date
                       iv_stage = ls_gate-stage_no
                       iv_bind = iv_bind ).
        INSERT zosd_l3_pile FROM TABLE lt_new.
        act( EXPORTING iv_run = iv_run
                       iv_date = iv_date
                       iv_stage = ls_gate-stage_no
                       iv_action = 'REPLAN'
                       iv_reason = 'OPEN-NO-PILES'
                       iv_now = iv_now
             CHANGING ct_report = ct_report ).
        LOOP AT lt_new INTO ls_pile.
          READ TABLE lt_rules INTO ls_rule WITH KEY rule = ls_pile-rule_name.
          submit( EXPORTING iv_date = iv_date
                            iv_run = iv_run
                            iv_bind = iv_bind
{{#with_params}}
                            is_params = is_params
{{/with_params}}
                            iv_jobname = ls_rule-jobname
                  CHANGING cs_pile = ls_pile ).
        ENDLOOP.
        IF lt_new IS INITIAL.
          " no key: the stage is complete as it is
          advance( iv_run = iv_run
                   iv_date = iv_date
                   iv_stage = ls_gate-stage_no
{{#with_params}}
                   is_params = is_params
{{/with_params}}
                   iv_bind = iv_bind ).
        ENDIF.
      ELSEIF lv_open = 0.
        " every pile DONE and the gate still OPEN: the job that ended the
        " stage did not get to advance( )
{{#killable}}
        " not while the kill switch is set: advance( ) would open nothing, and
        " the stage would be DONE with the next gate shut
        IF killed( ) = abap_true.
          CONTINUE.
        ENDIF.
{{/killable}}
        UPDATE zosd_l3_stage SET status = 'DONE' ended = iv_now
          WHERE run_id = iv_run
            AND stage_no = ls_gate-stage_no
            AND status = 'OPEN'.
        IF sy-dbcnt <> 1.
          CONTINUE.
        ENDIF.
        act( EXPORTING iv_run = iv_run
                       iv_date = iv_date
                       iv_stage = ls_gate-stage_no
                       iv_action = 'ADVANCE'
                       iv_reason = 'STAGE-DONE'
                       iv_now = iv_now
             CHANGING ct_report = ct_report ).
        advance( iv_run = iv_run
                 iv_date = iv_date
                 iv_stage = ls_gate-stage_no
{{#with_params}}
                 is_params = is_params
{{/with_params}}
                 iv_bind = iv_bind ).
      ENDIF.
    ENDLOOP.
    " a stage DONE whose next gate is still WAITING: its advance( ) was
    " stopped between the two (the kill switch set in between); the next
    " gate opens through advance( ), whose WAITING to OPEN is the one UPDATE
    LOOP AT lt_gates INTO ls_gate WHERE status = 'WAITING' AND stage_no > 1.
      lv_prev = ls_gate-stage_no - 1.
      READ TABLE lt_gates INTO ls_prev WITH KEY stage_no = lv_prev.
      IF sy-subrc <> 0 OR ls_prev-status <> 'DONE'.
        CONTINUE.
      ENDIF.
      IF advance( iv_run = iv_run
                  iv_date = iv_date
                  iv_stage = lv_prev
{{#with_params}}
                  is_params = is_params
{{/with_params}}
                  iv_bind = iv_bind ) = abap_true.
        act( EXPORTING iv_run = iv_run
                       iv_date = iv_date
                       iv_stage = lv_prev
                       iv_action = 'ADVANCE'
                       iv_reason = 'NEXT-WAITING'
                       iv_now = iv_now
             CHANGING ct_report = ct_report ).
      ENDIF.
    ENDLOOP.
  ENDMETHOD.

  METHOD due.
    " c_backoff seconds after the pile failed, doubled per attempt it has had
    " (1, 2, 4 ... times, at most a week); iv_force: at once
    DATA lv_wait TYPE i.
    DATA lv_times TYPE i.
    IF iv_force = abap_true.
      rv_due = abap_true.
      RETURN.
    ENDIF.
    lv_wait = c_backoff.
    lv_times = is_pile-attempt - 1.
    DO lv_times TIMES.
      IF lv_wait > 302400.
        lv_wait = 604800.
        EXIT.
      ENDIF.
      lv_wait = lv_wait * 2.
    ENDDO.
    IF is_pile-ended <= ago( iv_now = iv_now iv_secs = lv_wait ).
      rv_due = abap_true.
    ENDIF.
  ENDMETHOD.

  METHOD purge.
    " the plan, worklist, gate and doctor rows of every final run of the set
    " last touched (its gates' latest OPENED or ENDED) more than c_keep_days
    " ago, old doctor rows, and released locks older than that. A run is
    " open while its lock names it HELD, and nothing of an open run goes. The
    " alert log is history and is never purged
    DATA lv_now TYPE timestamp.
    DATA lv_cut TYPE timestamp.
    DATA lv_secs TYPE i.
    DATA lt_gates TYPE STANDARD TABLE OF zosd_l3_stage WITH DEFAULT KEY.
    DATA ls_gate TYPE zosd_l3_stage.
    DATA lt_runs TYPE STANDARD TABLE OF zosd_l3_stage WITH DEFAULT KEY.
    DATA ls_run TYPE zosd_l3_stage.
    DATA ls_lock TYPE zosd_l3_run.
    DATA lt_audit TYPE STANDARD TABLE OF zosd_l3_doctor WITH DEFAULT KEY.
    DATA ls_audit TYPE zosd_l3_doctor.
    lv_now = iv_now.
    IF lv_now IS INITIAL.
      GET TIME STAMP FIELD lv_now.
    ENDIF.
    lv_secs = c_keep_days * 86400.
    lv_cut = ago( iv_now = lv_now iv_secs = lv_secs ).
    SELECT * FROM zosd_l3_stage INTO TABLE lt_gates
      WHERE set_name = c_set
      ORDER BY PRIMARY KEY.
    LOOP AT lt_gates INTO ls_gate.
      IF ls_gate-ended > ls_gate-opened.
        ls_gate-opened = ls_gate-ended.
      ENDIF.
      READ TABLE lt_runs INTO ls_run WITH KEY run_id = ls_gate-run_id.
      IF sy-subrc <> 0.
        APPEND ls_gate TO lt_runs.
      ELSEIF ls_gate-opened > ls_run-opened.
        ls_run-opened = ls_gate-opened.
        MODIFY lt_runs FROM ls_run INDEX sy-tabix.
      ENDIF.
    ENDLOOP.
    LOOP AT lt_runs INTO ls_run.
      IF ls_run-opened > lv_cut.
        CONTINUE.
      ENDIF.
      CLEAR ls_lock.
      SELECT SINGLE * FROM zosd_l3_run INTO ls_lock
        WHERE set_name = c_set
          AND check_date = ls_run-check_date.
      IF ls_lock-run_id = ls_run-run_id AND ls_lock-status = 'HELD'.
        CONTINUE.
      ENDIF.
      DELETE FROM zosd_l3_pile WHERE set_name = c_set AND run_id = ls_run-run_id.
      DELETE FROM zosd_l3_work WHERE run_id = ls_run-run_id.
      DELETE FROM zosd_l3_doctor WHERE run_id = ls_run-run_id.
      DELETE FROM zosd_l3_stage WHERE run_id = ls_run-run_id.
      act( EXPORTING iv_run = ls_run-run_id
                     iv_date = ls_run-check_date
                     iv_action = 'PURGE'
                     iv_reason = 'a final run past c_keep_days'
                     iv_audit = abap_false
           CHANGING ct_report = rt_report ).
    ENDLOOP.
    " doctor rows older than the cut of a run that is not open, such as one
    " whose lock was released for having no plan
    SELECT * FROM zosd_l3_doctor INTO TABLE lt_audit
      WHERE set_name = c_set
        AND acted <= lv_cut
      ORDER BY PRIMARY KEY.
    LOOP AT lt_audit INTO ls_audit.
      CLEAR ls_lock.
      SELECT SINGLE * FROM zosd_l3_run INTO ls_lock
        WHERE set_name = c_set
          AND check_date = ls_audit-check_date.
      IF ls_lock-run_id = ls_audit-run_id AND ls_lock-status = 'HELD'.
        CONTINUE.
      ENDIF.
      DELETE FROM zosd_l3_doctor WHERE run_id = ls_audit-run_id AND seq = ls_audit-seq.
    ENDLOOP.
    " the lock rows of dates whose last run let go before the cut
    DELETE FROM zosd_l3_run
      WHERE set_name = c_set
        AND status = 'RELEASED'
        AND started <= lv_cut.
    IF sy-dbcnt > 0.
      act( EXPORTING iv_run = ''
                     iv_action = 'PURGE'
                     iv_reason = 'released locks past c_keep_days'
                     iv_audit = abap_false
           CHANGING ct_report = rt_report ).
    ENDIF.
  ENDMETHOD.

  METHOD ago.
    " iv_secs seconds before iv_now; initial (older than any row) when the
    " time stamp cannot be computed, so nothing is taken for stale
    TRY.
        rv_stamp = cl_abap_tstmp=>subtractsecs( tstmp = iv_now secs = iv_secs ).
      CATCH cx_root.
        CLEAR rv_stamp.
    ENDTRY.
  ENDMETHOD.

  METHOD act.
    " the report row; the audit row of ZOSD_L3_DOCTOR takes the run's next
    " SEQ, and a clash with a row another doctor inserted takes the one after
    DATA ls_row TYPE ty_doctor.
    DATA ls_audit TYPE zosd_l3_doctor.
    DATA lt_seq TYPE STANDARD TABLE OF zosd_l3_doctor-seq WITH DEFAULT KEY.
    DATA lv_seq TYPE zosd_l3_doctor-seq.
    ls_row-run_id = iv_run.
    ls_row-check_date = iv_date.
    ls_row-stage_no = iv_stage.
    ls_row-rule_name = iv_rule.
    ls_row-pile_no = iv_pile.
    ls_row-doc_action = iv_action.
    ls_row-reason = iv_reason.
    APPEND ls_row TO ct_report.
    IF iv_audit = abap_false.
      RETURN.
    ENDIF.
    MOVE-CORRESPONDING ls_row TO ls_audit.
    ls_audit-set_name = c_set.
    ls_audit-acted = iv_now.
    SELECT seq FROM zosd_l3_doctor INTO TABLE lt_seq
      WHERE run_id = iv_run.
    LOOP AT lt_seq INTO lv_seq.
      IF lv_seq > ls_audit-seq.
        ls_audit-seq = lv_seq.
      ENDIF.
    ENDLOOP.
    DO 10 TIMES.
      ls_audit-seq = ls_audit-seq + 1.
      INSERT zosd_l3_doctor FROM ls_audit.
      IF sy-subrc = 0.
        RETURN.
      ENDIF.
    ENDDO.
  ENDMETHOD.
{{#killable}}

  METHOD killed.
    DATA lv_set TYPE {{table}}-set_name.
    SELECT SINGLE set_name FROM {{table}} INTO lv_set
      WHERE set_name = c_set.
    IF sy-subrc = 0.
      rv_killed = abap_true.
    ENDIF.
  ENDMETHOD.
{{/killable}}
{{#scheduled}}

  METHOD schedule_doctor.
    " the doctor as a periodic job of its own, {{report}} with p_mode = 'H',
    " every {{stale.job.word}} from now (system time); nothing when an
    " instance of it already waits
    DATA ls_select TYPE btcselect.
    DATA lt_jobs TYPE STANDARD TABLE OF tbtcjob WITH DEFAULT KEY.
    DATA ls_job TYPE tbtcjob.
    DATA lv_jobname TYPE tbtcjob-jobname.
    DATA lv_jobcount TYPE tbtcjob-jobcount.
    DATA lv_period TYPE tbtcjob-{{stale.job.field}}.
    DATA lv_released TYPE btch0000-char1.
    DATA lv_date TYPE d.
    DATA lv_time TYPE t.
    ls_select-jobname = c_doctor.
    ls_select-username = sy-uname.
    ls_select-schedul = 'X'.
    CALL FUNCTION 'BP_JOB_SELECT'
      EXPORTING
        jobselect_dialog = 'N'
        jobsel_param_in = ls_select
      TABLES
        jobselect_joblist = lt_jobs
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc = 0.
      LOOP AT lt_jobs INTO ls_job WHERE status = 'S'.
        RETURN.
      ENDLOOP.
    ENDIF.
    lv_jobname = c_doctor.
    lv_period = {{stale.job.count}}.
    GET TIME.
    lv_date = sy-datum.
    lv_time = sy-uzeit.
    CALL FUNCTION 'JOB_OPEN'
      EXPORTING
        jobname = lv_jobname
      IMPORTING
        jobcount = lv_jobcount
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      RETURN.
    ENDIF.
    SUBMIT {{report}}
      WITH p_mode = 'H'
      VIA JOB lv_jobname NUMBER lv_jobcount
      AND RETURN.
    CALL FUNCTION 'JOB_CLOSE'
      EXPORTING
        jobname = lv_jobname
        jobcount = lv_jobcount
        sdlstrtdt = lv_date
        sdlstrttm = lv_time
        {{stale.job.field}} = lv_period
      IMPORTING
        job_was_released = lv_released
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0 OR lv_released <> 'X'.
      CALL FUNCTION 'BP_JOB_DELETE'
        EXPORTING
          jobname = lv_jobname
          jobcount = lv_jobcount
        EXCEPTIONS
          OTHERS = 1.
    ENDIF.
  ENDMETHOD.

  METHOD unschedule_doctor.
    " the doctor's instance waiting for its start ends its chain, as the driver's
    DATA ls_select TYPE btcselect.
    DATA lt_jobs TYPE STANDARD TABLE OF tbtcjob WITH DEFAULT KEY.
    DATA ls_job TYPE tbtcjob.
    ls_select-jobname = c_doctor.
    ls_select-username = sy-uname.
    ls_select-schedul = 'X'.
    CALL FUNCTION 'BP_JOB_SELECT'
      EXPORTING
        jobselect_dialog = 'N'
        jobsel_param_in = ls_select
      TABLES
        jobselect_joblist = lt_jobs
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      RETURN.
    ENDIF.
    LOOP AT lt_jobs INTO ls_job WHERE status = 'S'.
      CALL FUNCTION 'BP_JOB_DELETE'
        EXPORTING
          jobname = ls_job-jobname
          jobcount = ls_job-jobcount
        EXCEPTIONS
          OTHERS = 1.
      IF sy-subrc = 0.
        rv_deleted = rv_deleted + 1.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.
{{/scheduled}}
{{/resilience}}
ENDCLASS.
