* Generated by tools/dsl-l2.mjs from {{source}}; do not edit.
* The examples of rule {{rule}} and the cases derived from its conditions, one test method each.
* Every method runs check and check_reference (the obvious nested form, one
* SELECT per row) and asserts that they answer alike, then that check answers
* what the rule's interpreter expects.
* RISK LEVEL DANGEROUS: a method inserts its example's rows into the rule's
* own tables and its teardown deletes them again by key.
CLASS ltcl_examples DEFINITION FOR TESTING RISK LEVEL DANGEROUS DURATION SHORT FINAL.
  PRIVATE SECTION.
{{#tables}}
    DATA {{itab}} TYPE STANDARD TABLE OF {{table}} WITH DEFAULT KEY.
{{/tables}}
    METHODS teardown.
    METHODS check_reference
      IMPORTING iv_date TYPE d
      RETURNING VALUE(rt_alerts) TYPE string_table.
    METHODS assert_alerts
      IMPORTING it_act TYPE string_table it_exp TYPE string_table iv_example TYPE string.
    METHODS assert_same_as_reference
      IMPORTING it_act TYPE string_table it_ref TYPE string_table iv_example TYPE string.
{{#tests}}
    METHODS {{method}} FOR TESTING.
{{/tests}}
ENDCLASS.

CLASS ltcl_examples IMPLEMENTATION.

  METHOD teardown.
{{#tables}}
    DELETE {{table}} FROM TABLE {{itab}}.
    CLEAR {{itab}}.
{{/tables}}
  ENDMETHOD.

  METHOD check_reference.
    " the rule as a person would write it: a SELECT on the exists table for
    " every row of the first
    DATA {{for.itab}} TYPE STANDARD TABLE OF {{for.table}} WITH DEFAULT KEY.
    DATA {{for.wa}} TYPE {{for.table}}.
    DATA {{forbid.itab}} TYPE STANDARD TABLE OF {{forbid.table}} WITH DEFAULT KEY.
    DATA {{forbid.wa}} TYPE {{forbid.table}}.
    DATA lv_alert TYPE string.
    SELECT * FROM {{for.table}} INTO TABLE {{for.itab}}
{{#when.conditions}}
      {{#@first}}WHERE{{/@first}}{{^@first}}  AND{{/@first}} {{column}} {{op}} {{#is_literal}}{{value | literal}}{{/is_literal}}{{^is_literal}}{{ref}}{{/is_literal}}
{{/when.conditions}}
      ORDER BY PRIMARY KEY.
    LOOP AT {{for.itab}} INTO {{for.wa}}.
      SELECT * FROM {{forbid.table}} INTO TABLE {{forbid.itab}}
{{#forbid.conditions}}
        {{#@first}}WHERE{{/@first}}{{^@first}}  AND{{/@first}} {{column}} {{op}} {{#is_literal}}{{value | literal}}{{/is_literal}}{{^is_literal}}{{ref}}{{/is_literal}}
{{/forbid.conditions}}
        ORDER BY PRIMARY KEY.
      LOOP AT {{forbid.itab}} INTO {{forbid.wa}}.
{{#alert.parts}}
        {{#@first}}lv_alert = {{/@first}}{{^@first}}  && {{/@first}}{{#is_text}}{{value | literal}}{{/is_text}}{{^is_text}}{{ref}}{{/is_text}}{{#@last}}.{{/@last}}
{{/alert.parts}}
        APPEND lv_alert TO rt_alerts.
      ENDLOOP.
    ENDLOOP.
  ENDMETHOD.

  METHOD assert_alerts.
    " order-insensitive: the rule says which alerts, not in which order
    DATA lt_act TYPE string_table.
    DATA lt_exp TYPE string_table.
    lt_act = it_act.
    lt_exp = it_exp.
    SORT lt_act.
    SORT lt_exp.
    cl_abap_unit_assert=>assert_equals( act = lt_act exp = lt_exp msg = iv_example ).
  ENDMETHOD.

  METHOD assert_same_as_reference.
    " the query and the nested form answer alike, in the same order
    cl_abap_unit_assert=>assert_equals( act = it_act exp = it_ref msg = iv_example ).
  ENDMETHOD.
{{#tests}}

  METHOD {{method}}.
{{#tables}}
    DATA {{wa}} TYPE {{table}}.
{{/tables}}
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
{{#tables}}
{{#rows}}
    CLEAR {{wa}}.
{{#client}}
    {{wa}}-{{client}} = sy-mandt.
{{/client}}
{{#fields}}
    {{wa}}-{{column}} = {{value | literal}}.
{{/fields}}
    APPEND {{wa}} TO {{itab}}.
{{/rows}}
    INSERT {{table}} FROM TABLE {{itab}}.
{{/tables}}
{{#expect}}
    APPEND {{value | literal}} TO lt_exp.
{{/expect}}
    lt_act = {{date.call}}( iv_date = {{date.value | literal}} ).
    lt_ref = check_reference( iv_date = {{date.value | literal}} ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = {{ref_label | literal}} ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = {{label | literal}} ).
  ENDMETHOD.
{{/tests}}
ENDCLASS.
