* Generated by tools/dsl-l3.mjs from src/l2demo/fleet2.l3.yaml; do not edit.
* Port close of set fleet2, variant none.
CLASS zcl_l3_fleet2_close_none DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES zif_l3_fleet2_close.
ENDCLASS.
CLASS zcl_l3_fleet2_close_none IMPLEMENTATION.
  METHOD zif_l3_fleet2_close~apply.
  ENDMETHOD.
ENDCLASS.
