* Generated by tools/dsl-l3.mjs from src/l2demo/fleet.l3.yaml; do not edit.
* Set fleet: Every fleet rule, checked for one date
CLASS zcl_l3_fleet DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    TYPES: BEGIN OF ty_rule,
             rule TYPE zosd_l3_alert-rule_name,
             model_hash TYPE zosd_l3_alert-model_hash,
             jobname TYPE tbtcjob-jobname,
             jobcount TYPE tbtcjob-jobcount,
             status TYPE c LENGTH 12,
             alerts TYPE i,
             failed TYPE i,
           END OF ty_rule.
    TYPES tt_rule TYPE STANDARD TABLE OF ty_rule WITH DEFAULT KEY.
    TYPES: BEGIN OF ty_result,
             set_name TYPE zosd_l3_alert-set_name,
             run_id TYPE zosd_l3_alert-run_id,
             check_date TYPE d,
             mode TYPE c LENGTH 1,
             alerts TYPE i,
             rules TYPE tt_rule,
           END OF ty_result.
    CONSTANTS c_set TYPE zosd_l3_alert-set_name VALUE 'fleet'.
    CONSTANTS c_sequential TYPE c LENGTH 1 VALUE 'S'.
    CONSTANTS c_parallel TYPE c LENGTH 1 VALUE 'P'.
    CONSTANTS c_rule_1 TYPE zosd_l3_alert-rule_name VALUE 'maintenance-ship-no-future-voyage'.
    CONSTANTS c_hash_1 TYPE zosd_l3_alert-model_hash VALUE 'sha256:5b94ace0a8ae6ea8dd37f2fa41f62ff23aa83e6533a88f0301c495753e7652a1'.
    CONSTANTS c_rule_2 TYPE zosd_l3_alert-rule_name VALUE 'grounded-ship-keeps-only-keepers'.
    CONSTANTS c_hash_2 TYPE zosd_l3_alert-model_hash VALUE 'sha256:2b72e97ce478f2a42dfc8e105f67dead7260925b87f6634c0f92f8bc4fd33f2f'.
    CONSTANTS c_rule_3 TYPE zosd_l3_alert-rule_name VALUE 'ship-in-service-has-a-captain'.
    CONSTANTS c_hash_3 TYPE zosd_l3_alert-model_hash VALUE 'sha256:9fe75f5ad8fa0127298f0c96195200b12eabaea019b569d569fde6276b153a29'.
    CONSTANTS c_rule_4 TYPE zosd_l3_alert-rule_name VALUE 'ship-too-many-future-voyages'.
    CONSTANTS c_hash_4 TYPE zosd_l3_alert-model_hash VALUE 'sha256:817b24b38d55d3f382151282408eb931b80b70dc7ec29a2bfbf92fe7d8827f7f'.
    CONSTANTS c_rule_5 TYPE zosd_l3_alert-rule_name VALUE 'ship-min-crew'.
    CONSTANTS c_hash_5 TYPE zosd_l3_alert-model_hash VALUE 'sha256:7e156d101af7385078bddbeb4aec645f470ffa22ec9e156a36d5d1fa07741013'.
    CONSTANTS c_rule_6 TYPE zosd_l3_alert-rule_name VALUE 'ship-cargo-limit'.
    CONSTANTS c_hash_6 TYPE zosd_l3_alert-model_hash VALUE 'sha256:6dc361bcc17b388fe102c33fead3d7dd38d6b4993437e78ec508424e0e0f50a5'.
    " not run: ship-max-cargo (src/l2demo/ship_max_cargo.l2.yaml), enabled: false in the set
    " iv_bind: the variant of each port for this run, "port=variant,port=variant";
    " a port it does not name keeps the manifest's binding. A source that is not
    " live replaces table content in the caller's LUW: a test and dev seam, never
    " production, and refused unless iv_allow_replay says so.
    CLASS-METHODS run
      IMPORTING iv_date TYPE d
                iv_mode TYPE c DEFAULT 'S'
                iv_bind TYPE string OPTIONAL
                iv_allow_replay TYPE abap_bool DEFAULT abap_false
      RETURNING VALUE(rs_result) TYPE ty_result.
    CLASS-METHODS run_rule
      IMPORTING iv_rule TYPE csequence
                iv_date TYPE d
                iv_run TYPE csequence
                iv_bind TYPE string OPTIONAL
      RETURNING VALUE(rs_rule) TYPE ty_rule.
    CLASS-METHODS collect
      IMPORTING is_result TYPE ty_result
      RETURNING VALUE(rs_result) TYPE ty_result.
    CLASS-METHODS rules
      RETURNING VALUE(rt_rules) TYPE tt_rule.
  PRIVATE SECTION.
    CLASS-METHODS write
      IMPORTING iv_date TYPE d
                iv_run TYPE csequence
                iv_class TYPE csequence
                iv_file TYPE csequence
                iv_line TYPE i
                it_alerts TYPE string_table
                iv_bind TYPE string OPTIONAL
      CHANGING cs_rule TYPE ty_rule.
    " puts the rows of zosd_l2_ship back after a replay: the rows kept before it
    CLASS-METHODS restore_1
      IMPORTING it_keep TYPE zif_l3_fleet_ships=>tt_rows.
    CLASS-METHODS submit
      IMPORTING iv_date TYPE d
                iv_run TYPE csequence
                iv_bind TYPE string OPTIONAL
      CHANGING cs_rule TYPE ty_rule.
ENDCLASS.

CLASS zcl_l3_fleet IMPLEMENTATION.
  METHOD run.
    " mode S runs every rule in this step; mode P submits one job per rule,
    " and collect( ) reads their states once they have run
    DATA lt_rules TYPE tt_rule.
    DATA ls_rule TYPE ty_rule.
    DATA lv_stamp TYPE timestampl.
    DATA lv_parallel TYPE abap_bool.
    DATA lx_error TYPE REF TO cx_root.
    DATA li_src_1 TYPE REF TO zif_l3_fleet_ships.
    DATA lv_swap_1 TYPE abap_bool.
    DATA lt_keep_1 TYPE zif_l3_fleet_ships=>tt_rows.
    DATA lt_scope_1 TYPE zif_l3_fleet_ships=>tt_rows.
    FIELD-SYMBOLS <ls_row_1> TYPE zosd_l2_ship.
    IF iv_mode = c_parallel.
      lv_parallel = abap_true.
    ENDIF.
    zcl_l3_fleet_ports=>check( iv_bind = iv_bind
                          iv_parallel = lv_parallel
                          iv_allow_replay = iv_allow_replay ).
    rs_result-set_name = c_set.
    rs_result-mode = iv_mode.
    rs_result-check_date = iv_date.
    TRY.
        rs_result-run_id = cl_system_uuid=>create_uuid_c32_static( ).
      CATCH cx_uuid_error.
        GET TIME STAMP FIELD lv_stamp.
        rs_result-run_id = lv_stamp.
    ENDTRY.
    lt_rules = rules( ).
    " a source that is not live replaces table content for this run, and the
    " table is put back whatever happens: after the loop, or when an exception
    " leaves this method (CATCH and RAISE, which does what CLEANUP would; the
    " transpiler drops CLEANUP, ANORMALIES.md). Nothing in here commits.
    TRY.
        " zosd_l2_ship: the table's own rows are kept, the source's rows stand
        " in their place, and the rules read them as they read the table
        IF zcl_l3_fleet_ports=>swaps( iv_port = 'ships' iv_bind = iv_bind ) = abap_true.
          li_src_1 = zcl_l3_fleet_ports=>get_ships( zcl_l3_fleet_ports=>variant( iv_port = 'ships' iv_bind = iv_bind ) ).
          SELECT * FROM zosd_l2_ship INTO TABLE lt_keep_1.
          lt_scope_1 = li_src_1->read( ).
          LOOP AT lt_scope_1 ASSIGNING <ls_row_1>.
            <ls_row_1>-mandt = sy-mandt.
          ENDLOOP.
          lv_swap_1 = abap_true.
          DELETE FROM zosd_l2_ship.
          INSERT zosd_l2_ship FROM TABLE lt_scope_1.
        ENDIF.
        LOOP AT lt_rules INTO ls_rule.
          IF iv_mode = c_parallel.
            submit( EXPORTING iv_date = rs_result-check_date
                              iv_run = rs_result-run_id
                              iv_bind = iv_bind
                    CHANGING cs_rule = ls_rule ).
          ELSE.
            ls_rule = run_rule( iv_rule = ls_rule-rule
                                iv_date = rs_result-check_date
                                iv_run = rs_result-run_id
                                iv_bind = iv_bind ).
            rs_result-alerts = rs_result-alerts + ls_rule-alerts.
          ENDIF.
          APPEND ls_rule TO rs_result-rules.
        ENDLOOP.
      CATCH cx_root INTO lx_error.
        IF lv_swap_1 = abap_true.
          restore_1( lt_keep_1 ).
        ENDIF.
        RAISE EXCEPTION lx_error.
    ENDTRY.
    IF lv_swap_1 = abap_true.
      restore_1( lt_keep_1 ).
    ENDIF.
  ENDMETHOD.

  METHOD restore_1.
    DELETE FROM zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE it_keep.
  ENDMETHOD.

  METHOD rules.
    DATA ls_rule TYPE ty_rule.
    ls_rule-rule = c_rule_1.
    ls_rule-model_hash = c_hash_1.
    ls_rule-jobname = 'L3_FLEET_01'.
    APPEND ls_rule TO rt_rules.
    ls_rule-rule = c_rule_2.
    ls_rule-model_hash = c_hash_2.
    ls_rule-jobname = 'L3_FLEET_02'.
    APPEND ls_rule TO rt_rules.
    ls_rule-rule = c_rule_3.
    ls_rule-model_hash = c_hash_3.
    ls_rule-jobname = 'L3_FLEET_03'.
    APPEND ls_rule TO rt_rules.
    ls_rule-rule = c_rule_4.
    ls_rule-model_hash = c_hash_4.
    ls_rule-jobname = 'L3_FLEET_04'.
    APPEND ls_rule TO rt_rules.
    ls_rule-rule = c_rule_5.
    ls_rule-model_hash = c_hash_5.
    ls_rule-jobname = 'L3_FLEET_05'.
    APPEND ls_rule TO rt_rules.
    ls_rule-rule = c_rule_6.
    ls_rule-model_hash = c_hash_6.
    ls_rule-jobname = 'L3_FLEET_06'.
    APPEND ls_rule TO rt_rules.
  ENDMETHOD.

  METHOD run_rule.
    DATA lt_alerts TYPE string_table.
    rs_rule-rule = iv_rule.
    CASE iv_rule.
      WHEN c_rule_1.
        rs_rule-model_hash = c_hash_1.
        rs_rule-jobname = 'L3_FLEET_01'.
        lt_alerts = zcl_l2_maintenance_ship=>check( iv_date ).
        write( EXPORTING iv_date = iv_date
                         iv_run = iv_run
                         iv_class = 'zcl_l2_maintenance_ship'
                         iv_file = 'src/l2demo/maintenance_ship.l2.yaml'
                         iv_line = 12
                         it_alerts = lt_alerts
                         iv_bind = iv_bind
               CHANGING cs_rule = rs_rule ).
      WHEN c_rule_2.
        rs_rule-model_hash = c_hash_2.
        rs_rule-jobname = 'L3_FLEET_02'.
        lt_alerts = zcl_l2_grounded_ship_crew=>check( iv_date ).
        write( EXPORTING iv_date = iv_date
                         iv_run = iv_run
                         iv_class = 'zcl_l2_grounded_ship_crew'
                         iv_file = 'src/l2demo/grounded_ship_crew.l2.yaml'
                         iv_line = 13
                         it_alerts = lt_alerts
                         iv_bind = iv_bind
               CHANGING cs_rule = rs_rule ).
      WHEN c_rule_3.
        rs_rule-model_hash = c_hash_3.
        rs_rule-jobname = 'L3_FLEET_03'.
        lt_alerts = zcl_l2_ship_captain=>check( iv_date ).
        write( EXPORTING iv_date = iv_date
                         iv_run = iv_run
                         iv_class = 'zcl_l2_ship_captain'
                         iv_file = 'src/l2demo/ship_captain.l2.yaml'
                         iv_line = 12
                         it_alerts = lt_alerts
                         iv_bind = iv_bind
               CHANGING cs_rule = rs_rule ).
      WHEN c_rule_4.
        rs_rule-model_hash = c_hash_4.
        rs_rule-jobname = 'L3_FLEET_04'.
        lt_alerts = zcl_l2_ship_voyage_limit=>check( iv_date ).
        write( EXPORTING iv_date = iv_date
                         iv_run = iv_run
                         iv_class = 'zcl_l2_ship_voyage_limit'
                         iv_file = 'src/l2demo/ship_voyage_limit.l2.yaml'
                         iv_line = 10
                         it_alerts = lt_alerts
                         iv_bind = iv_bind
               CHANGING cs_rule = rs_rule ).
      WHEN c_rule_5.
        rs_rule-model_hash = c_hash_5.
        rs_rule-jobname = 'L3_FLEET_05'.
        lt_alerts = zcl_l2_ship_min_crew=>check( iv_date ).
        write( EXPORTING iv_date = iv_date
                         iv_run = iv_run
                         iv_class = 'zcl_l2_ship_min_crew'
                         iv_file = 'src/l2demo/ship_min_crew.l2.yaml'
                         iv_line = 10
                         it_alerts = lt_alerts
                         iv_bind = iv_bind
               CHANGING cs_rule = rs_rule ).
      WHEN c_rule_6.
        rs_rule-model_hash = c_hash_6.
        rs_rule-jobname = 'L3_FLEET_06'.
        lt_alerts = zcl_l2_ship_cargo_limit=>check( iv_date ).
        write( EXPORTING iv_date = iv_date
                         iv_run = iv_run
                         iv_class = 'zcl_l2_ship_cargo_limit'
                         iv_file = 'src/l2demo/ship_cargo_limit.l2.yaml'
                         iv_line = 9
                         it_alerts = lt_alerts
                         iv_bind = iv_bind
               CHANGING cs_rule = rs_rule ).
      WHEN OTHERS.
        rs_rule-status = 'UNKNOWN'.
    ENDCASE.
  ENDMETHOD.

  METHOD write.
    " the rows of one rule version and date go through the alert sink the run
    " is bound to (alerts); the log variant is idempotent per (set,
    " rule, model hash, check date), see its class
    DATA ls_row TYPE zosd_l3_alert.
    DATA lt_rows TYPE zif_l3_fleet_alerts=>tt_rows.
    DATA ls_group TYPE zif_l3_fleet_alerts=>ty_group.
    DATA li_sink TYPE REF TO zif_l3_fleet_alerts.
    DATA lv_alert TYPE string.
    DATA lv_count TYPE i.
    ls_row-set_name = c_set.
    ls_row-rule_name = cs_rule-rule.
    ls_row-model_hash = cs_rule-model_hash.
    ls_row-check_date = iv_date.
    ls_row-run_id = iv_run.
    ls_row-rule_class = iv_class.
    ls_row-rule_file = iv_file.
    ls_row-rule_line = iv_line.
    GET TIME STAMP FIELD ls_row-run_ts.
    LOOP AT it_alerts INTO lv_alert.
      ls_row-alert_seq = sy-tabix.
      ls_row-alert_text = lv_alert.
      APPEND ls_row TO lt_rows.
    ENDLOOP.
    ls_group-set_name = c_set.
    ls_group-rule_name = cs_rule-rule.
    ls_group-model_hash = cs_rule-model_hash.
    ls_group-check_date = iv_date.
    li_sink = zcl_l3_fleet_ports=>get_alerts( zcl_l3_fleet_ports=>variant( iv_port = 'alerts' iv_bind = iv_bind ) ).
    lv_count = li_sink->put( it_rows = lt_rows
                             is_group = ls_group ).
    cs_rule-alerts = lines( lt_rows ).
    cs_rule-failed = cs_rule-alerts - lv_count.
    IF cs_rule-failed = 0.
      cs_rule-status = 'DONE'.
    ELSE.
      cs_rule-status = 'WRITE-FAILED'.
    ENDIF.
  ENDMETHOD.

  METHOD submit.
    " one job per rule: JOB_OPEN, SUBMIT ... VIA JOB, JOB_CLOSE started at
    " once; the rules do not depend on each other, so no job waits for one
    DATA lv_jobname TYPE tbtcjob-jobname.
    DATA lv_jobcount TYPE tbtcjob-jobcount.
    DATA lv_released TYPE btch0000-char1.
    lv_jobname = cs_rule-jobname.
    CALL FUNCTION 'JOB_OPEN'
      EXPORTING
        jobname = lv_jobname
      IMPORTING
        jobcount = lv_jobcount
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      cs_rule-status = 'OPEN-FAILED'.
      RETURN.
    ENDIF.
    cs_rule-jobcount = lv_jobcount.
    SUBMIT zl3_fleet
      WITH p_rule = cs_rule-rule
      WITH p_date = iv_date
      WITH p_run = iv_run
      WITH p_bind = iv_bind
      VIA JOB lv_jobname NUMBER lv_jobcount
      AND RETURN.
    CALL FUNCTION 'JOB_CLOSE'
      EXPORTING
        jobname = lv_jobname
        jobcount = lv_jobcount
        strtimmed = 'X'
      IMPORTING
        job_was_released = lv_released
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0 OR lv_released <> 'X'.
      cs_rule-status = 'CLOSE-FAILED'.
      RETURN.
    ENDIF.
    cs_rule-status = 'SUBMITTED'.
  ENDMETHOD.

  METHOD collect.
    " the jobs of the run, found by BP_JOB_SELECT, each read by SHOW_JOBSTATE;
    " a finished rule counts the rows its job wrote under this run
    DATA ls_select TYPE btcselect.
    DATA lt_jobs TYPE STANDARD TABLE OF tbtcjob WITH DEFAULT KEY.
    DATA ls_rule TYPE ty_rule.
    DATA lv_aborted TYPE btch0000-char1.
    DATA lv_finished TYPE btch0000-char1.
    DATA lv_running TYPE btch0000-char1.
    DATA lv_ready TYPE btch0000-char1.
    DATA lv_scheduled TYPE btch0000-char1.
    DATA lv_preliminary TYPE btch0000-char1.
    rs_result = is_result.
    CLEAR: rs_result-rules, rs_result-alerts.
    ls_select-jobname = 'L3_FLEET_*'.
    ls_select-username = sy-uname.
    CALL FUNCTION 'BP_JOB_SELECT'
      EXPORTING
        jobselect_dialog = 'N'
        jobsel_param_in = ls_select
      TABLES
        jobselect_joblist = lt_jobs
      EXCEPTIONS
        OTHERS = 1.
    IF sy-subrc <> 0.
      CLEAR lt_jobs.
    ENDIF.
    LOOP AT is_result-rules INTO ls_rule.
      IF ls_rule-jobcount IS NOT INITIAL.
        READ TABLE lt_jobs TRANSPORTING NO FIELDS
          WITH KEY jobname = ls_rule-jobname jobcount = ls_rule-jobcount.
        IF sy-subrc <> 0.
          ls_rule-status = 'NO-JOB'.
        ELSE.
          CLEAR: lv_aborted, lv_finished, lv_running, lv_ready, lv_scheduled, lv_preliminary.
          CALL FUNCTION 'SHOW_JOBSTATE'
            EXPORTING
              jobname = ls_rule-jobname
              jobcount = ls_rule-jobcount
            IMPORTING
              aborted = lv_aborted
              finished = lv_finished
              preliminary = lv_preliminary
              ready = lv_ready
              running = lv_running
              scheduled = lv_scheduled
            EXCEPTIONS
              OTHERS = 1.
          IF sy-subrc <> 0.
            ls_rule-status = 'NO-JOB'.
          ELSEIF lv_finished = 'X'.
            ls_rule-status = 'FINISHED'.
          ELSEIF lv_aborted = 'X'.
            ls_rule-status = 'ABORTED'.
          ELSEIF lv_running = 'X'.
            ls_rule-status = 'RUNNING'.
          ELSEIF lv_ready = 'X'.
            ls_rule-status = 'READY'.
          ELSEIF lv_scheduled = 'X'.
            ls_rule-status = 'SCHEDULED'.
          ELSEIF lv_preliminary = 'X'.
            ls_rule-status = 'PRELIMINARY'.
          ELSE.
            ls_rule-status = 'OTHER'.
          ENDIF.
        ENDIF.
      ENDIF.
      IF ls_rule-status = 'FINISHED' OR ls_rule-status = 'DONE'.
        SELECT COUNT(*) FROM zosd_l3_alert
          WHERE set_name = c_set
            AND rule_name = ls_rule-rule
            AND model_hash = ls_rule-model_hash
            AND check_date = is_result-check_date
            AND run_id = is_result-run_id.
        ls_rule-alerts = sy-dbcnt.
        rs_result-alerts = rs_result-alerts + ls_rule-alerts.
      ENDIF.
      APPEND ls_rule TO rs_result-rules.
    ENDLOOP.
  ENDMETHOD.
ENDCLASS.
