* Generated by tools/dsl-l2.mjs from src/l2demo/ship_voyage_limit.l2.yaml; do not edit.
* Rule ship-too-many-future-voyages: A ship has at most two voyages departing after the check date
CLASS zcl_l2_ship_voyage_limit DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    TYPES tt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    CLASS-METHODS check
      IMPORTING iv_date TYPE d
                it_range TYPE tt_range OPTIONAL
      RETURNING VALUE(rt_alerts) TYPE string_table.
ENDCLASS.

CLASS zcl_l2_ship_voyage_limit IMPLEMENTATION.
  METHOD check.
    " one query: join rows counted per for key in the loop (HAVING probe fails here)
    TYPES: BEGIN OF ty_join,
             ship_ship_id TYPE zosd_l2_ship-ship_id,
             ship_name TYPE zosd_l2_ship-name,
           END OF ty_join.
    DATA lt_join TYPE STANDARD TABLE OF ty_join WITH DEFAULT KEY.
    DATA ls_join TYPE ty_join.
    DATA ls_prev TYPE ty_join.
    DATA lv_alert TYPE string.
    DATA lv_count TYPE i.
    DATA lv_count_text TYPE c LENGTH 12.
    SELECT
        ship~ship_id AS ship_ship_id
        ship~name AS ship_name
      FROM zosd_l2_ship AS ship
        INNER JOIN zosd_l2_voy AS voy
          ON voy~ship_id = ship~ship_id
      INTO CORRESPONDING FIELDS OF TABLE lt_join
      WHERE ship~status <> 'D'
        AND voy~dep_date > iv_date
        AND ship~ship_id IN it_range
      ORDER BY
        ship~ship_id.
    SORT lt_join BY ship_ship_id.
    LOOP AT lt_join INTO ls_join.
      IF lv_count > 0 AND ( ls_join-ship_ship_id <> ls_prev-ship_ship_id ).
        IF lv_count > 2.
          lv_count_text = lv_count.
          CONDENSE lv_count_text NO-GAPS.
          lv_alert = ls_prev-ship_ship_id
            && ` `
            && ls_prev-ship_name
            && `: `
            && lv_count_text
            && ` future voyages`.
          APPEND lv_alert TO rt_alerts.
        ENDIF.
        CLEAR lv_count.
      ENDIF.
      ADD 1 TO lv_count.
      ls_prev = ls_join.
    ENDLOOP.
    IF lv_count > 2.
      lv_count_text = lv_count.
      CONDENSE lv_count_text NO-GAPS.
      lv_alert = ls_prev-ship_ship_id
        && ` `
        && ls_prev-ship_name
        && `: `
        && lv_count_text
        && ` future voyages`.
      APPEND lv_alert TO rt_alerts.
    ENDIF.
  ENDMETHOD.
ENDCLASS.
