* Generated by tools/dsl-l2.mjs from src/l2demo/ship_min_captains.l2.yaml; do not edit.
* Rule ship-min-captains: An active ship needs two captains
CLASS zcl_l2_ship_min_captains DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS check
      IMPORTING iv_date TYPE d
      RETURNING VALUE(rt_alerts) TYPE string_table.
ENDCLASS.

CLASS zcl_l2_ship_min_captains IMPLEMENTATION.
  METHOD check.
    " one query: legal equality-only LEFT OUTER JOIN; missing counted side counts 0
    TYPES: BEGIN OF ty_join,
             ship_ship_id TYPE zosd_l2_ship-ship_id,
             ship_name TYPE zosd_l2_ship-name,
             crew_mandt TYPE zosd_l2_crew-mandt,
           END OF ty_join.
    DATA lt_join TYPE STANDARD TABLE OF ty_join WITH DEFAULT KEY.
    DATA ls_join TYPE ty_join.
    TYPES: BEGIN OF ty_count,
             ship_ship_id TYPE zosd_l2_ship-ship_id,
             cnt TYPE i,
           END OF ty_count.
    DATA lt_for TYPE STANDARD TABLE OF ty_join WITH DEFAULT KEY.
    DATA ls_for TYPE ty_join.
    DATA lt_count TYPE SORTED TABLE OF ty_count WITH UNIQUE KEY ship_ship_id.
    DATA ls_count TYPE ty_count.
    DATA lv_seen TYPE c LENGTH 1.
    DATA ls_prev TYPE ty_join.
    DATA lv_alert TYPE string.
    DATA lv_count TYPE i.
    DATA lv_count_text TYPE c LENGTH 12.
    SELECT
        ship~ship_id AS ship_ship_id
        ship~name AS ship_name
        crew~mandt AS crew_mandt
      FROM zosd_l2_ship AS ship
        LEFT OUTER JOIN zosd_l2_crew AS crew
          ON crew~ship_id = ship~ship_id
           AND crew~role = 'C'
      INTO CORRESPONDING FIELDS OF TABLE lt_join
      WHERE ship~status = 'A'
      ORDER BY
        ship~ship_id.
    LOOP AT lt_join INTO ls_join.
      IF lv_seen IS INITIAL OR ls_join-ship_ship_id <> ls_prev-ship_ship_id.
        APPEND ls_join TO lt_for.
      ENDIF.
      lv_seen = 'X'.
      ls_prev = ls_join.
      IF ls_join-crew_mandt IS INITIAL.
        CONTINUE.
      ENDIF.
      READ TABLE lt_count INTO ls_count WITH TABLE KEY ship_ship_id = ls_join-ship_ship_id.
      IF sy-subrc = 0.
        ADD 1 TO ls_count-cnt.
        MODIFY TABLE lt_count FROM ls_count.
      ELSE.
        MOVE-CORRESPONDING ls_join TO ls_count.
        ls_count-cnt = 1.
        INSERT ls_count INTO TABLE lt_count.
      ENDIF.
    ENDLOOP.
    LOOP AT lt_for INTO ls_for.
      CLEAR lv_count.
      READ TABLE lt_count INTO ls_count WITH TABLE KEY ship_ship_id = ls_for-ship_ship_id.
      IF sy-subrc = 0.
        lv_count = ls_count-cnt.
      ENDIF.
      IF lv_count < 2.
        lv_count_text = lv_count.
        CONDENSE lv_count_text NO-GAPS.
        lv_alert = ls_for-ship_ship_id
          && ` `
          && ls_for-ship_name
          && `: `
          && lv_count_text
          && ` captains`.
        APPEND lv_alert TO rt_alerts.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.
ENDCLASS.
