* Generated by tools/dsl-l2.mjs from src/l2demo/ship_busy.l2.yaml; do not edit.
* Rule ship-busy: A ship that is not decommissioned has a voyage departing after the check date
CLASS zcl_l2_ship_busy DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    TYPES tt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    CLASS-METHODS check
      IMPORTING iv_date TYPE d
                it_range TYPE tt_range OPTIONAL
      RETURNING VALUE(rt_alerts) TYPE string_table.
    " the driving keys check( ) flags: one I EQ row per key, sorted, each once
    CLASS-METHODS keys
      IMPORTING iv_date TYPE d
                it_range TYPE tt_range OPTIONAL
      RETURNING VALUE(rt_keys) TYPE tt_range.
ENDCLASS.

CLASS zcl_l2_ship_busy IMPLEMENTATION.
  METHOD check.
    " one query: the tables joined, never a SELECT per row of the first
    TYPES: BEGIN OF ty_join,
             ship_ship_id TYPE zosd_l2_ship-ship_id,
             voy_voyage_id TYPE zosd_l2_voy-voyage_id,
             ship_name TYPE zosd_l2_ship-name,
             voy_dep_date TYPE zosd_l2_voy-dep_date,
           END OF ty_join.
    DATA lt_join TYPE STANDARD TABLE OF ty_join WITH DEFAULT KEY.
    DATA ls_join TYPE ty_join.
    DATA lv_alert TYPE string.
    SELECT
        ship~ship_id AS ship_ship_id
        voy~voyage_id AS voy_voyage_id
        ship~name AS ship_name
        voy~dep_date AS voy_dep_date
      FROM zosd_l2_ship AS ship
        INNER JOIN zosd_l2_voy AS voy
          ON voy~ship_id = ship~ship_id
      INTO CORRESPONDING FIELDS OF TABLE lt_join
      WHERE ship~status <> 'D'
        AND voy~dep_date > iv_date
        AND ship~ship_id IN it_range
      ORDER BY
        ship~ship_id
        voy~voyage_id.
    LOOP AT lt_join INTO ls_join.
      lv_alert = ls_join-ship_ship_id
        && ` `
        && ls_join-ship_name
        && `: voyage `
        && ls_join-voy_voyage_id
        && ` departs `
        && ls_join-voy_dep_date.
      APPEND lv_alert TO rt_alerts.
    ENDLOOP.
  ENDMETHOD.

  METHOD keys.
    " the query of check( ) with the driving key only, DISTINCT: one query,
    " never a SELECT per row; a key flagged by several rows is one row
    DATA lt_keys TYPE STANDARD TABLE OF zosd_l2_ship-ship_id WITH DEFAULT KEY.
    DATA lv_key TYPE zosd_l2_ship-ship_id.
    DATA ls_key LIKE LINE OF rt_keys.
    SELECT DISTINCT ship~ship_id
      FROM zosd_l2_ship AS ship
        INNER JOIN zosd_l2_voy AS voy
          ON voy~ship_id = ship~ship_id
      APPENDING TABLE lt_keys
      WHERE ship~status <> 'D'
        AND voy~dep_date > iv_date
        AND ship~ship_id IN it_range
      ORDER BY ship~ship_id.
    SORT lt_keys.
    DELETE ADJACENT DUPLICATES FROM lt_keys.
    LOOP AT lt_keys INTO lv_key.
      ls_key-sign = 'I'.
      ls_key-option = 'EQ'.
      ls_key-low = lv_key.
      APPEND ls_key TO rt_keys.
    ENDLOOP.
  ENDMETHOD.
ENDCLASS.
