* Generated by tools/dsl-l2.mjs from src/l2demo/ship_min_crew.l2.yaml; do not edit.
* The examples of rule ship-min-crew and the cases derived from its conditions, one test method each.
* Every method runs check and check_reference (the obvious nested form, one
* SELECT per row) and asserts that they answer alike, then that check answers
* what the rule's interpreter expects.
* RISK LEVEL DANGEROUS: a method inserts its example's rows into the rule's
* own tables and its teardown deletes them again by key.
CLASS ltcl_examples DEFINITION FOR TESTING RISK LEVEL DANGEROUS DURATION SHORT FINAL.
  PRIVATE SECTION.
    TYPES tt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA mt_zosd_l2_ship TYPE STANDARD TABLE OF zosd_l2_ship WITH DEFAULT KEY.
    DATA mt_zosd_l2_crew TYPE STANDARD TABLE OF zosd_l2_crew WITH DEFAULT KEY.
    METHODS teardown.
    METHODS check_reference
      IMPORTING iv_date TYPE d
                it_range TYPE tt_range OPTIONAL
      RETURNING VALUE(rt_alerts) TYPE string_table.
    METHODS assert_alerts
      IMPORTING it_act TYPE string_table it_exp TYPE string_table iv_example TYPE string.
    METHODS assert_same_as_reference
      IMPORTING it_act TYPE string_table it_ref TYPE string_table iv_example TYPE string.
    METHODS one_crew_member FOR TESTING.
    METHODS no_crew FOR TESTING.
    METHODS two_crew_members FOR TESTING.
    METHODS three_crew_members FOR TESTING.
    METHODS one_not_yet_aboard FOR TESTING.
    METHODS filtered_ship FOR TESTING.
    METHODS other_ships_crew FOR TESTING.
    METHODS fleet_out_of_key_order FOR TESTING.
    METHODS the_range_keeps_the_inner_ship FOR TESTING.
    METHODS b_status_eq FOR TESTING.
    METHODS b_status_ne FOR TESTING.
    METHODS b_status_blank FOR TESTING.
    METHODS b_ship_id_match FOR TESTING.
    METHODS b_ship_id_nomatch FOR TESTING.
    METHODS b_since_lt FOR TESTING.
    METHODS b_since_eq FOR TESTING.
    METHODS b_since_gt FOR TESTING.
    METHODS b_count_below FOR TESTING.
    METHODS b_count_at FOR TESTING.
    METHODS b_count_zero FOR TESTING.
    METHODS b_count_next_zero FOR TESTING.
    METHODS b_count_groups FOR TESTING.
ENDCLASS.

CLASS ltcl_examples IMPLEMENTATION.

  METHOD teardown.
    DELETE zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR mt_zosd_l2_ship.
    DELETE zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    CLEAR mt_zosd_l2_crew.
  ENDMETHOD.

  METHOD check_reference.
    " the rule as a person would write it: a SELECT on the exists table for
    " every row of the first
    DATA lt_ship TYPE STANDARD TABLE OF zosd_l2_ship WITH DEFAULT KEY.
    DATA ls_ship TYPE zosd_l2_ship.
    DATA lt_crew TYPE STANDARD TABLE OF zosd_l2_crew WITH DEFAULT KEY.
    DATA ls_crew TYPE zosd_l2_crew.
    DATA lv_alert TYPE string.
    DATA lv_count TYPE i.
    DATA lv_count_text TYPE c LENGTH 12.
    SELECT * FROM zosd_l2_ship INTO TABLE lt_ship
      WHERE status = 'A'
        AND ship_id IN it_range
      ORDER BY PRIMARY KEY.
    LOOP AT lt_ship INTO ls_ship.
      SELECT * FROM zosd_l2_crew INTO TABLE lt_crew
        WHERE ship_id = ls_ship-ship_id
          AND since <= iv_date
        ORDER BY PRIMARY KEY.
      DESCRIBE TABLE lt_crew LINES lv_count.
      IF lv_count < 2.
        lv_count_text = lv_count.
        CONDENSE lv_count_text NO-GAPS.
        lv_alert = ls_ship-ship_id
          && ` `
          && ls_ship-name
          && `: `
          && lv_count_text
          && ` crew aboard`.
        APPEND lv_alert TO rt_alerts.
      ENDIF.
    ENDLOOP.
  ENDMETHOD.

  METHOD assert_alerts.
    " order-insensitive: the rule says which alerts, not in which order
    DATA lt_act TYPE string_table.
    DATA lt_exp TYPE string_table.
    lt_act = it_act.
    lt_exp = it_exp.
    SORT lt_act.
    SORT lt_exp.
    cl_abap_unit_assert=>assert_equals( act = lt_act exp = lt_exp msg = iv_example ).
  ENDMETHOD.

  METHOD assert_same_as_reference.
    " the query and the nested form answer alike, in the same order
    cl_abap_unit_assert=>assert_equals( act = it_act exp = it_ref msg = iv_example ).
  ENDMETHOD.

  METHOD one_crew_member.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    APPEND `S002 Cormorant: 1 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `one crew member (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `one crew member` ).
  ENDMETHOD.

  METHOD no_crew.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    APPEND `S001 Albatross: 0 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `no crew (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `no crew` ).
  ENDMETHOD.

  METHOD two_crew_members.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S003'.
    ls_zosd_l2_ship-name = 'Tern'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00002'.
    ls_zosd_l2_crew-ship_id = 'S003'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00003'.
    ls_zosd_l2_crew-ship_id = 'S003'.
    ls_zosd_l2_crew-role = 'K'.
    ls_zosd_l2_crew-since = '20261001'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `two crew members (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `two crew members` ).
  ENDMETHOD.

  METHOD three_crew_members.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S004'.
    ls_zosd_l2_ship-name = 'Gull'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00004'.
    ls_zosd_l2_crew-ship_id = 'S004'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00005'.
    ls_zosd_l2_crew-ship_id = 'S004'.
    ls_zosd_l2_crew-role = 'K'.
    ls_zosd_l2_crew-since = '20260201'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00006'.
    ls_zosd_l2_crew-ship_id = 'S004'.
    ls_zosd_l2_crew-role = 'P'.
    ls_zosd_l2_crew-since = '20260301'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `three crew members (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `three crew members` ).
  ENDMETHOD.

  METHOD one_not_yet_aboard.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S005'.
    ls_zosd_l2_ship-name = 'Heron'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00007'.
    ls_zosd_l2_crew-ship_id = 'S005'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00008'.
    ls_zosd_l2_crew-ship_id = 'S005'.
    ls_zosd_l2_crew-role = 'K'.
    ls_zosd_l2_crew-since = '20261002'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    APPEND `S005 Heron: 1 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `one not yet aboard (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `one not yet aboard` ).
  ENDMETHOD.

  METHOD filtered_ship.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S006'.
    ls_zosd_l2_ship-name = 'Egret'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `filtered ship (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `filtered ship` ).
  ENDMETHOD.

  METHOD other_ships_crew.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S008'.
    ls_zosd_l2_ship-name = 'Ibis'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S007'.
    ls_zosd_l2_ship-name = 'Crane'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00010'.
    ls_zosd_l2_crew-ship_id = 'S008'.
    ls_zosd_l2_crew-role = 'K'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00009'.
    ls_zosd_l2_crew-ship_id = 'S008'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    APPEND `S007 Crane: 0 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `other ships crew (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `other ships crew` ).
  ENDMETHOD.

  METHOD fleet_out_of_key_order.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S024'.
    ls_zosd_l2_ship-name = 'Rook'.
    ls_zosd_l2_ship-status = 'D'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S022'.
    ls_zosd_l2_ship-name = 'Lark'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S020'.
    ls_zosd_l2_ship-name = 'Wren'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S023'.
    ls_zosd_l2_ship-name = 'Kite'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S021'.
    ls_zosd_l2_ship-name = 'Teal'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00025'.
    ls_zosd_l2_crew-ship_id = 'S023'.
    ls_zosd_l2_crew-role = 'K'.
    ls_zosd_l2_crew-since = '20260501'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00020'.
    ls_zosd_l2_crew-ship_id = 'S020'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00023'.
    ls_zosd_l2_crew-ship_id = 'S022'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00022'.
    ls_zosd_l2_crew-ship_id = 'S020'.
    ls_zosd_l2_crew-role = 'P'.
    ls_zosd_l2_crew-since = '20260301'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00024'.
    ls_zosd_l2_crew-ship_id = 'S023'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00021'.
    ls_zosd_l2_crew-ship_id = 'S020'.
    ls_zosd_l2_crew-role = 'K'.
    ls_zosd_l2_crew-since = '20260201'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    APPEND `S021 Teal: 0 crew aboard` TO lt_exp.
    APPEND `S022 Lark: 1 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `fleet out of key order (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `fleet out of key order` ).
  ENDMETHOD.

  METHOD the_range_keeps_the_inner_ship.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_range.
    ls_range-sign = 'I'.
    ls_range-option = 'BT'.
    ls_range-low = 'S002'.
    ls_range-high = 'S003'.
    APPEND ls_range TO lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S004'.
    ls_zosd_l2_ship-name = 'Dove'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    APPEND `S002 Cormorant: 0 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `the range keeps the inner ship (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `the range keeps the inner ship` ).
  ENDMETHOD.

  METHOD b_status_eq.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    APPEND `S002 Cormorant: 1 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `ship.status = 'A': eq (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `ship.status = 'A': eq` ).
  ENDMETHOD.

  METHOD b_status_ne.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'B'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `ship.status = 'A': ne (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `ship.status = 'A': ne` ).
  ENDMETHOD.

  METHOD b_status_blank.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = ''.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `ship.status = 'A': blank (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `ship.status = 'A': blank` ).
  ENDMETHOD.

  METHOD b_ship_id_match.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'A00101'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `crew.ship_id = ship.ship_id: match (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `crew.ship_id = ship.ship_id: match` ).
  ENDMETHOD.

  METHOD b_ship_id_nomatch.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S003'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'A00101'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    APPEND `S002 Cormorant: 1 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `crew.ship_id = ship.ship_id: nomatch (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `crew.ship_id = ship.ship_id: nomatch` ).
  ENDMETHOD.

  METHOD b_since_lt.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260930'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'A00101'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `crew.since <= $date: lt (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `crew.since <= $date: lt` ).
  ENDMETHOD.

  METHOD b_since_eq.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20261001'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'A00101'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `crew.since <= $date: eq (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `crew.since <= $date: eq` ).
  ENDMETHOD.

  METHOD b_since_gt.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20261002'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'A00101'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    APPEND `S002 Cormorant: 1 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `crew.since <= $date: gt (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `crew.since <= $date: gt` ).
  ENDMETHOD.

  METHOD b_count_below.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    APPEND `S002 Cormorant: 1 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `1 matching rows: below (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `1 matching rows: below` ).
  ENDMETHOD.

  METHOD b_count_at.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'A00101'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `2 matching rows: at (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `2 matching rows: at` ).
  ENDMETHOD.

  METHOD b_count_zero.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    APPEND `S002 Cormorant: 0 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `0 matching rows: zero (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `0 matching rows: zero` ).
  ENDMETHOD.

  METHOD b_count_next_zero.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S003'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'A00101'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    APPEND `S003 Cormorant: 0 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `2 matching rows, then a key with none: next_zero (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `2 matching rows, then a key with none: next_zero` ).
  ENDMETHOD.

  METHOD b_count_groups.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_crew TYPE zosd_l2_crew.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'A002'.
    ls_zosd_l2_ship-name = 'Cormoranu'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'C00001'.
    ls_zosd_l2_crew-ship_id = 'S002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'A00500'.
    ls_zosd_l2_crew-ship_id = 'A002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    CLEAR ls_zosd_l2_crew.
    ls_zosd_l2_crew-mandt = sy-mandt.
    ls_zosd_l2_crew-crew_id = 'A00501'.
    ls_zosd_l2_crew-ship_id = 'A002'.
    ls_zosd_l2_crew-role = 'C'.
    ls_zosd_l2_crew-since = '20260101'.
    APPEND ls_zosd_l2_crew TO mt_zosd_l2_crew.
    INSERT zosd_l2_crew FROM TABLE mt_zosd_l2_crew.
    APPEND `S002 Cormorant: 1 crew aboard` TO lt_exp.
    lt_act = zcl_l2_ship_min_crew=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `1 and 2 matching rows in two groups: groups (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `1 and 2 matching rows in two groups: groups` ).
  ENDMETHOD.
ENDCLASS.
