* Generated by tools/dsl-l2.mjs from src/l2demo/ship_restricted_status.l2.yaml; do not edit.
* The examples of rule ship-restricted-status-no-voyage and the cases derived from its conditions, one test method each.
* Every method runs check and check_reference (the obvious nested form, one
* SELECT per row) and asserts that they answer alike, then that check answers
* what the rule's interpreter expects.
* RISK LEVEL DANGEROUS: a method inserts its example's rows into the rule's
* own tables and its teardown deletes them again by key.
CLASS ltcl_examples DEFINITION FOR TESTING RISK LEVEL DANGEROUS DURATION SHORT FINAL.
  PRIVATE SECTION.
    TYPES tt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA mt_zosd_l2_ship TYPE STANDARD TABLE OF zosd_l2_ship WITH DEFAULT KEY.
    DATA mt_zosd_l2_voy TYPE STANDARD TABLE OF zosd_l2_voy WITH DEFAULT KEY.
    METHODS teardown.
    METHODS check_reference
      IMPORTING iv_date TYPE d
                it_range TYPE tt_range OPTIONAL
                iv_restricted TYPE zcl_l2_ship_restricted=>tt_restricted OPTIONAL
                iv_exempt TYPE zcl_l2_ship_restricted=>tt_exempt OPTIONAL
      RETURNING VALUE(rt_alerts) TYPE string_table.
    METHODS assert_alerts
      IMPORTING it_act TYPE string_table it_exp TYPE string_table iv_example TYPE string.
    METHODS assert_same_as_reference
      IMPORTING it_act TYPE string_table it_ref TYPE string_table iv_example TYPE string.
    METHODS restricted_with_a_voyage_ahead FOR TESTING.
    METHODS active_ship_is_not_restricted FOR TESTING.
    METHODS second_default_status_counts FOR TESTING.
    METHODS restricted_past_voyage_only FOR TESTING.
    METHODS another_table_replaces_default FOR TESTING.
    METHODS empty_table_is_every_status FOR TESTING.
    METHODS e_row_alone_excludes_its_own FOR TESTING.
    METHODS bt_row_with_an_e_row_cut_out FOR TESTING.
    METHODS an_exempt_ship_is_skipped FOR TESTING.
    METHODS own_exempt_table FOR TESTING.
    METHODS key_range_keeps_inner_ship FOR TESTING.
    METHODS b_status_in FOR TESTING.
    METHODS b_status_out FOR TESTING.
    METHODS b_status_empty FOR TESTING.
    METHODS b_status_excl FOR TESTING.
    METHODS b_ship_id_in FOR TESTING.
    METHODS b_ship_id_out FOR TESTING.
    METHODS b_ship_id_empty FOR TESTING.
    METHODS b_ship_id_excl FOR TESTING.
    METHODS b_ship_id_match FOR TESTING.
    METHODS b_ship_id_nomatch FOR TESTING.
    METHODS b_dep_date_lt FOR TESTING.
    METHODS b_dep_date_eq FOR TESTING.
    METHODS b_dep_date_gt FOR TESTING.
    METHODS b_exists_zero FOR TESTING.
    METHODS b_exists_two FOR TESTING.
ENDCLASS.

CLASS ltcl_examples IMPLEMENTATION.

  METHOD teardown.
    DELETE zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR mt_zosd_l2_ship.
    DELETE zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    CLEAR mt_zosd_l2_voy.
  ENDMETHOD.

  METHOD check_reference.
    " the rule as a person would write it: a SELECT on the exists table for
    " every row of the first
    DATA lt_ship TYPE STANDARD TABLE OF zosd_l2_ship WITH DEFAULT KEY.
    DATA ls_ship TYPE zosd_l2_ship.
    DATA lt_voy TYPE STANDARD TABLE OF zosd_l2_voy WITH DEFAULT KEY.
    DATA ls_voy TYPE zosd_l2_voy.
    DATA lv_alert TYPE string.
    DATA lt_p_restricted TYPE zcl_l2_ship_restricted=>tt_restricted.
    DATA ls_p_restricted LIKE LINE OF lt_p_restricted.
    IF iv_restricted IS SUPPLIED.
      lt_p_restricted = iv_restricted.
    ELSE.
      CLEAR ls_p_restricted.
      ls_p_restricted-sign = 'I'.
      ls_p_restricted-option = 'EQ'.
      ls_p_restricted-low = 'M'.
      APPEND ls_p_restricted TO lt_p_restricted.
      CLEAR ls_p_restricted.
      ls_p_restricted-sign = 'I'.
      ls_p_restricted-option = 'EQ'.
      ls_p_restricted-low = 'D'.
      APPEND ls_p_restricted TO lt_p_restricted.
    ENDIF.
    DATA lt_p_exempt TYPE zcl_l2_ship_restricted=>tt_exempt.
    DATA ls_p_exempt LIKE LINE OF lt_p_exempt.
    IF iv_exempt IS SUPPLIED.
      lt_p_exempt = iv_exempt.
    ELSE.
      CLEAR ls_p_exempt.
      ls_p_exempt-sign = 'I'.
      ls_p_exempt-option = 'BT'.
      ls_p_exempt-low = 'S900'.
      ls_p_exempt-high = 'S999'.
      APPEND ls_p_exempt TO lt_p_exempt.
    ENDIF.
    SELECT * FROM zosd_l2_ship INTO TABLE lt_ship
      WHERE status IN lt_p_restricted
        AND ship_id NOT IN lt_p_exempt
        AND ship_id IN it_range
      ORDER BY PRIMARY KEY.
    LOOP AT lt_ship INTO ls_ship.
      SELECT * FROM zosd_l2_voy INTO TABLE lt_voy
        WHERE ship_id = ls_ship-ship_id
          AND dep_date > iv_date
        ORDER BY PRIMARY KEY.
      LOOP AT lt_voy INTO ls_voy.
        lv_alert = ls_ship-ship_id
          && ` `
          && ls_ship-name
          && `: restricted status `
          && ls_ship-status
          && `, voyage `
          && ls_voy-voyage_id
          && ` departs `
          && ls_voy-dep_date.
        APPEND lv_alert TO rt_alerts.
      ENDLOOP.
    ENDLOOP.
  ENDMETHOD.

  METHOD assert_alerts.
    " order-insensitive: the rule says which alerts, not in which order
    DATA lt_act TYPE string_table.
    DATA lt_exp TYPE string_table.
    lt_act = it_act.
    lt_exp = it_exp.
    SORT lt_act.
    SORT lt_exp.
    cl_abap_unit_assert=>assert_equals( act = lt_act exp = lt_exp msg = iv_example ).
  ENDMETHOD.

  METHOD assert_same_as_reference.
    " the query and the nested form answer alike, in the same order
    cl_abap_unit_assert=>assert_equals( act = it_act exp = it_ref msg = iv_example ).
  ENDMETHOD.

  METHOD restricted_with_a_voyage_ahead.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S001 Albatross: restricted status M, voyage V00001 departs 20261005` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `restricted with a voyage ahead (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `restricted with a voyage ahead` ).
  ENDMETHOD.

  METHOD active_ship_is_not_restricted.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00002'.
    ls_zosd_l2_voy-ship_id = 'S002'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `active ship is not restricted (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `active ship is not restricted` ).
  ENDMETHOD.

  METHOD second_default_status_counts.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S003'.
    ls_zosd_l2_ship-name = 'Petrel'.
    ls_zosd_l2_ship-status = 'D'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00003'.
    ls_zosd_l2_voy-ship_id = 'S003'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S003 Petrel: restricted status D, voyage V00003 departs 20261005` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `second default status counts (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `second default status counts` ).
  ENDMETHOD.

  METHOD restricted_past_voyage_only.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00004'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261001'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `restricted past voyage only (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `restricted past voyage only` ).
  ENDMETHOD.

  METHOD another_table_replaces_default.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    DATA lt_p_restricted TYPE zcl_l2_ship_restricted=>tt_restricted.
    DATA ls_p_restricted LIKE LINE OF lt_p_restricted.
    CLEAR ls_p_restricted.
    ls_p_restricted-sign = 'I'.
    ls_p_restricted-option = 'EQ'.
    ls_p_restricted-low = 'A'.
    APPEND ls_p_restricted TO lt_p_restricted.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00005'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00006'.
    ls_zosd_l2_voy-ship_id = 'S002'.
    ls_zosd_l2_voy-dep_date = '20261006'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S002 Cormorant: restricted status A, voyage V00006 departs 20261006` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `another table replaces default (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `another table replaces default` ).
  ENDMETHOD.

  METHOD empty_table_is_every_status.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    DATA lt_p_restricted TYPE zcl_l2_ship_restricted=>tt_restricted.
    DATA ls_p_restricted LIKE LINE OF lt_p_restricted.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00007'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00008'.
    ls_zosd_l2_voy-ship_id = 'S002'.
    ls_zosd_l2_voy-dep_date = '20261006'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S001 Albatross: restricted status M, voyage V00007 departs 20261005` TO lt_exp.
    APPEND `S002 Cormorant: restricted status A, voyage V00008 departs 20261006` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `empty table is every status (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `empty table is every status` ).
  ENDMETHOD.

  METHOD e_row_alone_excludes_its_own.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    DATA lt_p_restricted TYPE zcl_l2_ship_restricted=>tt_restricted.
    DATA ls_p_restricted LIKE LINE OF lt_p_restricted.
    CLEAR ls_p_restricted.
    ls_p_restricted-sign = 'E'.
    ls_p_restricted-option = 'EQ'.
    ls_p_restricted-low = 'M'.
    APPEND ls_p_restricted TO lt_p_restricted.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'A'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00009'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00010'.
    ls_zosd_l2_voy-ship_id = 'S002'.
    ls_zosd_l2_voy-dep_date = '20261006'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S002 Cormorant: restricted status A, voyage V00010 departs 20261006` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `E row alone excludes its own (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `E row alone excludes its own` ).
  ENDMETHOD.

  METHOD bt_row_with_an_e_row_cut_out.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    DATA lt_p_restricted TYPE zcl_l2_ship_restricted=>tt_restricted.
    DATA ls_p_restricted LIKE LINE OF lt_p_restricted.
    CLEAR ls_p_restricted.
    ls_p_restricted-sign = 'I'.
    ls_p_restricted-option = 'BT'.
    ls_p_restricted-low = 'A'.
    ls_p_restricted-high = 'M'.
    APPEND ls_p_restricted TO lt_p_restricted.
    CLEAR ls_p_restricted.
    ls_p_restricted-sign = 'E'.
    ls_p_restricted-option = 'EQ'.
    ls_p_restricted-low = 'D'.
    APPEND ls_p_restricted TO lt_p_restricted.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'D'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S003'.
    ls_zosd_l2_ship-name = 'Petrel'.
    ls_zosd_l2_ship-status = 'R'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00011'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00012'.
    ls_zosd_l2_voy-ship_id = 'S002'.
    ls_zosd_l2_voy-dep_date = '20261006'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00013'.
    ls_zosd_l2_voy-ship_id = 'S003'.
    ls_zosd_l2_voy-dep_date = '20261007'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S001 Albatross: restricted status M, voyage V00011 departs 20261005` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `BT row with an E row cut out (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `BT row with an E row cut out` ).
  ENDMETHOD.

  METHOD an_exempt_ship_is_skipped.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S901'.
    ls_zosd_l2_ship-name = 'Skiff'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00016'.
    ls_zosd_l2_voy-ship_id = 'S901'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `an exempt ship is skipped (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `an exempt ship is skipped` ).
  ENDMETHOD.

  METHOD own_exempt_table.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    DATA lt_p_exempt TYPE zcl_l2_ship_restricted=>tt_exempt.
    DATA ls_p_exempt LIKE LINE OF lt_p_exempt.
    CLEAR ls_p_exempt.
    ls_p_exempt-sign = 'I'.
    ls_p_exempt-option = 'EQ'.
    ls_p_exempt-low = 'S001'.
    APPEND ls_p_exempt TO lt_p_exempt.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S901'.
    ls_zosd_l2_ship-name = 'Skiff'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00017'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00018'.
    ls_zosd_l2_voy-ship_id = 'S901'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S901 Skiff: restricted status M, voyage V00018 departs 20261005` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range iv_exempt = lt_p_exempt ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range iv_exempt = lt_p_exempt ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `own exempt table (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `own exempt table` ).
  ENDMETHOD.

  METHOD key_range_keeps_inner_ship.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_range.
    ls_range-sign = 'I'.
    ls_range-option = 'EQ'.
    ls_range-low = 'S002'.
    APPEND ls_range TO lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S002'.
    ls_zosd_l2_ship-name = 'Cormorant'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00014'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00015'.
    ls_zosd_l2_voy-ship_id = 'S002'.
    ls_zosd_l2_voy-dep_date = '20261006'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S002 Cormorant: restricted status M, voyage V00015 departs 20261006` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `key range keeps inner ship (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `key range keeps inner ship` ).
  ENDMETHOD.

  METHOD b_status_in.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S001 Albatross: restricted status M, voyage V00001 departs 20261005` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `ship.status in $restricted: in (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `ship.status in $restricted: in` ).
  ENDMETHOD.

  METHOD b_status_out.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'N'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `ship.status in $restricted: out (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `ship.status in $restricted: out` ).
  ENDMETHOD.

  METHOD b_status_empty.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    DATA lt_p_restricted TYPE zcl_l2_ship_restricted=>tt_restricted.
    DATA ls_p_restricted LIKE LINE OF lt_p_restricted.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'N'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S001 Albatross: restricted status N, voyage V00001 departs 20261005` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `ship.status in $restricted: empty (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `ship.status in $restricted: empty` ).
  ENDMETHOD.

  METHOD b_status_excl.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    DATA lt_p_restricted TYPE zcl_l2_ship_restricted=>tt_restricted.
    DATA ls_p_restricted LIKE LINE OF lt_p_restricted.
    CLEAR ls_p_restricted.
    ls_p_restricted-sign = 'I'.
    ls_p_restricted-option = 'EQ'.
    ls_p_restricted-low = 'M'.
    APPEND ls_p_restricted TO lt_p_restricted.
    CLEAR ls_p_restricted.
    ls_p_restricted-sign = 'I'.
    ls_p_restricted-option = 'EQ'.
    ls_p_restricted-low = 'D'.
    APPEND ls_p_restricted TO lt_p_restricted.
    CLEAR ls_p_restricted.
    ls_p_restricted-sign = 'E'.
    ls_p_restricted-option = 'EQ'.
    ls_p_restricted-low = 'M'.
    APPEND ls_p_restricted TO lt_p_restricted.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range iv_restricted = lt_p_restricted ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `ship.status in $restricted: excl (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `ship.status in $restricted: excl` ).
  ENDMETHOD.

  METHOD b_ship_id_in.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S900'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S900'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `ship.ship_id not in $exempt: in (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `ship.ship_id not in $exempt: in` ).
  ENDMETHOD.

  METHOD b_ship_id_out.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S99A'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S99A'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S99A Albatross: restricted status M, voyage V00001 departs 20261005` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `ship.ship_id not in $exempt: out (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `ship.ship_id not in $exempt: out` ).
  ENDMETHOD.

  METHOD b_ship_id_empty.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    DATA lt_p_exempt TYPE zcl_l2_ship_restricted=>tt_exempt.
    DATA ls_p_exempt LIKE LINE OF lt_p_exempt.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S99A'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S99A'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range iv_exempt = lt_p_exempt ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range iv_exempt = lt_p_exempt ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `ship.ship_id not in $exempt: empty (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `ship.ship_id not in $exempt: empty` ).
  ENDMETHOD.

  METHOD b_ship_id_excl.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    DATA lt_p_exempt TYPE zcl_l2_ship_restricted=>tt_exempt.
    DATA ls_p_exempt LIKE LINE OF lt_p_exempt.
    CLEAR ls_p_exempt.
    ls_p_exempt-sign = 'I'.
    ls_p_exempt-option = 'BT'.
    ls_p_exempt-low = 'S900'.
    ls_p_exempt-high = 'S999'.
    APPEND ls_p_exempt TO lt_p_exempt.
    CLEAR ls_p_exempt.
    ls_p_exempt-sign = 'E'.
    ls_p_exempt-option = 'EQ'.
    ls_p_exempt-low = 'S900'.
    APPEND ls_p_exempt TO lt_p_exempt.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S900'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S900'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S900 Albatross: restricted status M, voyage V00001 departs 20261005` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range iv_exempt = lt_p_exempt ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range iv_exempt = lt_p_exempt ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `ship.ship_id not in $exempt: excl (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `ship.ship_id not in $exempt: excl` ).
  ENDMETHOD.

  METHOD b_ship_id_match.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S001 Albatross: restricted status M, voyage V00001 departs 20261005` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `voy.ship_id = ship.ship_id: match (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `voy.ship_id = ship.ship_id: match` ).
  ENDMETHOD.

  METHOD b_ship_id_nomatch.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S002'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `voy.ship_id = ship.ship_id: nomatch (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `voy.ship_id = ship.ship_id: nomatch` ).
  ENDMETHOD.

  METHOD b_dep_date_lt.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20260930'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `voy.dep_date > $date: lt (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `voy.dep_date > $date: lt` ).
  ENDMETHOD.

  METHOD b_dep_date_eq.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261001'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `voy.dep_date > $date: eq (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `voy.dep_date > $date: eq` ).
  ENDMETHOD.

  METHOD b_dep_date_gt.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261002'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S001 Albatross: restricted status M, voyage V00001 departs 20261002` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `voy.dep_date > $date: gt (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `voy.dep_date > $date: gt` ).
  ENDMETHOD.

  METHOD b_exists_zero.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `exists ZOSD_L2_VOY as voy: zero (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `exists ZOSD_L2_VOY as voy: zero` ).
  ENDMETHOD.

  METHOD b_exists_two.
    DATA ls_zosd_l2_ship TYPE zosd_l2_ship.
    DATA ls_zosd_l2_voy TYPE zosd_l2_voy.
    DATA lt_act TYPE string_table.
    DATA lt_ref TYPE string_table.
    DATA lt_exp TYPE string_table.
    DATA lt_range TYPE RANGE OF zosd_l2_ship-ship_id.
    DATA ls_range LIKE LINE OF lt_range.
    CLEAR ls_zosd_l2_ship.
    ls_zosd_l2_ship-mandt = sy-mandt.
    ls_zosd_l2_ship-ship_id = 'S001'.
    ls_zosd_l2_ship-name = 'Albatross'.
    ls_zosd_l2_ship-status = 'M'.
    APPEND ls_zosd_l2_ship TO mt_zosd_l2_ship.
    INSERT zosd_l2_ship FROM TABLE mt_zosd_l2_ship.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00001'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    CLEAR ls_zosd_l2_voy.
    ls_zosd_l2_voy-mandt = sy-mandt.
    ls_zosd_l2_voy-voyage_id = 'V00002'.
    ls_zosd_l2_voy-ship_id = 'S001'.
    ls_zosd_l2_voy-dep_date = '20261005'.
    APPEND ls_zosd_l2_voy TO mt_zosd_l2_voy.
    INSERT zosd_l2_voy FROM TABLE mt_zosd_l2_voy.
    APPEND `S001 Albatross: restricted status M, voyage V00001 departs 20261005` TO lt_exp.
    APPEND `S001 Albatross: restricted status M, voyage V00002 departs 20261005` TO lt_exp.
    lt_act = zcl_l2_ship_restricted=>check( iv_date = '20261001' it_range = lt_range ).
    lt_ref = check_reference( iv_date = '20261001' it_range = lt_range ).
    assert_same_as_reference( it_act = lt_act it_ref = lt_ref iv_example = `exists ZOSD_L2_VOY as voy: two (check against check_reference)` ).
    assert_alerts( it_act = lt_act it_exp = lt_exp iv_example = `exists ZOSD_L2_VOY as voy: two` ).
  ENDMETHOD.
ENDCLASS.
