* Generated by tools/dsl-l3.mjs from src/l2demo/fleet.l3.yaml; do not edit.
* Port ships of set fleet, variant table: the table the rules read.
CLASS zcl_l3_fleet_ships_table DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES zif_l3_fleet_ships.
ENDCLASS.

CLASS zcl_l3_fleet_ships_table IMPLEMENTATION.
  METHOD zif_l3_fleet_ships~read.
    SELECT * FROM zosd_l2_ship INTO TABLE rt_rows WHERE ship_id IN it_range.
  ENDMETHOD.
ENDCLASS.
