REPORT zl3_fleet3.
* Generated by tools/dsl-l3.mjs from src/l2demo/fleet3.l3.yaml; do not edit.
* Set fleet3: one rule of the set as one background job step,
* submitted by zcl_l3_fleet3=>run( iv_mode = 'P' ).
* One pile of the rule: the job reads its range from the plan row
* ZOSD_L3_PILE (set, p_run, p_rule, p_pile), not from a selection field.

PARAMETERS p_rule TYPE c LENGTH 60 LOWER CASE.
PARAMETERS p_date TYPE d.
PARAMETERS p_run TYPE c LENGTH 32.
PARAMETERS p_pile TYPE i.
PARAMETERS p_bind TYPE c LENGTH 255 LOWER CASE.
PARAMETERS s_1 TYPE c LENGTH 40 LOWER CASE.
PARAMETERS p_active TYPE zosd_l2_ship-status.
DATA gv_s_restricted TYPE zosd_l2_ship-status.
SELECT-OPTIONS s_restri FOR gv_s_restricted.
DATA gv_s_exempt TYPE zosd_l2_ship-ship_id.
SELECT-OPTIONS s_exempt FOR gv_s_exempt.

START-OF-SELECTION.
  DATA ls_rule TYPE zcl_l3_fleet3=>ty_rule.
  DATA lv_bind TYPE string.
  DATA ls_settings TYPE zcl_l3_fleet3_conf=>ty_values.
  ls_settings-params_restricted = s_1.
  DATA ls_params TYPE zcl_l3_fleet3=>ty_params.
  ls_params-active_status = p_active.
  ls_params-restricted = s_restri[].
  ls_params-exempt = s_exempt[].
  lv_bind = p_bind.
  ls_rule = zcl_l3_fleet3=>run_rule(
    iv_rule = p_rule
    iv_date = p_date
    iv_run = p_run
    is_settings = ls_settings
    iv_pile = p_pile
    is_params = ls_params
    iv_bind = lv_bind ).
  WRITE: / ls_rule-rule, ls_rule-status, ls_rule-alerts.
  IF ls_rule-status <> 'DONE'.
    MESSAGE 'The rule did not run to the end; see the list' TYPE 'E'.
  ENDIF.
