CLASS zcl_osd_lift_r3_probe DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS ping.
ENDCLASS.
CLASS zcl_osd_lift_r3_probe IMPLEMENTATION.
  METHOD ping.
  ENDMETHOD.
ENDCLASS.
