CLASS zcl_gogen_unit_where DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS divide IMPORTING iv TYPE i RETURNING VALUE(rv) TYPE i.
ENDCLASS.

CLASS zcl_gogen_unit_where IMPLEMENTATION.
  METHOD divide.
    rv = 1 / iv.
  ENDMETHOD.
ENDCLASS.
