CLASS zcl_zstg_sadl_dpc_ext DEFINITION PUBLIC INHERITING FROM zcl_zstg_sadl_dpc CREATE PUBLIC.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_zstg_sadl_dpc_ext IMPLEMENTATION.
ENDCLASS.
