CLASS zcl_zstg_sadl_mpc_ext DEFINITION PUBLIC INHERITING FROM zcl_zstg_sadl_mpc CREATE PUBLIC.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_zstg_sadl_mpc_ext IMPLEMENTATION.
ENDCLASS.
