* Generated by tools/dsl-l3.mjs from {{source}}; do not edit.
* Set {{set}}: a port, a variant or a binding the set does not have, or one a run cannot use.
CLASS {{exception}} DEFINITION PUBLIC INHERITING FROM cx_no_check FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    DATA port TYPE string READ-ONLY.
    DATA variant TYPE string READ-ONLY.
    DATA reason TYPE string READ-ONLY.
    METHODS constructor
      IMPORTING iv_port TYPE csequence OPTIONAL
                iv_variant TYPE csequence OPTIONAL
                iv_reason TYPE csequence OPTIONAL.
    METHODS if_message~get_text REDEFINITION.
ENDCLASS.

CLASS {{exception}} IMPLEMENTATION.
  METHOD constructor.
    super->constructor( ).
    port = iv_port.
    variant = iv_variant.
    reason = iv_reason.
  ENDMETHOD.

  METHOD if_message~get_text.
    result = `port ` && port && ` variant ` && variant && `: ` && reason.
  ENDMETHOD.
ENDCLASS.
