* Generated by tools/dsl-l3.mjs from {{source}}; do not edit.
* Port {{port}} of set {{set}}: a sink of {{table}} rows.
INTERFACE {{iface}} PUBLIC.
  TYPES tt_rows TYPE STANDARD TABLE OF {{table}} WITH DEFAULT KEY.
  TYPES: BEGIN OF ty_group,
{{#group}}
           {{name}} TYPE {{table}}-{{name}},
{{/group}}
         END OF ty_group.
  " the rows of one group (its key fields given in is_group) as the run found
  " them, in {{seq}} order; the answer is how many rows the sink took
  METHODS put
    IMPORTING it_rows TYPE tt_rows
              is_group TYPE ty_group
    RETURNING VALUE(rv_count) TYPE i.
ENDINTERFACE.
