* Generated by tools/dsl-l3.mjs from {{source}}; do not edit.
* Port {{port}} of set {{set}}: the work of one pile. Variant real is the
* runner's own static calls of the L2 classes; sim is a simulated twin.
INTERFACE {{iface}} PUBLIC.
  " one pile: its stream is a pure function of seed, run, rule, pile and
  " attempt; scale is wall millionths of a second per simulated second
  TYPES: BEGIN OF ty_pile,
           run_id TYPE c LENGTH 32,
           rule TYPE c LENGTH 60,
           pile_no TYPE i,
           attempt TYPE i,
           seed TYPE i,
           scale TYPE i,
           stale TYPE i,
         END OF ty_pile.
  " a check rule's work: its alert lines over the pile's keys
  METHODS check
    IMPORTING is_pile TYPE ty_pile
              it_keys TYPE string_table
    RETURNING VALUE(rt_alerts) TYPE string_table.
  " a filter rule's work: the keys of the pile it selects
  METHODS keys
    IMPORTING is_pile TYPE ty_pile
              it_keys TYPE string_table
    RETURNING VALUE(rt_keys) TYPE string_table.
ENDINTERFACE.
