* Generated by tools/dsl-l3.mjs from {{source}}; do not edit.
* Port {{port}} of set {{set}}, variant {{variant}}: the table the rules read.
CLASS {{class}} DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES {{iface}}.
ENDCLASS.

CLASS {{class}} IMPLEMENTATION.
  METHOD {{iface}}~read.
    SELECT * FROM {{table}} INTO TABLE rt_rows WHERE {{key}} IN it_range.
  ENDMETHOD.

  METHOD {{iface}}~live.
    rv_live = abap_true.
  ENDMETHOD.

  METHOD {{iface}}~volatile.
    rv_volatile = abap_false.
  ENDMETHOD.
ENDCLASS.
