CLASS ltcl_local DEFINITION FOR TESTING.
  PUBLIC SECTION.
    CLASS-METHODS run RETURNING VALUE(r) TYPE i.
ENDCLASS.
CLASS ltcl_local IMPLEMENTATION.
  METHOD run.
    DO 1000000 TIMES.
      r = r + 1.
    ENDDO.
  ENDMETHOD.
ENDCLASS.
