"! GENERATED by tools/osd-sxml-contract.mjs from test/fixtures/sxml-contract/cases.json;
"! edit that file and run the tool, never this one. The fixtures of
"! ZCL_OSD_SXML_CONTRACT as ABAP, so every host loads them the same way.
"! STATUS provisional-fork: generated from the pinned open-abap-core fork,
"! not an oracle. STATUS provisional-spec: written from the XML or
"! JSON-XML rules where the fork is visibly wrong. STATUS
"! measured-a4h-<date>: measured on A4H. FORK: what the pinned fork does
"! with it: empty = passes, MISS = another sequence, DUMPS = a runtime
"! error no CATCH sees, which ends the whole run.
CLASS zcl_osd_sxml_fixtures DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS all
      RETURNING VALUE(rt) TYPE zcl_osd_sxml_contract=>ty_fixtures.
ENDCLASS.


CLASS zcl_osd_sxml_fixtures IMPLEMENTATION.

  METHOD all.
    DATA ls TYPE zcl_osd_sxml_contract=>ty_fixture.
    DATA lv_hex TYPE string.
    DATA lv_line TYPE string.

    CLEAR ls.
    ls-name = `json_empty_object`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `7B7D`.
    ls-input = lv_hex.
    lv_line = `OPEN "object" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "object"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_empty_array`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `5B5D`.
    ls-input = lv_hex.
    lv_line = `OPEN "array" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "array"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_simple_integer`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `32`.
    ls-input = lv_hex.
    lv_line = `OPEN "num" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "2"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "num"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_simple_true`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `74727565`.
    ls-input = lv_hex.
    lv_line = `OPEN "bool" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "true"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "bool"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_simple_null`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `6E756C6C`.
    ls-input = lv_hex.
    lv_line = `OPEN "null" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "null"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_integer_array`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `5B325D`.
    ls-input = lv_hex.
    lv_line = `OPEN "array" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "num" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "2"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "num"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "array"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_key_value`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `7B226B657931223A202276616C756531227D`.
    ls-input = lv_hex.
    lv_line = `OPEN "object" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "str" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "name" "" "key1"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "value1"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "str"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "object"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_key_empty`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `7B226B657931223A205B5D7D`.
    ls-input = lv_hex.
    lv_line = `OPEN "object" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "array" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "name" "" "key1"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "array"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "object"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_empty_key`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `7B22223A20317D`.
    ls-input = lv_hex.
    lv_line = `OPEN "object" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "num" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "name" "" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "1"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "num"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "object"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_two_keys`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `7B226B657931223A202276616C756531222C20226B657932223A202276616C756532227D`.
    ls-input = lv_hex.
    lv_line = `OPEN "object" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "str" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "name" "" "key1"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "value1"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "str"`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "str" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "name" "" "key2"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "value2"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "str"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "object"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_two_array`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `5B312C20325D`.
    ls-input = lv_hex.
    lv_line = `OPEN "array" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "num" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "1"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "num"`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "num" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "2"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "num"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "array"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_array_with_object`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `5B7B226B6579223A202276616C7565227D5D`.
    ls-input = lv_hex.
    lv_line = `OPEN "array" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "object" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "str" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "name" "" "key"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "value"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "str"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "object"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "array"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_object_with_object`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `7B226B6579223A207B22737562223A202276616C7565227D7D`.
    ls-input = lv_hex.
    lv_line = `OPEN "object" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "object" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "name" "" "key"`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "str" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "name" "" "sub"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "value"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "str"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "object"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "object"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_bad`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `6D6F6F2C2068656C6C6F20776F726C64`.
    ls-input = lv_hex.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 0`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_bad_offset`.
    ls-group = `json-ported`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `7B0A226F6B223A2022616263222C0A226572726F72220A7D`.
    ls-input = lv_hex.
    lv_line = `OPEN "object" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "str" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "name" "" "ok"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "abc"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "str"`.
    APPEND lv_line TO ls-expected.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 23`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `json_non_ascii`.
    ls-group = `json`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `7B22C3A9E282ACF09F9880223A2022C3A9E282ACF09F9880227D`.
    ls-input = lv_hex.
    lv_line = `OPEN "object" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "str" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "name" "" "\u00E9\u20AC\uD83D\uDE00"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "\u00E9\u20AC\uD83D\uDE00"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "str"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "object"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_simple`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C613E743C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "t"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_name_e_acute`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3CC3A920C3A9783D2276223E743C2FC3A93E`.
    ls-input = lv_hex.
    lv_line = `OPEN "\u00E9" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "\u00E9x" "" "v"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "t"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "\u00E9"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_name_euro`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C61E282AC3E743C2F61E282AC3E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a\u20AC" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "t"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a\u20AC"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_name_astral`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C61F09F98802F3E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a\uD83D\uDE00" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a\uD83D\uDE00"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_non_ascii_values`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C6120783D22C3A9E282ACF09F9880223EC3A9E282ACF09F98803C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "x" "" "\u00E9\u20AC\uD83D\uDE00"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "\u00E9\u20AC\uD83D\uDE00"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_non_ascii_cdata`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C613E3C215B43444154415BC3A9E282ACF09F98805D5D3E3C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "\u00E9\u20AC\uD83D\uDE00"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_non_ascii_comment`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C613E3C212D2DC3A9E282ACF09F98802D2D3E743C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "t"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_entities`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C6120783D2226616D703B262378323041433B26233132383531323B223E26616D703B262378323041433B26233132383531323B266C743B2667743B2671756F743B2661706F733B3C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "x" "" "&\u20AC\uD83D\uDE00"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "&\u20AC\uD83D\uDE00<>\u0022'"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_cdata_brackets`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C613E3C215B43444154415B785D5D795D5D5D3E3C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "x]]y]"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_comment_dashes`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613E313C212D2D20612D62202D20632D202D2D3E323C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "12"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_pi`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C3F786D6C2076657273696F6E3D22312E30223F3E3C3F706920646174613F3E3C613E3C3F696E6E657220783F3E743C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "t"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_bom`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `EFBBBF3C613E743C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "t"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_namespaces`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C7220786D6C6E733D2275726E3A642220786D6C6E733A703D2275726E3A70223E3C703A6320703A783D22312220793D2232223E743C2F703A633E3C642F3E3C2F723E`.
    ls-input = lv_hex.
    lv_line = `OPEN "r" "urn:d"`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "c" "urn:p"`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "x" "urn:p" "1"`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "y" "" "2"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "t"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "c"`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "d" "urn:d"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "d"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "r"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_empty_elements`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C613E3C622F3E3C633E3C2F633E3C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "b" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "b"`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "c" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "c"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_whitespace_only`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C613E203C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE " "`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_whitespace_between`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C613E0A20203C623E783C2F623E0A3C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "b" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "x"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "b"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_long_text`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C613E61626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F9880`.
    lv_hex = lv_hex && `2061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061`.
    lv_hex = lv_hex && `626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F988020616263`.
    lv_hex = lv_hex && `20C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3`.
    lv_hex = lv_hex && `A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E2`.
    lv_hex = lv_hex && `82ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F9880203C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD`.
    lv_line = lv_line && `83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC`.
    lv_line = lv_line && `\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u2`.
    lv_line = lv_line && `0AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9`.
    lv_line = lv_line && `\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u0`.
    lv_line = lv_line && `0E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 abc \u00E9\u20AC\uD83D\uDE00 "`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_decl_lowercase_utf8`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `DUMPS`.
    lv_hex = `3C3F786D6C2076657273696F6E3D22312E302220656E636F64696E673D227574662D38223F3E3C613EC3A93C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "\u00E9"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_astral_text`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C613EF09F98803C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "\uD83D\uDE00"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_text_cdata_merged`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C61C3A920783D22C3A9E282AC223EC3A9E282AC3C215B43444154415BC3A95D5D5D5D3E3C2F61C3A93E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a\u00E9" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "x" "" "\u00E9\u20AC"`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "\u00E9\u20AC\u00E9]]"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a\u00E9"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_ff_in_comment`.
    ls-group = `xml`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613E3C212D2DFF2D2D3E3C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_unclosed`.
    ls-group = `xml-invalid`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C613E3C623E743C2F623E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `OPEN "b" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "t"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "b"`.
    APPEND lv_line TO ls-expected.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 11`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_mismatched_close`.
    ls-group = `xml-invalid`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613E3C2F623E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 3`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_mismatched_close_non_ascii`.
    ls-group = `xml-invalid`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613EC3A9E282AC3C2F623E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "\u00E9\u20AC"`.
    APPEND lv_line TO ls-expected.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 8`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_lt_in_attribute`.
    ls-group = `xml-invalid`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C6120783D22C3A9C3A93C222F3E`.
    ls-input = lv_hex.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 6`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_cdata_end_in_text`.
    ls-group = `xml-invalid`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = `3C613E785D5D3E793C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "x]]>y"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_bad_entity`.
    ls-group = `xml-invalid`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613E26666F6F3B3C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 3`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_bad_charref`.
    ls-group = `xml-invalid`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613E262378443830303B3C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 3`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_comment_double_dash`.
    ls-group = `xml-invalid`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613E3C212D2D782D2D792D2D3E3C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 7`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `xml_empty_document`.
    ls-group = `xml-invalid`.
    ls-status = `measured-a4h-2026-10-01`.
    lv_hex = ``.
    ls-input = lv_hex.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 0`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `utf8_lone_continuation`.
    ls-group = `utf8`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613E80613C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "\uFFFDa"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `utf8_overlong`.
    ls-group = `utf8`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613EC0AF613C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "\uFFFDa"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `utf8_truncated_3`.
    ls-group = `utf8`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613EE282613C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "\uFFFD\uFFFDa"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `utf8_truncated_3_before_lt`.
    ls-group = `utf8`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613EE2823C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 5`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `utf8_truncated_4_before_lt`.
    ls-group = `utf8`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613EF09F983C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ERROR CX_SXML_PARSE_ERROR 6`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `utf8_encoded_surrogate`.
    ls-group = `utf8`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613EEDA0803C2F613E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "\uD800"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `utf8_truncated_at_eof`.
    ls-group = `utf8`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C613E613C2F613EE282`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `VALUE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.

    CLEAR ls.
    ls-name = `utf8_in_attribute`.
    ls-group = `utf8`.
    ls-status = `measured-a4h-2026-10-01`.
    ls-fork = `MISS`.
    lv_hex = `3C6120783D2280222F3E`.
    ls-input = lv_hex.
    lv_line = `OPEN "a" ""`.
    APPEND lv_line TO ls-expected.
    lv_line = `ATTR "x" "" "\uFFFD"`.
    APPEND lv_line TO ls-expected.
    lv_line = `CLOSE "a"`.
    APPEND lv_line TO ls-expected.
    lv_line = `FINAL`.
    APPEND lv_line TO ls-expected.
    APPEND ls TO rt.
  ENDMETHOD.

ENDCLASS.
