// Builds the static preview deployment into build/:
//   sw.js        the transpiled gateway + sql.js in a service worker
//   index.html   installs the worker, then goes to app/
//   app/         the Fiori Elements demo app, service URI relative to the mount
// Run after `npm run transpile`. No server is involved: GitHub Pages (or any
// static host) serves these files, the worker answers the OData requests.
import {copyFile, mkdir, readFile, readdir, writeFile, stat} from "node:fs/promises";
import {createHash} from "node:crypto";
import {createRequire} from "node:module";
import {join, resolve} from "node:path";
import {fileURLToPath} from "node:url";
import {seedStatements} from "../test/seed.mjs";
import {services as icfServices, channels as apcChannels} from "../tools/osd-icf.mjs";
import {folderOf, packsOf, tilesOf, webappsOf} from "../tools/osd-packs.mjs";
import {describeUnfetched, unfetched} from "../tools/osd-fetch.mjs";
import {packsInfo, servicesOf} from "../tools/osd-status.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));
const generated = resolve(root, "web/generated");
// build/preview, not build/: build/ is the generation store of tools/osd-build.mjs
// (build/live is what output/ points at), and webpack cleans its output
// directory before writing, which took the transpile it was bundling with it
const build = resolve(root, "build/preview");
// the seed and the packs read the tree the builder built; say which one
process.env.OSD_ROOT = root;

// The packs are in this build the way they are in a served system: their
// ABAP went through the transpile already (tools/osd-build.mjs lists them
// as layers), and here their ICF nodes, channels, seed rows, pages and
// tiles follow. A pack that fetches a folder and has not is refused, as the
// build refuses it: a preview of a smaller system than the manifest says
// would be published as if it were the whole.
const missing = unfetched(root);
if (missing.length > 0) {
  throw new Error(describeUnfetched(missing));
}
const packs = packsOf(root);
const roots = [...new Set(["src", "local", "test", "gen", ...packs.flatMap((p) => p.abap.map((f) => folderOf(root, f)))])];
console.log(`Packs: ${packs.length === 0 ? "(none)" : packs.map((p) => p.name).join(", ")}`);

// the seed rows, and a build id that tells a stored browser database from a
// deployment it no longer fits
await mkdir(generated, {recursive: true});
// every folder of rows, the tree's own and each pack's, in layer order
const seed = seedStatements();
const init = await readFile(resolve(root, "output/init.mjs"), "utf8");
const buildId = createHash("sha256").update(init).update(seed.join("\n")).digest("hex").slice(0, 16);
await writeFile(resolve(generated, "seed.mjs"),
  "// Generated by scripts/build-preview.mjs. Do not edit.\n"
  + `export const buildId = ${JSON.stringify(buildId)};\n`
  + `export const seed = ${JSON.stringify(seed, undefined, 2)};\n`, "utf8");
console.log(`Seed: ${seed.length} statements, build ${buildId}`);

// The services this deployment answers, written out so the worker and the
// backend agree without either hard-coding a path.
//
// The OData front is one of them rather than a special case: it is an
// if_http_extension on a prefix exactly like the rest, and the only reason it
// used to be written into two files by hand is that it was the only one. A
// repository imported under local/ brings its own *.sicf.xml and appears here
// with no change to this script.
const RESERVED = [];
// which pack a path came from, worked out the way the facade works it out
// (tools/osd-status.mjs), so the status service in the browser can name the
// pack a service belongs to without the worker reading any manifest
const facadeServices = servicesOf(root);
const packOfPath = new Map(facadeServices.map((s) => [s.path, s.pack]));
const table = [
  {path: "/sap/opu/odata/sap", handler: "ZCL_STG_HTTP_HANDLER", name: "OData", pack: ""},
  ...icfServices(root, {roots})
    .filter((s) => s.handler !== undefined)
    .filter((s) => RESERVED.includes(s.path) === false)
    .map((s) => ({path: s.path, handler: s.handler, name: s.name, text: s.description ?? "", pack: packOfPath.get(s.path) ?? ""})),
];
// the push channels, from the *.sapc.xml objects, on the same principle: a
// page opens ws://host<path> and the worker drives that handler
const channels = apcChannels(root, {roots})
  .map((c) => ({path: c.path, handler: c.handler, name: c.name, text: c.description ?? "", pack: packOfPath.get(c.path) ?? ""}));
await writeFile(resolve(generated, "services.mjs"),
  "// Generated by scripts/build-preview.mjs. Do not edit.\n"
  + `export const services = ${JSON.stringify(table, undefined, 2)};\n`
  + `export const channels = ${JSON.stringify(channels, undefined, 2)};\n`, "utf8");
console.log(`Services: ${table.map((s) => s.path).join(", ")}`);
console.log(`Channels: ${channels.length === 0 ? "(none)" : channels.map((c) => c.path).join(", ")}`);

// The half of the status snapshot only the build knows.
//
// In the browser there is no facade to take the snapshot: no pool, no
// listeners, no /proc. What ZOSD_STATUS_SRV still has to say about a
// deployment is the system id, the OData services registered in it and the
// packs layered into it, and all three are facts of the build. The worker
// fills in the rest -- the host kind, the one "process", the generation it
// is answering with and the clock -- and posts the whole thing to
// ZCL_OSD_STATUS=>REFRESH (web/preview-backend.mjs, docs/status-service.md
// "On the browser deployment"). The shape is the contract in
// tools/osd-status.mjs; these are rows of it, not a shape of their own.
// the OData services and the UI5 applications: the two kinds of row the
// worker cannot derive for itself, and both are what the Easy Access menu
// (src/webgui/) reads out of the status tables
const odata = facadeServices.filter((s) => s.kind === "ODATA" || s.kind === "APP");
const packRows = packsInfo(root);
await writeFile(resolve(generated, "status.mjs"),
  "// Generated by scripts/build-preview.mjs. Do not edit.\n"
  + `export const sid = ${JSON.stringify(String(process.env.STG_ADT_SID ?? "OSG"))};\n`
  + `export const odata = ${JSON.stringify(odata, undefined, 2)};\n`
  + `export const packs = ${JSON.stringify(packRows, undefined, 2)};\n`, "utf8");
console.log(`Status: ${odata.filter((s) => s.kind === "ODATA").length} OData services, ${odata.filter((s) => s.kind === "APP").length} apps, ${packRows.length} packs`);

// The page-side websocket shim, as source the worker can inline.
//
// Not a <script src> and not a module. A module script is deferred by
// specification: it runs after the document is parsed, which is after the
// page's own inline script has already called new WebSocket( ) and failed.
// The shim has to be a classic script, inline, so it runs the moment the
// parser reaches it and before anything below it. So the build turns the
// module into a plain script and the worker pastes it in.
const shimSource = (await readFile(resolve(root, "web/preview-socket.mjs"), "utf8"))
  .replace(/^export /gm, "");
await writeFile(resolve(generated, "socket-shim.mjs"),
  "// Generated by scripts/build-preview.mjs. Do not edit.\n"
  + `export const shim = ${JSON.stringify(shimSource)};\n`, "utf8");
const require = createRequire(import.meta.url);
const webpack = require("webpack");
const configuration = require(resolve(root, "webpack.config.cjs"));
const statistics = await new Promise((fulfil, reject) => {
  webpack(configuration, (error, result) => {
    if (error) {
      reject(error);
    } else if (result.hasErrors()) {
      reject(new Error(result.toString({colors: false, errorDetails: true})));
    } else {
      fulfil(result);
    }
  });
});
console.log(statistics.toString({colors: false, preset: "minimal"}));

// The bundle's own identity, written into the bundle.
//
// A suite that passes against a stale build/sw.js, a deployment verified by
// the command exiting 0, a fix confirmed by grepping for a comment the
// bundler strips — three of those in one day, all the same shape: the check
// and the thing checked were not the same object. The file on disk being
// right says nothing about which worker controls a page, because a
// registration outlives a rebuild.
//
// So the worker carries a digest of itself and serves it. The digest is
// taken before the stamp is substituted, which makes it well defined: it is
// what webpack emitted. build.json holds the same value for whoever wants to
// compare from outside.
const workerPath = resolve(build, "sw.js");
const emitted = await readFile(workerPath, "utf8");
const PLACEHOLDER = "__OSD_BUILD_STAMP__";
if (emitted.includes(PLACEHOLDER) === false) {
  throw new Error(`${PLACEHOLDER} is not in the bundle: web/preview-worker.mjs must carry it`);
}
const stamp = createHash("sha256").update(emitted).digest("hex").slice(0, 16);
await writeFile(workerPath, emitted.replaceAll(PLACEHOLDER, stamp), "utf8");
await writeFile(resolve(build, "build.json"),
  JSON.stringify({stamp, buildId, builtAt: new Date().toISOString()}, undefined, 2) + "\n", "utf8");
console.log(`Stamp: ${stamp}`);

await mkdir(build, {recursive: true});
await copyFile(resolve(root, "web/index.html"), resolve(build, "index.html"));

// the app: copied as is, except index.html makes sure the worker controls the
// page before UI5 boots (a deep link into app/ must work without going
// through the root page first)
async function copyTree(from, to) {
  await mkdir(to, {recursive: true});
  for (const entry of await readdir(from)) {
    const source = join(from, entry);
    if ((await stat(source)).isDirectory()) {
      await copyTree(source, join(to, entry));
    } else {
      await copyFile(source, join(to, entry));
    }
  }
}
await copyTree(resolve(root, "webapp"), resolve(build, "app"));
// a pack's page under app/<name>/, and the tiles the packs ask for as the
// file the launchpad fetches (test/start.mjs answers the same JSON live)
for (const pack of webappsOf(root)) {
  await copyTree(pack.dir, resolve(build, "app", pack.name));
}
await writeFile(resolve(build, "app", "packs.json"), JSON.stringify({tiles: tilesOf(root)}, undefined, 2) + "\n", "utf8");
// the two entry pages: the Travels app alone, and the launchpad sandbox with
// both apps; each boots UI5 only once the worker answers
for (const page of ["index.html", "flp.html"]) {
  await deferBootstrap(page);
}

async function deferBootstrap(page) {
const index = await readFile(resolve(root, "webapp", page), "utf8");
const bootstrap = /<script id="sap-ui-bootstrap"[\s\S]*?<\/script>/.exec(index);
if (bootstrap === null) {
  throw new Error(`webapp/${page}: sap-ui-bootstrap script not found`);
}
// the bootstrap tag's attributes, set on a script element the loader creates
// once the worker controls the page (the tag itself must not appear inside a
// script: "</script>" would end it)
const attributes = {};
for (const m of bootstrap[0].replace(/^<script /, "").matchAll(/([\w-]+)="([^"]*)"|([\w-]+)='([^']*)'/g)) {
  attributes[m[1] ?? m[3]] = m[2] ?? m[4];
}
const loader = `<script>
    // preview deployment: the OData service is answered by a service worker,
    // so it has to control this page before UI5 asks for $metadata. When it
    // cannot, say so instead of booting into a blank list report.
    (async () => {
      const explain = (title, detail) => {
        document.body.innerHTML = "";
        const main = document.createElement("main");
        main.style.cssText = "max-width:40rem;margin:3rem auto;padding:0 1rem;font:16px/1.5 system-ui,sans-serif";
        const h = document.createElement("h1");
        h.style.fontSize = "1.3rem";
        h.textContent = title;
        const p = document.createElement("pre");
        p.style.whiteSpace = "pre-wrap";
        p.textContent = detail;
        const a = document.createElement("p");
        a.innerHTML = 'The gateway runs in a service worker. <a href="../">Install it again</a>, try another browser, or check that service workers and site data are allowed for this site.';
        main.append(h, p, a);
        document.body.append(main);
      };
      if (!("serviceWorker" in navigator)) {
        explain("This browser cannot run the preview", "navigator.serviceWorker is not available (private window, or service workers turned off).");
        return;
      }
      if (!navigator.serviceWorker.controller) {
        try {
          await navigator.serviceWorker.register("../sw.js", {scope: "../"});
          await navigator.serviceWorker.ready;
          // clients.claim() in the worker makes this page controlled a moment
          // after ready; the event for it may already have fired, so poll
          for (let waited = 0; !navigator.serviceWorker.controller && waited < 5000; waited += 100) {
            await new Promise((tick) => setTimeout(tick, 100));
          }
          if (!navigator.serviceWorker.controller) {
            // a navigation after the registration is controlled for sure; once
            const key = "stg-preview-reload";
            if (!sessionStorage.getItem(key)) {
              sessionStorage.setItem(key, "1");
              location.reload();
              return;
            }
            sessionStorage.removeItem(key);
            throw new Error("the service worker was installed but does not control this page");
          }
        } catch (error) {
          explain("The preview could not start", String(error && error.stack || error));
          return;
        }
      }
      // one round trip before UI5: the worker must be the one answering
      try {
        const probe = await fetch("../sap/opu/odata/sap/ZSTG_DEMO_SRV/", {headers: {accept: "application/json"}});
        if (!probe.ok) {
          explain("The gateway did not answer", "GET ../sap/opu/odata/sap/ZSTG_DEMO_SRV/ returned " + probe.status + "\\n\\n" + (await probe.text()).slice(0, 2000));
          return;
        }
      } catch (error) {
        explain("The gateway did not answer", String(error));
        return;
      }
      const boot = document.createElement("script");
      const attributes = ${JSON.stringify(attributes)};
      for (const name of Object.keys(attributes)) {
        boot.setAttribute(name, attributes[name]);
      }
      document.head.appendChild(boot);
    })();
  </script>`;
await writeFile(resolve(build, "app", page), index.replace(bootstrap[0], loader), "utf8");
}
await copyFile(resolve(root, "web/preview-socket.mjs"), resolve(build, "preview-socket.mjs"));

// The SMW0 media, beside the bundle.
//
// Each transpiled W3MI object names one file, which the transpiler wrote next
// to the module; in the browser web/preview-backend.mjs fetches it from here
// instead of reading it. Copied rather than bundled: twelve megabytes of
// pictures and audio inside sw.js would be downloaded by every visitor before
// the first request, and out here they are downloaded by the page that asks.
const media = resolve(build, "media");
await mkdir(media, {recursive: true});
let carried = 0;
let bytes = 0;
for (const entry of await readdir(resolve(root, "output"))) {
  if (/\.w3mi\.data\./.test(entry) === false) {
    continue;
  }
  const source = resolve(root, "output", entry);
  await copyFile(source, join(media, entry));
  bytes += (await stat(source)).size;
  carried += 1;
}
console.log(`Media: ${carried} W3MI objects, ${(bytes / 1048576).toFixed(1)} MB in media/`);

console.log(`Preview build is in ${build}`);
