CLASS cl_abap_daemon_ext_base DEFINITION PUBLIC ABSTRACT CREATE PUBLIC.
  PUBLIC SECTION.
    INTERFACES if_abap_daemon_extension ALL METHODS ABSTRACT.
ENDCLASS.
CLASS cl_abap_daemon_ext_base IMPLEMENTATION.
ENDCLASS.
