// Seamless AMDP: rewrite what the transpiler cannot run into a call it can.
//
// The transpiler stops dead on an AMDP body -- `Statement NativeSQL not
// supported` -- because the body is SQLScript, not ABAP. So before it sees
// the class, the body is taken out and replaced by a routed call:
//
//   METHOD calculate_squares.
//     CALL FUNCTION 'Z_AMDP_1A2B3C4D' DESTINATION 'AMDP'
//       EXPORTING iv_count = iv_count IMPORTING et_result = et_result.
//   ENDMETHOD.
//
// which the transpiler emits as `abap.statements.callFunction({name, destination,
// exporting, importing})`, and which the runtime hands to
// `abap.context.RFCDestinations["AMDP"]` -- the same contract
// tools/rfc-replay.mjs already implements for captured RFC. The SQLScript is
// put aside for deployment into HANA.
//
// **The source in src/ is not touched.** It stays the AMDP it is and still
// compiles on a real system; only the copy handed to the transpiler is
// rewritten, into gen/amdp/, which wins the name by the input-folder order
// (CLAUDE.md, backlog E.1). That is what cds2ddic, stg-compile and segw-gen
// all do already.
//
//   node tools/amdp-gen.mjs [--list] [--out gen/amdp]
import {readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, rmSync} from "node:fs";
import {join, basename, dirname} from "node:path";
import {createHash} from "node:crypto";
import {extract, parameterType} from "./amdp-extract.mjs";
import {contentFoldersOf} from "./osd-packs.mjs";
import {compileProcedure} from "./sqlscript-to-procedure-ir.mjs";
import {ObjectStore} from "./osd-store.mjs";
import {ddicCatalogue} from "./sqlscript-ddic-catalogue.mjs";
import {parseTableFunction} from "./sqlscript/table-function-ddls.mjs";
import {resolveType} from "./osd-type-graph.mjs";

const DEFAULT_OUT = "gen/amdp";

/** the function module that stands in for one AMDP method.
 *  ABAP names are at most 30 characters and a class plus a method is easily
 *  more, so the name is a hash: short, stable, and unique per method. */
export function moduleName(cls, method) {
  return "Z_AMDP_" + createHash("sha1").update(`${cls}=>${method}`.toUpperCase()).digest("hex").slice(0, 8).toUpperCase();
}

/** every *.clas.abap under the folders, with its xml beside it */
function classFiles(folders) {
  const out = [];
  const walk = (dir) => {
    if (!existsSync(dir)) return;
    for (const e of readdirSync(dir, {withFileTypes: true})) {
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (/\.clas\.abap$/i.test(e.name) && !/\.testclasses\./i.test(e.name)) out.push(p);
    }
  };
  for (const f of folders) walk(f);
  return out;
}

/** the type sources a class may need: every interface beside it */
function typeSources(folders) {
  const out = [];
  const walk = (dir) => {
    if (!existsSync(dir)) return;
    for (const e of readdirSync(dir, {withFileTypes: true})) {
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (/\.intf\.abap$/i.test(e.name)) out.push(readFileSync(p, "utf8"));
    }
  };
  for (const f of folders) walk(f);
  return out;
}

/** the ABAP of one rewritten method */
function rewrittenMethod(cls, m) {
  const fm = moduleName(cls, m.name);
  const byDirection = (d) => m.parameters.filter((p) => p.direction === d);
  const returning = m.parameters.find((p) => p.direction === "RETURNING");
  const clause = (keyword, list) => (list.length === 0 ? "" :
    `\n      ${keyword}\n` + list.map((p) => `        ${p.name.toLowerCase().padEnd(24)} = ${p.name.toLowerCase()}`).join("\n"));
  return `  METHOD ${m.name}.
* Generated by tools/amdp-gen.mjs -- do not edit. The body of this method is
* SQLScript and runs in HANA; what stands here is the call that reaches it.
* The original is ${cls}=>${m.name} in src/.
    CALL FUNCTION '${fm}' DESTINATION 'AMDP'${clause("EXPORTING", byDirection("IN"))}${clause("IMPORTING", returning === undefined ? byDirection("OUT") : [...byDirection("OUT"), returning])}${clause("CHANGING", byDirection("INOUT"))}.
  ENDMETHOD.`;
}

/** the class with every AMDP body replaced */
export function rewriteClass(source, parsed) {
  let out = source;
  for (const m of parsed.methods) {
    const start = out.search(new RegExp(`^\\s*METHOD\\s+${m.name}\\s+BY\\s+DATABASE`, "im"));
    if (start === -1) continue;
    const end = out.toUpperCase().indexOf("ENDMETHOD.", start) + "ENDMETHOD.".length;
    out = out.slice(0, start) + rewrittenMethod(parsed.className, m) + out.slice(end);
  }
  return out;
}

const xmlEscape = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/** the function group that carries the signatures the transpiler needs */
function functionGroup(group, entries) {
  const items = entries.map(({cls, m, fm}) => {
    const of = (d) => m.parameters.filter((p) => p.direction === d);
    const returning = m.parameters.find((p) => p.direction === "RETURNING");
    const rs = (tag, list, param) => (list.length === 0 ? "" :
      `\n     <${tag}>\n` + list.map((p) =>
        `      <${param}><PARAMETER>${p.name.toUpperCase()}</PARAMETER><TYP>${xmlEscape(abapTypeFor(cls, p))}</TYP></${param}>`).join("\n") + `\n     </${tag}>`);
    return `    <item>
     <FUNCNAME>${fm}</FUNCNAME>
     <SHORT_TEXT>AMDP ${cls}=&gt;${m.name}</SHORT_TEXT>${rs("IMPORT", of("IN"), "RSIMP")}${rs("EXPORT", returning === undefined ? of("OUT") : [...of("OUT"), returning], "RSEXP")}${rs("CHANGING", of("INOUT"), "RSCHA")}
    </item>`;
  }).join("\n");
  return `<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_FUGR" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0">
  <asx:values>
   <AREAT>AMDP bridge: the signatures of ${entries[0].cls}</AREAT>
   <INCLUDES>
    <SOBJ_NAME>L${group.toUpperCase()}TOP</SOBJ_NAME>
    <SOBJ_NAME>SAPL${group.toUpperCase()}</SOBJ_NAME>
   </INCLUDES>
   <FUNCTIONS>
${items}
   </FUNCTIONS>
  </asx:values>
 </asx:abap>
</abapGit>
`;
}

/** how a parameter is typed in the function module. A class-local type is
 *  named the way ABAP names it, which abaplint resolves and the transpiler
 *  builds the right structure for -- checked 2026-09-18. */
function abapTypeFor(cls, p) {
  const t = String(p.abapType);
  return /^[a-z_0-9]+$/i.test(t) && !/^(i|f|d|t|string|xstring|int8|int4|int2|int1|abap_bool)$/i.test(t)
    ? `${cls.toUpperCase()}=>${t.toUpperCase()}`
    : t.toUpperCase();
}

const progXml = (name) => `<?xml version="1.0" encoding="utf-8"?>
<abapGit version="v1.0.0" serializer="LCL_OBJECT_FUGR" serializer_version="v1.0.0">
 <asx:abap xmlns:asx="http://www.sap.com/abapxml" version="1.0"><asx:values><PROGDIR><NAME>${name.toUpperCase()}</NAME><SUBC>I</SUBC></PROGDIR></asx:values></asx:abap>
</abapGit>
`;

export function generate(folders, out = DEFAULT_OUT, options = {}) {
  const extras = typeSources(folders);
  // the runtime's object store; a test hands one over a fixture root
  const store = options.store ?? new ObjectStore({root: process.cwd()});
  const procedures = [];
  const written = [];
  rmSync(out, {recursive: true, force: true});

  for (const file of classFiles(folders)) {
    const source = readFileSync(file, "utf8");
    if (!/BY\s+DATABASE\s+(PROCEDURE|FUNCTION)/i.test(source)) continue;
    const parsed = extract(source, basename(file), extras);
    if (parsed.methods.length === 0) continue;

    const cls = parsed.className;
    const unmapped = parsed.methods.flatMap((m) => m.parameters
      .filter((p) => parameterType(p.abapType, parsed.types) === undefined)
      .map((p) => `${m.name}.${p.name} (${p.abapType})`));
    if (unmapped.length > 0) {
      throw new Error(`amdp-gen: ${cls} has parameters with no HANA type: ${unmapped.join(", ")}`);
    }

    mkdirSync(out, {recursive: true});
    writeFileSync(join(out, basename(file)), rewriteClass(source, parsed));
    const xml = file.replace(/\.clas\.abap$/i, ".clas.xml");
    if (existsSync(xml)) writeFileSync(join(out, basename(xml)), readFileSync(xml, "utf8"));
    written.push(basename(file));

    const group = ("ZAMDP_" + cls.replace(/^ZCL_/i, "")).slice(0, 26).toUpperCase();
    const entries = parsed.methods.map((m) => ({cls, m, fm: moduleName(cls, m.name)}));
    writeFileSync(join(out, `${group.toLowerCase()}.fugr.xml`), functionGroup(group, entries));
    writeFileSync(join(out, `${group.toLowerCase()}.fugr.l${group.toLowerCase()}top.abap`), `FUNCTION-POOL ${group.toLowerCase()}.\n`);
    writeFileSync(join(out, `${group.toLowerCase()}.fugr.l${group.toLowerCase()}top.xml`), progXml(`L${group}TOP`));
    writeFileSync(join(out, `${group.toLowerCase()}.fugr.sapl${group.toLowerCase()}.abap`),
      `INCLUDE l${group.toLowerCase()}top.\nINCLUDE l${group.toLowerCase()}uxx.\n`);
    writeFileSync(join(out, `${group.toLowerCase()}.fugr.sapl${group.toLowerCase()}.xml`), progXml(`SAPL${group}`));
    for (const {m, fm} of entries) {
      writeFileSync(join(out, `${group.toLowerCase()}.fugr.${fm.toLowerCase()}.abap`),
        `FUNCTION ${fm.toLowerCase()}.\n* never runs: DESTINATION 'AMDP' routes the call to HANA before it gets here\n  RAISE EXCEPTION TYPE cx_sy_dyn_call_illegal_func.\nENDFUNCTION.\n`);
      // Compile the portable form while the extractor's full local type map
      // is still present. The runtime artefact deliberately carries IR, not
      // a parser: a normal application process should not have to load the
      // SQLScript frontend merely because one AMDP method is called. A
      // method outside the measured subset remains deployable on HANA and
      // carries its exact portable refusal beside it.
      let portable;
      let portableRefusal;
      try {
        // USING is the AMDP declaration of database objects this body may
        // read.  Carry only those schemas: a procedure must not silently
        // acquire access to the entire system catalogue, and the generated
        // browser artefact should not contain a system-sized DDIC dump.
        // the store also types a table parameter declared by the dictionary
        // (TTYP -> TABL), under the compiler's measured datatype gate
        // a method FOR TABLE FUNCTION takes its parameters and output from
        // the DDLS it names, read through the same store; a DDLS that is not
        // in the tree leaves the method as it was (refused by the compiler)
        let method = m;
        if (m.tableFunction !== undefined) {
          let ddls;
          try { ddls = store.read("DDLS", m.tableFunction)?.source; } catch { ddls = undefined; }
          const tf = ddls === undefined ? undefined : parseTableFunction(ddls);
          if (tf !== undefined) method = {...m, parameters: tf.parameters, returns: tf.returns};
        }
        const resolveElement = (name) => {
          const found = resolveType(store, name);
          return found.KIND === "DTEL" && found.DATATYPE !== "" ? found : undefined;
        };
        portable = compileProcedure(method, parsed.types, {catalogue: ddicCatalogue(store, m.usings), store, resolveType: resolveElement});
      } catch (error) {
        portableRefusal = {
          code: error?.code ?? "UNSUPPORTED_SQLSCRIPT",
          message: String(error?.message ?? error),
        };
      }
      procedures.push({
        module: fm,
        class: cls,
        method: m.name,
        kind: m.dbKind === "FUNCTION" ? "function" : "procedure",
        readOnly: m.readOnly === true,
        language: m.language || "SQLSCRIPT",
        parameters: m.parameters.map((p) => ({
          name: p.name.toLowerCase(), direction: p.direction,
          abapType: p.abapType, hanaType: parameterType(p.abapType, parsed.types),
        })),
        body: m.body,
        hash: createHash("sha1").update(m.body).digest("hex").slice(0, 16),
        ...(portable === undefined ? {portableRefusal} : {portable}),
      });
    }
  }

  if (procedures.length > 0) {
    mkdirSync(out, {recursive: true});
    writeFileSync(join(out, "procedures.json"), JSON.stringify({procedures}, undefined, 2) + "\n");
  }
  return {classes: written, procedures};
}

if (basename(process.argv[1] ?? "") === "amdp-gen.mjs") {
  const args = process.argv.slice(2);
  const out = args.includes("--out") ? args[args.indexOf("--out") + 1] : DEFAULT_OUT;
  // Content, not the layer list. A generator that reads every input folder
  // picks up test fixtures and puts them in the build -- CLAUDE.md records
  // that happening once already, with a CDS fixture under test/.
  const folders = contentFoldersOf(process.cwd());
  const result = generate(folders, out);
  if (result.procedures.length === 0) {
    console.log("amdp-gen: no AMDP methods found");
  } else {
    console.log(`amdp-gen: ${result.procedures.length} AMDP method(s) in ${result.classes.length} class(es) -> ${out}`);
    for (const p of result.procedures) console.log(`  ${p.module}  ${p.class}=>${p.method}  ${p.kind}  ${p.parameters.length} parameter(s)  body ${p.body.split("\n").length} lines`);
  }
}
