#!/usr/bin/env node
// Search help objects -> the search help registry.
//
// A SEGW operation mapped to a search help asks the runtime by name
// (/iwbep/cl_sb_shlp_data_factory). abapGit serializes the search help as
// <name>.shlp.xml: DD30V (selection method SELMETHOD, exit SELMEXIT, text
// table TEXTTAB, ISSIMPLE) and DD32P (the parameters: FIELDNAME, SHLPINPUT,
// SHLPOUTPUT, SHLPLISPOS, SHLPSELPOS). Reading them is what lets a cloned
// repository serve its own value helps: nothing registered by hand.
//
// Output: gen/segw/zcl_stg_shlp_registry.clas.abap with one register() that
// builds a zcl_oao_shlp_ddic per elementary search help and registers it.
// Collective search helps (DD31S, no ISSIMPLE) are listed as not registered.
import {readdirSync, readFileSync, statSync, writeFileSync, mkdirSync} from "node:fs";
import {join} from "node:path";

const OUT = "gen/segw";

function tag(xml, name) {
  const m = new RegExp(`<${name}>([^<]*)</${name}>`).exec(xml);
  return m ? m[1].trim() : "";
}

function walk(dir, out = []) {
  let entries = [];
  try {
    entries = readdirSync(dir).sort();
  } catch {
    return out;
  }
  for (const entry of entries) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (entry === "node_modules" || entry.startsWith(".")) {
        continue;
      }
      walk(full, out);
    } else if (/\.shlp\.xml$/i.test(entry)) {
      out.push(full);
    }
  }
  return out;
}

/** one search help as its XML defines it */
export function parseSearchHelp(xml, file) {
  const head = /<DD30V>[\s\S]*?<\/DD30V>/.exec(xml)?.[0] ?? xml;
  const parameters = [];
  for (const m of xml.matchAll(/<DD32P>([\s\S]*?)<\/DD32P>/g)) {
    const p = m[1];
    parameters.push({
      name: tag(p, "FIELDNAME"),
      rollname: tag(p, "ROLLNAME"),
      input: tag(p, "SHLPINPUT") === "X",
      output: tag(p, "SHLPOUTPUT") === "X",
      listPosition: parseInt(tag(p, "SHLPLISPOS") || "0", 10),
      selectPosition: parseInt(tag(p, "SHLPSELPOS") || "0", 10),
    });
  }
  return {
    name: tag(head, "SHLPNAME"),
    description: tag(head, "DDTEXT"),
    simple: tag(head, "ISSIMPLE") === "X",
    selmethod: tag(head, "SELMETHOD"),
    selmexit: tag(head, "SELMEXIT"),
    texttab: tag(head, "TEXTTAB"),
    collective: /<DD31S>/.test(xml),
    parameters,
    file,
  };
}

/** the search helps found below the folders */
export function searchHelps(folders) {
  const out = [];
  for (const folder of folders) {
    for (const file of walk(folder)) {
      out.push(parseSearchHelp(readFileSync(file, "utf8"), file));
    }
  }
  return out.sort((a, b) => a.name.localeCompare(b.name));
}

const q = (s) => "'" + s.replace(/'/g, "''") + "'";
const bool = (b) => (b ? "abap_true" : "abap_false");

export function shlpRegistryClass(helps) {
  const blocks = [];
  let registered = 0;
  for (const h of helps) {
    if (h.collective || !h.simple) {
      blocks.push(`* ${h.name}: collective search help, not registered (elementary ones only)`);
      continue;
    }
    if (h.selmethod === "" && h.selmexit === "") {
      blocks.push(`* ${h.name}: no selection method and no exit, not registered`);
      continue;
    }
    registered++;
    const lines = [`* ${h.name}: ${h.description || "search help"}`];
    const opts = [`iv_shlp_name = ${q(h.name)}`];
    if (h.selmethod !== "") {
      opts.push(`iv_selmethod = ${q(h.selmethod)}`);
    }
    if (h.selmexit !== "") {
      opts.push(`iv_selmexit  = ${q(h.selmexit)}`);
    }
    if (h.texttab !== "") {
      opts.push(`iv_texttab   = ${q(h.texttab)}`);
    }
    const pad = " ".repeat("    lo_shlp = zcl_oao_shlp_ddic=>create( ".length);
    lines.push(`    lo_shlp = zcl_oao_shlp_ddic=>create( ${opts.join("\n" + pad)} ).`);
    const ppad = " ".repeat("    lo_shlp->add_parameter( ".length);
    for (const p of h.parameters) {
      lines.push(`    lo_shlp->add_parameter( iv_name            = ${q(p.name)}
${ppad}iv_input           = ${bool(p.input)}
${ppad}iv_output          = ${bool(p.output)}
${ppad}iv_list_position   = ${p.listPosition}
${ppad}iv_select_position = ${p.selectPosition} ).`);
    }
    lines.push("    lo_shlp->register( ).");
    blocks.push(lines.join("\n"));
  }
  const body = registered > 0
    ? `    DATA lo_shlp TYPE REF TO zcl_oao_shlp_ddic.\n\n${blocks.join("\n\n")}`
    : `${blocks.length > 0 ? blocks.join("\n") + "\n" : ""}    RETURN.`;
  return `CLASS zcl_stg_shlp_registry DEFINITION PUBLIC CREATE PUBLIC.
* generated by tools/segw-shlp.mjs from the search help objects - do not edit
  PUBLIC SECTION.
    CLASS-METHODS register.
ENDCLASS.

CLASS zcl_stg_shlp_registry IMPLEMENTATION.

  METHOD register.
${body}
  ENDMETHOD.

ENDCLASS.
`;
}

if (process.argv[1] && /segw-shlp\.mjs$/.test(process.argv[1])) {
  const folders = process.argv.slice(2).filter((a) => !a.startsWith("--"));
  const list = process.argv.includes("--list");
  const helps = searchHelps(folders.length > 0 ? folders : ["src", "gen"]);
  for (const h of helps) {
    const how = h.collective || !h.simple ? "collective, skipped" : h.selmethod ? "table " + h.selmethod : h.selmexit ? "exit " + h.selmexit : "no source";
    console.log(`segw-shlp: ${h.name} -> ${how}, ${h.parameters.length} parameters${h.description ? " (" + h.description + ")" : ""}`);
  }
  if (!list) {
    mkdirSync(OUT, {recursive: true});
    writeFileSync(join(OUT, "zcl_stg_shlp_registry.clas.abap"), shlpRegistryClass(helps));
  }
}
