* Generated by wasm/osd_unit_test.go. Expected values come from wazero.
CLASS ltcl_wasm DEFINITION FINAL FOR TESTING
  DURATION SHORT RISK LEVEL HARMLESS.
  PRIVATE SECTION.
    METHODS c1 FOR TESTING.
    METHODS c2 FOR TESTING.
    METHODS c3 FOR TESTING.
    METHODS c4 FOR TESTING.
    METHODS c5 FOR TESTING.
    METHODS c6 FOR TESTING.
    METHODS c7 FOR TESTING.
ENDCLASS.

CLASS ltcl_wasm IMPLEMENTATION.
  METHOD c1.
    DATA lo TYPE REF TO zcl_abapiti_factorial.
    DATA lv_act TYPE i.
    DATA lv_exp TYPE i.
    CREATE OBJECT lo.
    lv_act = lo->factorial( p0 = 0 ).
    lv_exp = 1.
    cl_abap_unit_assert=>assert_equals( act = lv_act exp = lv_exp msg = 'factorial(0)' ).
  ENDMETHOD.
  METHOD c2.
    DATA lo TYPE REF TO zcl_abapiti_factorial.
    DATA lv_act TYPE i.
    DATA lv_exp TYPE i.
    CREATE OBJECT lo.
    lv_act = lo->factorial( p0 = 1 ).
    lv_exp = 1.
    cl_abap_unit_assert=>assert_equals( act = lv_act exp = lv_exp msg = 'factorial(1)' ).
  ENDMETHOD.
  METHOD c3.
    DATA lo TYPE REF TO zcl_abapiti_factorial.
    DATA lv_act TYPE i.
    DATA lv_exp TYPE i.
    CREATE OBJECT lo.
    lv_act = lo->factorial( p0 = 5 ).
    lv_exp = 120.
    cl_abap_unit_assert=>assert_equals( act = lv_act exp = lv_exp msg = 'factorial(5)' ).
  ENDMETHOD.
  METHOD c4.
    DATA lo TYPE REF TO zcl_abapiti_factorial.
    DATA lv_act TYPE i.
    DATA lv_exp TYPE i.
    CREATE OBJECT lo.
    lv_act = lo->factorial( p0 = 10 ).
    lv_exp = 3628800.
    cl_abap_unit_assert=>assert_equals( act = lv_act exp = lv_exp msg = 'factorial(10)' ).
  ENDMETHOD.
  METHOD c5.
    DATA lo TYPE REF TO zcl_abapiti_factorial.
    DATA lv_act TYPE i.
    DATA lv_exp TYPE i.
    CREATE OBJECT lo.
    lv_act = lo->factorial( p0 = 12 ).
    lv_exp = 479001600.
    cl_abap_unit_assert=>assert_equals( act = lv_act exp = lv_exp msg = 'factorial(12)' ).
  ENDMETHOD.
  METHOD c6.
    DATA lo TYPE REF TO zcl_abapiti_factorial.
    DATA lv_act TYPE i.
    DATA lv_exp TYPE i.
    CREATE OBJECT lo.
    lv_act = lo->factorial( p0 = 13 ).
    lv_exp = 1932053504.
    cl_abap_unit_assert=>assert_equals( act = lv_act exp = lv_exp msg = 'factorial(13)' ).
  ENDMETHOD.
  METHOD c7.
    DATA lo TYPE REF TO zcl_abapiti_factorial.
    DATA lv_act TYPE i.
    DATA lv_exp TYPE i.
    CREATE OBJECT lo.
    lv_act = lo->factorial( p0 = 20 ).
    lv_exp = -2102132736.
    cl_abap_unit_assert=>assert_equals( act = lv_act exp = lv_exp msg = 'factorial(20)' ).
  ENDMETHOD.
ENDCLASS.
