CLASS ltcl_recorder DEFINITION FOR TESTING DURATION SHORT RISK LEVEL HARMLESS FINAL.
  PRIVATE SECTION.
    METHODS same_as_contract FOR TESTING RAISING cx_static_check.
    METHODS recorded
      RETURNING VALUE(rv) TYPE string.
ENDCLASS.

CLASS ltcl_recorder IMPLEMENTATION.

  METHOD same_as_contract.
    DATA lo_contract TYPE REF TO zcl_osd_sxml_contract.
    DATA li_factory TYPE REF TO zif_osd_sxml_factory.
    DATA lv_exp TYPE string.
    DATA lt_fixtures TYPE zcl_osd_sxml_contract=>ty_fixtures.
* a fixture that DUMPS the pinned fork ends the run; the recorder here leaves
* it out too (on A4H it is in)
    lt_fixtures = zcl_osd_sxml_fixtures=>all( ).
    DELETE lt_fixtures WHERE fork = `DUMPS`.
    CREATE OBJECT li_factory TYPE zcl_osd_sxml_factory_concat.
    CREATE OBJECT lo_contract EXPORTING ii_factory = li_factory.
    lv_exp = `SXML<<` && lo_contract->record( lt_fixtures ) && `>>SXML`.
    cl_abap_unit_assert=>assert_equals( act = recorded( )
                                        exp = lv_exp ).
  ENDMETHOD.

  METHOD recorded.
* sXML contract recorder. GENERATED by tools/osd-sxml-contract.mjs from
* test/fixtures/sxml-contract/cases.json. Runs CL_SXML_STRING_READER over
* every fixture with NEXT_NODE / NEXT_ATTRIBUTE and prints the events in
* the normalisation stated in ZCL_OSD_SXML_CONTRACT (whose RECORD method
* gives the same text; test/unit/zcl_osd_sxml_recorder_test proves it).
* Run it through execute_abap; the report is the alert title, framed
* SXML<< ... >>SXML. Save that text to a file and import it with
*   node tools/osd-sxml-contract.mjs import <file> --date YYYY-MM-DD
* If the title is cut (no >>SXML), print a recorder for fewer fixtures:
*   node tools/osd-sxml-contract.mjs recorder --only a,b,c
    TYPES: BEGIN OF ty_ev,
             kw TYPE string,
             n  TYPE i,
             f1 TYPE string,
             f2 TYPE string,
             f3 TYPE string,
           END OF ty_ev.
    DATA lt_names TYPE string_table.
    DATA lt_hex TYPE string_table.
    DATA lv_hex TYPE string.
    DATA lv_name TYPE string.
    DATA lv_x TYPE xstring.
    DATA lv_out TYPE string.
    DATA li_reader TYPE REF TO if_sxml_reader.
    DATA lx_error TYPE REF TO cx_root.
    DATA lx_parse TYPE REF TO cx_sxml_parse_error.
    DATA lt_ev TYPE STANDARD TABLE OF ty_ev WITH DEFAULT KEY.
    DATA ls_ev TYPE ty_ev.
    DATA lv_field TYPE string.
    DATA lv_esc TYPE string.
    DATA lv_line TYPE string.
    DATA lv_len TYPE i.
    DATA lv_pos TYPE i.
    DATA lv_c TYPE c LENGTH 1.
    DATA lv_code TYPE x LENGTH 2.
    DATA lv_code_hex TYPE string.
    DATA lv_class TYPE string.
    DATA lv_offset TYPE string.
    DATA lv_index TYPE i.
    DATA lv_done TYPE abap_bool.
    DATA lv_plain TYPE string.
    lv_plain = ` !#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_``abcdefghijklmnopqrstuvwxyz{}~`.
    lv_hex = `7B7D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_empty_object` TO lt_names.
    lv_hex = `5B5D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_empty_array` TO lt_names.
    lv_hex = `32`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_simple_integer` TO lt_names.
    lv_hex = `74727565`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_simple_true` TO lt_names.
    lv_hex = `6E756C6C`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_simple_null` TO lt_names.
    lv_hex = `5B325D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_integer_array` TO lt_names.
    lv_hex = `7B226B657931223A202276616C756531227D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_key_value` TO lt_names.
    lv_hex = `7B226B657931223A205B5D7D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_key_empty` TO lt_names.
    lv_hex = `7B22223A20317D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_empty_key` TO lt_names.
    lv_hex = `7B226B657931223A202276616C756531222C20226B657932223A202276616C756532227D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_two_keys` TO lt_names.
    lv_hex = `5B312C20325D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_two_array` TO lt_names.
    lv_hex = `5B7B226B6579223A202276616C7565227D5D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_array_with_object` TO lt_names.
    lv_hex = `7B226B6579223A207B22737562223A202276616C7565227D7D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_object_with_object` TO lt_names.
    lv_hex = `6D6F6F2C2068656C6C6F20776F726C64`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_bad` TO lt_names.
    lv_hex = `7B0A226F6B223A2022616263222C0A226572726F72220A7D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_bad_offset` TO lt_names.
    lv_hex = `7B22C3A9E282ACF09F9880223A2022C3A9E282ACF09F9880227D`.
    APPEND lv_hex TO lt_hex.
    APPEND `json_non_ascii` TO lt_names.
    lv_hex = `3C613E743C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_simple` TO lt_names.
    lv_hex = `3CC3A920C3A9783D2276223E743C2FC3A93E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_name_e_acute` TO lt_names.
    lv_hex = `3C61E282AC3E743C2F61E282AC3E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_name_euro` TO lt_names.
    lv_hex = `3C61F09F98802F3E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_name_astral` TO lt_names.
    lv_hex = `3C6120783D22C3A9E282ACF09F9880223EC3A9E282ACF09F98803C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_non_ascii_values` TO lt_names.
    lv_hex = `3C613E3C215B43444154415BC3A9E282ACF09F98805D5D3E3C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_non_ascii_cdata` TO lt_names.
    lv_hex = `3C613E3C212D2DC3A9E282ACF09F98802D2D3E743C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_non_ascii_comment` TO lt_names.
    lv_hex = `3C6120783D2226616D703B262378323041433B26233132383531323B223E26616D703B262378323041433B26233132383531323B266C743B2667743B2671756F743B2661706F733B3C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_entities` TO lt_names.
    lv_hex = `3C613E3C215B43444154415B785D5D795D5D5D3E3C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_cdata_brackets` TO lt_names.
    lv_hex = `3C613E313C212D2D20612D62202D20632D202D2D3E323C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_comment_dashes` TO lt_names.
    lv_hex = `3C3F786D6C2076657273696F6E3D22312E30223F3E3C3F706920646174613F3E3C613E3C3F696E6E657220783F3E743C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_pi` TO lt_names.
    lv_hex = `EFBBBF3C613E743C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_bom` TO lt_names.
    lv_hex = `3C7220786D6C6E733D2275726E3A642220786D6C6E733A703D2275726E3A70223E3C703A6320703A783D22312220793D2232223E743C2F703A633E3C642F3E3C2F723E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_namespaces` TO lt_names.
    lv_hex = `3C613E3C622F3E3C633E3C2F633E3C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_empty_elements` TO lt_names.
    lv_hex = `3C613E203C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_whitespace_only` TO lt_names.
    lv_hex = `3C613E0A20203C623E783C2F623E0A3C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_whitespace_between` TO lt_names.
    lv_hex = `3C613E61626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F9880`.
    lv_hex = lv_hex && `2061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061`.
    lv_hex = lv_hex && `626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F988020616263`.
    lv_hex = lv_hex && `20C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3`.
    lv_hex = lv_hex && `A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E2`.
    lv_hex = lv_hex && `82ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F98802061626320C3A9E282ACF09F9880203C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_long_text` TO lt_names.
    lv_hex = `3C3F786D6C2076657273696F6E3D22312E302220656E636F64696E673D227574662D38223F3E3C613EC3A93C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_decl_lowercase_utf8` TO lt_names.
    lv_hex = `3C613EF09F98803C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_astral_text` TO lt_names.
    lv_hex = `3C61C3A920783D22C3A9E282AC223EC3A9E282AC3C215B43444154415BC3A95D5D5D5D3E3C2F61C3A93E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_text_cdata_merged` TO lt_names.
    lv_hex = `3C613E3C212D2DFF2D2D3E3C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_ff_in_comment` TO lt_names.
    lv_hex = `3C613E3C623E743C2F623E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_unclosed` TO lt_names.
    lv_hex = `3C613E3C2F623E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_mismatched_close` TO lt_names.
    lv_hex = `3C613EC3A9E282AC3C2F623E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_mismatched_close_non_ascii` TO lt_names.
    lv_hex = `3C6120783D22C3A9C3A93C222F3E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_lt_in_attribute` TO lt_names.
    lv_hex = `3C613E785D5D3E793C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_cdata_end_in_text` TO lt_names.
    lv_hex = `3C613E26666F6F3B3C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_bad_entity` TO lt_names.
    lv_hex = `3C613E262378443830303B3C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_bad_charref` TO lt_names.
    lv_hex = `3C613E3C212D2D782D2D792D2D3E3C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_comment_double_dash` TO lt_names.
    lv_hex = ``.
    APPEND lv_hex TO lt_hex.
    APPEND `xml_empty_document` TO lt_names.
    lv_hex = `3C613E80613C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `utf8_lone_continuation` TO lt_names.
    lv_hex = `3C613EC0AF613C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `utf8_overlong` TO lt_names.
    lv_hex = `3C613EE282613C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `utf8_truncated_3` TO lt_names.
    lv_hex = `3C613EE2823C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `utf8_truncated_3_before_lt` TO lt_names.
    lv_hex = `3C613EF09F983C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `utf8_truncated_4_before_lt` TO lt_names.
    lv_hex = `3C613EEDA0803C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `utf8_encoded_surrogate` TO lt_names.
    lv_hex = `3C613E613C2F613EE282`.
    APPEND lv_hex TO lt_hex.
    APPEND `utf8_truncated_at_eof` TO lt_names.
    lv_hex = `3C6120783D2280222F3E`.
    APPEND lv_hex TO lt_hex.
    APPEND `utf8_in_attribute` TO lt_names.
    lv_hex = `FFFE3C0061003E00E9003C002F0061003E00`.
    APPEND lv_hex TO lt_hex.
    APPEND `utf16le_bom_text` TO lt_names.
    lv_hex = `FFFE3C0061003E003C002F0062003E00`.
    APPEND lv_hex TO lt_hex.
    APPEND `utf16le_bom_mismatched_close` TO lt_names.
    lv_hex = `FEFF003C0061003E003C002F0062003E`.
    APPEND lv_hex TO lt_hex.
    APPEND `utf16be_bom_mismatched_close` TO lt_names.
    lv_hex = `3C3F786D6C2076657273696F6E3D22312E302220656E636F64696E673D2249534F2D383835392D31223F3E3C613EE93C2F613E`.
    APPEND lv_hex TO lt_hex.
    APPEND `latin1_declared_text` TO lt_names.
    lv_hex = `3C3F786D6C2076657273696F6E3D22312E302220656E636F64696E673D2249534F2D383835392D31223F3E3C613EE93C2F623E`.
    APPEND lv_hex TO lt_hex.
    APPEND `latin1_declared_mismatched_close` TO lt_names.
    lv_out = `SXML<<`.
    LOOP AT lt_names INTO lv_name.
      lv_index = sy-tabix.
      READ TABLE lt_hex INDEX lv_index INTO lv_hex.
      lv_x = lv_hex.
      IF lv_index > 1.
        lv_out = lv_out && `|`.
      ENDIF.
      lv_out = lv_out && `@` && lv_name.
      CLEAR: lt_ev, lv_done.
      TRY.
          li_reader = cl_sxml_string_reader=>create( lv_x ).
          WHILE lv_done = abap_false.
            IF lines( lt_ev ) >= 256.
              CLEAR ls_ev.
              ls_ev-kw = `ABORT`.
              APPEND ls_ev TO lt_ev.
              EXIT.
            ENDIF.
            li_reader->next_node( ).
            CLEAR ls_ev.
            CASE li_reader->node_type.
              WHEN if_sxml_node=>co_nt_final.
                ls_ev-kw = `FINAL`.
                APPEND ls_ev TO lt_ev.
                lv_done = abap_true.
              WHEN if_sxml_node=>co_nt_element_open.
                ls_ev-kw = `OPEN`.
                ls_ev-n = 2.
                ls_ev-f1 = li_reader->name.
                ls_ev-f2 = li_reader->nsuri.
                APPEND ls_ev TO lt_ev.
                DO.
                  IF lines( lt_ev ) >= 256.
                    EXIT.
                  ENDIF.
                  li_reader->next_attribute( ).
                  IF li_reader->node_type <> if_sxml_node=>co_nt_attribute.
                    EXIT.
                  ENDIF.
                  CLEAR ls_ev.
                  ls_ev-kw = `ATTR`.
                  ls_ev-n = 3.
                  ls_ev-f1 = li_reader->name.
                  ls_ev-f2 = li_reader->nsuri.
                  ls_ev-f3 = li_reader->value.
                  APPEND ls_ev TO lt_ev.
                ENDDO.
              WHEN if_sxml_node=>co_nt_element_close.
                ls_ev-kw = `CLOSE`.
                ls_ev-n = 1.
                ls_ev-f1 = li_reader->name.
                APPEND ls_ev TO lt_ev.
              WHEN if_sxml_node=>co_nt_value.
                ls_ev-kw = `VALUE`.
                ls_ev-n = 1.
                ls_ev-f1 = li_reader->value.
                APPEND ls_ev TO lt_ev.
              WHEN OTHERS.
                lv_line = li_reader->node_type.
                CONDENSE lv_line.
                ls_ev-kw = `NODE ` && lv_line.
                APPEND ls_ev TO lt_ev.
            ENDCASE.
          ENDWHILE.
        CATCH cx_root INTO lx_error.
          lv_class = cl_abap_classdescr=>get_class_name( lx_error ).
          FIND REGEX `=([^=]*)$` IN lv_class SUBMATCHES lv_class.
          lv_offset = `-`.
          TRY.
              lx_parse ?= lx_error.
              lv_offset = lx_parse->xml_offset.
              CONDENSE lv_offset.
            CATCH cx_sy_move_cast_error.
              lv_offset = `-`.
          ENDTRY.
          CLEAR ls_ev.
          ls_ev-kw = `ERROR ` && lv_class && ` ` && lv_offset.
          APPEND ls_ev TO lt_ev.
      ENDTRY.
      LOOP AT lt_ev INTO ls_ev.
        lv_line = ls_ev-kw.
        DO ls_ev-n TIMES.
          CASE sy-index.
            WHEN 1.
              lv_field = ls_ev-f1.
            WHEN 2.
              lv_field = ls_ev-f2.
            WHEN OTHERS.
              lv_field = ls_ev-f3.
          ENDCASE.
          IF lv_field CO lv_plain.
            lv_esc = lv_field.
          ELSE.
            CLEAR lv_esc.
            lv_len = strlen( lv_field ).
            lv_pos = 0.
            WHILE lv_pos < lv_len.
              lv_c = lv_field+lv_pos(1).
              IF lv_field+lv_pos(1) = ` `.
                lv_esc = lv_esc && ` `.
              ELSEIF lv_c CA lv_plain.
                lv_esc = lv_esc && lv_c.
              ELSE.
                TRY.
                    lv_code = cl_abap_conv_out_ce=>uccp( lv_c ).
                    lv_code_hex = lv_code.
                  CATCH cx_root.
                    lv_code_hex = `????`.
                ENDTRY.
                lv_esc = lv_esc && `\u` && lv_code_hex.
              ENDIF.
              lv_pos = lv_pos + 1.
            ENDWHILE.
          ENDIF.
          lv_line = lv_line && ` "` && lv_esc && `"`.
        ENDDO.
        lv_out = lv_out && `|` && lv_line.
      ENDLOOP.
    ENDLOOP.
    lv_out = lv_out && `>>SXML`.
    rv = lv_out.
  ENDMETHOD.

ENDCLASS.
