CLASS zcl_osd_luw_test DEFINITION PUBLIC FINAL CREATE PUBLIC FOR TESTING
  DURATION SHORT RISK LEVEL HARMLESS.
* The transactional buffer (backlog B.2).
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_osd_luw_test IMPLEMENTATION.
ENDCLASS.
