CLASS zcl_osd_amdp_test DEFINITION PUBLIC FINAL CREATE PUBLIC FOR TESTING
  DURATION SHORT RISK LEVEL HARMLESS.
* Seamless AMDP: an ABAP call that lands in HANA (backlog B.19).
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_osd_amdp_test IMPLEMENTATION.
ENDCLASS.
