// Reproduce the 7.02 catalogue from the same core instance as the frontend.
import {createRequire} from "node:module";
import {mkdtempSync, writeFileSync, rmSync, mkdirSync} from "node:fs";
import {resolve, join} from "node:path";
import {compileProgram} from "./frontend.mjs";
const req = createRequire(import.meta.url);
const coreReq = createRequire(req.resolve("@abaplint/transpiler/package.json"));
const {BuiltIn} = coreReq("@abaplint/core/build/src/abap/5_syntax/_builtin.js");
const {Release, releaseAtLeast} = coreReq("@abaplint/core/build/src/version.js");
export const builtins702 = () => Object.entries(BuiltIn.methods)
  .filter(([, def]) => !def.release || releaseAtLeast(Release.v702, def.release));

if (process.argv[1] === new URL(import.meta.url).pathname) {
  mkdirSync(".local", {recursive: true});
  const folder = mkdtempSync(resolve(".local/builtin-audit-"));
  const rows = [];
  const numeric = (t) => /Integer|Float|Packed|Numeric/.test(t.constructor.name);
  const value = (name, t) => name === "bit" ? "8" : name === "format" ? "24" : name === "occ" ? "1"
    : name === "len" ? "1" : /Table/.test(t.constructor.name) ? "tab" : numeric(t) ? "1" : "'a'";
  try {
    for (const [name, def] of builtins702()) {
      const cls = `ZCL_BIA_${rows.length}`;
      const required = Object.entries(def.mandatory ?? {});
      const params = required.map(([n,t]) => `${n} = ${value(n,t)}`);
      let expression = `${name.toLowerCase()}( ${params.join(" ")} )`;
      if (required.length === 1) expression = `${name.toLowerCase()}( ${value(...required[0])} )`;
      if (name === "BOOLC") expression = "boolc( 1 = 1 )";
      if (name === "BOOLX") expression = "boolx( bool = 1 = 1 bit = 8 )";
      if (name === "NMIN" || name === "NMAX") expression = `${name.toLowerCase()}( val1 = 1 val2 = 2 )`;
      const supportedProbes = {
        ESCAPE: "escape( val = 'a' format = cl_abap_format=>e_json_string )",
        FIND: "find( val = 'a' sub = 'a' )", REPLACE: "replace( val = 'a' sub = 'a' with = 'b' )",
        SUBSTRING: "substring( val = 'a' off = 0 len = 1 )",
        SUBSTRING_BEFORE: "substring_before( val = 'a' sub = 'a' )",
        SUBSTRING_AFTER: "substring_after( val = 'a' sub = 'a' )", XSTRLEN: "xstrlen( bytes )",
      };
      expression = supportedProbes[name] ?? expression;
      if (def.predicate) expression = `boolc( ${expression} )`;
      const type = name === "BOOLC" || def.predicate ? "string" : /XString/.test(def.return.constructor.name) ? "xstring"
        : numeric(def.return) ? "i" : /Character/.test(def.return.constructor.name) ? "c LENGTH 1" : "string";
      writeFileSync(join(folder, `${cls.toLowerCase()}.clas.abap`), `CLASS ${cls} DEFINITION PUBLIC FINAL CREATE PUBLIC. PUBLIC SECTION. CLASS-METHODS run. ENDCLASS.
CLASS ${cls} IMPLEMENTATION. METHOD run. DATA tab TYPE STANDARD TABLE OF string WITH DEFAULT KEY. DATA bytes TYPE xstring. DATA result TYPE ${type}. result = ${expression}. ENDMETHOD. ENDCLASS.\n`);
      rows.push({name, cls, expression});
    }
    const p = compileProgram({folders:[folder, resolve(".local/lars/open-abap-core/src")], objects:rows.map((r)=>r.cls), tolerant:true});
    const issues = p.reg.findIssues();
    const text = rows.map((r) => {
      const refusal = [...p.skipped, ...p.partial].find((x) => x.startsWith(r.cls+"=>"));
      const status = p.broken.includes(r.cls.toLowerCase()) ? "Parser/type checker refusal" : refusal ? "Refused" : "Lowered";
      const issue = issues.find((i) => i.getFilename() === `${r.cls.toLowerCase()}.clas.abap`);
      const why = refusal?.slice(refusal.indexOf("): ")+3) ?? (status === "Lowered" ? "Supported for this row; see limits below" : issue?.getMessage() ?? "abaplint parser or syntax check rejects this shape");
      return `| ${r.name.toLowerCase()} | \`${r.expression}\` | ${status} | ${why.replaceAll("|", "\\|")} |`;
    }).join("\n");
    const header = `# gogen built-in function audit\n\nGenerated by \`node tools/gogen/builtin-audit.mjs\` from the transpiler's installed \`@abaplint/core\` built-in table (${coreReq("@abaplint/core/package.json").version}). Include entries without a release gate or whose release is at most v702, using core's \`releaseAtLeast\`. ${rows.length} entries. Each row records a compile probe, not a claim that every parameter form works.\n\n\`ipow\` (7.40 SP02) and \`xsdbool\` (7.40 SP08) are outside this 7.02 list. gogen compiles with v758 and lowers both.\n\n| Function | Probe | Status | Refusal or scope |\n|---|---|---|---|\n`;
    writeFileSync("docs/gogen-builtins.md", header+text+`\n\n## Limits and next oracle rows\n\n- Numeric unary functions: i/f/p; nmin/nmax: i/f. Other operand types are not covered by these probes.\n- String functions accept only the forms the frontend explicitly lowers; regexp and unusual offsets can be refused. The refusal text includes the specific unsupported argument or form.\n- ipow: i and int8 use checked multiplication; packed decimal uses exact intermediate multiplication. The exponent converts to i and does not choose the result type. In arithmetic, the enclosing calculation type applies. Exponent zero returns one, including zero base.\n- Next A4H oracle rows: negative exponents for i/int8/p (including zero base); runtime refusal is \`NOT_COMPILED in ipow( ): negative exponent: awaiting A4H oracle\`. f calculation types are also refused pending measurement.\n- decfloat16/34 remain outside gogen's type subset, with \`type DecFloat16Type is outside the subset\` / \`type DecFloat34Type is outside the subset\`; never converted through a binary float. Next oracle rows: decfloat precision, rounding and exponent bounds before expanding that type subset.\n- boolx: logical expression bridged through boolc to accommodate core's character-source signature; bit numbering starts at one at the most significant bit. Zero gives an empty xstring; negative positions fill the prefix. Bits beyond 524288 raise a named local allocation-limit refusal.\n\nContracts, from mirrored SAP keyword documentation: [integer power](https://eduardocopat.github.io/abap-docs/7.54/abenpower_function/), [logical functions](https://eduardocopat.github.io/abap-docs/7.40/abenboole_functions/), [bit-set](https://eduardocopat.github.io/abap-docs/7.40/abenbit_functions/). The upstream JS ipow implementation uses Math.pow and fixed rounding; it is not used as the oracle.\n`);
    console.log(`${rows.length} built-ins audited; ${p.partial.length} partial refusals, ${p.broken.length} syntax refusals`);
  } finally { rmSync(folder, {recursive:true, force:true}); }
}
