// IR -> Go source, for the Go backend spike.
//
// Nothing here decides semantics: the IR already says which calculation type
// every operator runs in and where a conversion happens. This file only
// spells it. A method becomes a function taking the Session first -- the
// roll area -- so the same generated code can run on any goroutine.

const goType = (t) => {
  if (t.k === "i") return "int32";
  if (t.k === "f") return "float64";
  if (t.k === "table") return `[]${goType(t.row)}`;
  throw new Error(`no Go type for ${t.k}`);
};

const ident = (name) => name.toLowerCase().replace(/[^a-z0-9_]/g, "_");
export const funcName = (cls, method) => `${cls}_${method}`.replace(/[^A-Za-z0-9_]/g, "_");

export function emitGo(classes, pkg = "main") {
  const out = [];
  out.push("// Code generated by tools/gogen/emit-go.mjs. DO NOT EDIT.");
  out.push("");
  out.push(`package ${pkg}`);
  out.push("");
  out.push("import (");
  out.push("\t\"math\"");
  out.push("");
  out.push("\t\"osg/gogen/abap\"");
  out.push(")");
  out.push("");
  out.push("var _ = math.Sin");
  out.push("");
  for (const cls of classes) {
    for (const m of cls.methods) out.push(...method(cls, m), "");
  }
  out.push(...dispatcher(classes));
  return out.join("\n") + "\n";
}

function method(cls, m) {
  const params = ["s *abap.Session", ...m.params.map((p) => `${ident(p.name)} ${goType(p.type)}`)];
  const ret = m.returning ? ` (${ident(m.returning.name)} ${goType(m.returning.type)})` : "";
  const lines = [`func ${funcName(cls.name, m.method ?? m.name)}(${params.join(", ")})${ret} {`];
  // IMPORTING parameters are read-only in ABAP; the generated code never
  // assigns them, so passing them by value is exact
  for (const l of m.locals) lines.push(`\tvar ${ident(l.name)} ${goType(l.type)}`);
  for (const l of m.locals) lines.push(`\t_ = ${ident(l.name)}`);
  const ctx = {cls, loop: 0};
  lines.push(...m.body.flatMap((st) => stmt(st, ctx, 1)));
  lines.push("\treturn");
  lines.push("}");
  return lines;
}

const tab = (n) => "\t".repeat(n);

function stmt(st, ctx, d) {
  const t = tab(d);
  switch (st.s) {
    case "assign":
      return [`${t}${ident(st.target)} = ${expr(st.value, ctx)}`];
    case "clear":
      return [`${t}${ident(st.target)} = ${st.type.k === "table" ? "nil" : "0"}`];
    case "append":
      return [
        `${t}${ident(st.table)} = append(${ident(st.table)}, ${expr(st.value, ctx)})`,
        `${t}s.Sy.Tabix = int32(len(${ident(st.table)}))`,
      ];
    case "read_index": {
      const n = `idx${ctx.loop++}`;
      return [
        `${t}if ${n} := ${expr(st.index, ctx)}; ${n} >= 1 && int(${n}) <= len(${ident(st.table)}) {`,
        `${t}\t${ident(st.into)} = ${ident(st.table)}[${n}-1]`,
        `${t}\ts.Sy.Subrc = 0`,
        `${t}\ts.Sy.Tabix = ${n}`,
        `${t}} else {`,
        `${t}\ts.Sy.Subrc = 4`,
        `${t}}`,
      ];
    }
    case "if": {
      const lines = [];
      st.branches.forEach((b, i) => {
        lines.push(`${t}${i === 0 ? "if" : "} else if"} ${cond(b.cond, ctx)} {`);
        lines.push(...b.body.flatMap((x) => stmt(x, ctx, d + 1)));
      });
      if (st.else !== null) {
        lines.push(`${t}} else {`);
        lines.push(...st.else.flatMap((x) => stmt(x, ctx, d + 1)));
      }
      lines.push(`${t}}`);
      return lines;
    }
    case "do": {
      // sy-index is the pass counter of the innermost DO/WHILE and comes
      // back to the enclosing loop's value after ENDDO
      const n = ctx.loop++;
      const lines = [`${t}{`, `${t}\tsave${n} := s.Sy.Index`];
      if (st.times === null) {
        lines.push(`${t}\tfor i${n} := int32(1); ; i${n}++ {`);
      } else {
        lines.push(`${t}\tn${n} := ${expr(st.times, ctx)}`);
        lines.push(`${t}\tfor i${n} := int32(1); i${n} <= n${n}; i${n}++ {`);
      }
      lines.push(`${t}\t\ts.Sy.Index = i${n}`);
      lines.push(...st.body.flatMap((x) => stmt(x, ctx, d + 2)));
      lines.push(`${t}\t}`, `${t}\ts.Sy.Index = save${n}`, `${t}}`);
      return lines;
    }
    case "while": {
      const n = ctx.loop++;
      return [
        `${t}{`,
        `${t}\tsave${n} := s.Sy.Index`,
        `${t}\tfor i${n} := int32(1); ${cond(st.cond, ctx)}; i${n}++ {`,
        `${t}\t\ts.Sy.Index = i${n}`,
        ...st.body.flatMap((x) => stmt(x, ctx, d + 2)),
        `${t}\t}`,
        `${t}\ts.Sy.Index = save${n}`,
        `${t}}`,
      ];
    }
    case "loop": {
      // index-based on purpose: a row APPENDed inside the loop is visited,
      // as in ABAP; a range over the slice would not see it
      const n = ctx.loop++;
      const tb = ident(st.table);
      return [
        `${t}{`,
        `${t}\tsave${n} := s.Sy.Tabix`,
        `${t}\ts.Sy.Subrc = 4`,
        `${t}\tfor i${n} := 0; i${n} < len(${tb}); i${n}++ {`,
        `${t}\t\ts.Sy.Tabix = int32(i${n} + 1)`,
        `${t}\t\ts.Sy.Subrc = 0`,
        `${t}\t\t${ident(st.into)} = ${tb}[i${n}]`,
        ...st.body.flatMap((x) => stmt(x, ctx, d + 2)),
        `${t}\t}`,
        `${t}\ts.Sy.Tabix = save${n}`,
        `${t}}`,
      ];
    }
    case "exit":
      return [`${t}break`];
    case "continue":
      return [`${t}continue`];
    case "return":
      return [`${t}return`];
    default:
      throw new Error(`no Go for statement ${st.s}`);
  }
}

const I_OPS = {"+": "abap.AddI", "-": "abap.SubI", "*": "abap.MulI", "/": "abap.DivI", DIV: "abap.DivIntI", MOD: "abap.ModI"};
const F_OPS = {"/": "abap.DivF", DIV: "abap.DivIntF", MOD: "abap.ModF"};

function expr(e, ctx) {
  switch (e.e) {
    case "var":
      return ident(e.name);
    case "sy":
      return `s.Sy.${e.field[0].toUpperCase()}${e.field.slice(1)}`;
    case "int":
      return `int32(${e.value})`;
    case "float":
      return Number.isInteger(e.value) ? `float64(${e.value})` : String(e.value);
    case "neg":
      return e.type.k === "i" ? `abap.NegI(${expr(e.x, ctx)})` : `(-${expr(e.x, ctx)})`;
    case "bin":
      if (e.type.k === "i") return `${I_OPS[e.op]}(${expr(e.l, ctx)}, ${expr(e.r, ctx)})`;
      if (F_OPS[e.op] !== undefined) return `${F_OPS[e.op]}(${expr(e.l, ctx)}, ${expr(e.r, ctx)})`;
      return `(${expr(e.l, ctx)} ${e.op} ${expr(e.r, ctx)})`;
    case "conv":
      if (e.from.k === "i" && e.to.k === "f") return `float64(${expr(e.x, ctx)})`;
      if (e.from.k === "f" && e.to.k === "i") return `abap.F2I(${expr(e.x, ctx)})`;
      throw new Error("conversion");
    case "fn": {
      const arg = expr(e.args[0], ctx);
      if (e.name === "ABS") return e.type.k === "i" ? `abap.AbsI(${arg})` : `math.Abs(${arg})`;
      return `math.${e.name[0]}${e.name.slice(1).toLowerCase()}(${arg})`;
    }
    case "lines":
      return `int32(len(${ident(e.table)}))`;
    case "call":
      return `${funcName(ctx.cls.name, e.method)}(${["s", ...e.args.map((a) => expr(a, ctx))].join(", ")})`;
    default:
      throw new Error(`no Go for expression ${e.e}`);
  }
}

function cond(c, ctx) {
  switch (c.c) {
    case "cmp":
      return `${expr(c.l, ctx)} ${c.op === "=" ? "==" : c.op === "<>" ? "!=" : c.op} ${expr(c.r, ctx)}`;
    case "and":
      return `(${cond(c.l, ctx)} && ${cond(c.r, ctx)})`;
    case "or":
      return `(${cond(c.l, ctx)} || ${cond(c.r, ctx)})`;
    case "not":
      return `!(${cond(c.x, ctx)})`;
    default:
      throw new Error(`no Go for condition ${c.c}`);
  }
}

/** Call(name, session, args) for the harness: numbers in, a number out */
function dispatcher(classes) {
  const lines = ["// Call runs one method by name with numeric arguments, for the harness.",
    "func Call(name string, s *abap.Session, args []float64) float64 {", "\tswitch name {"];
  for (const cls of classes) {
    for (const m of cls.methods) {
      if (m.returning === null || m.params.some((p) => p.type.k === "table")) continue;
      const args = m.params.map((p, i) => (p.type.k === "i" ? `int32(args[${i}])` : `args[${i}]`));
      lines.push(`\tcase "${cls.name}=>${m.name}":`);
      lines.push(`\t\treturn float64(${funcName(cls.name, m.name)}(${["s", ...args].join(", ")}))`);
    }
  }
  lines.push("\t}", "\tpanic(\"unknown method \" + name)", "}");
  return lines;
}
