// IR -> Go source, for the Go backend spike.
//
// Nothing here decides semantics: the IR already says which calculation type
// every operator runs in and where a conversion happens. This file only
// spells it. A method takes the Session first -- the roll area -- so the
// same generated code runs on any goroutine. An instance method has the
// object as its receiver; a static one is a plain function.

const GO_RESERVED = new Set(("break default func interface select case defer go map struct chan else goto package switch const "
  + "fallthrough if range type continue for import return var append cap clear close complex copy delete imag len make max min new "
  + "panic print println real recover bool byte error float32 float64 int int8 int16 int32 int64 rune string uint uint8 uint16 "
  + "uint32 uint64 uintptr true false nil iota me s math abap").split(" "));

export const ident = (name) => {
  const id = String(name).toLowerCase().replace(/[^a-z0-9_]/g, "_");
  return GO_RESERVED.has(id) || /^\d/.test(id) ? `${id}_` : id;
};
const typeName = (s) => String(s).toUpperCase().replace(/=>|~|-/g, "__").replace(/[^A-Z0-9_]/g, "_");
export const funcName = (cls, method) => `${typeName(cls)}_${typeName(method)}`;

export function goType(t) {
  switch (t.k) {
    case "i": return "int32";
    case "int8": return "int64";
    case "f": return "float64";
    case "string": case "c": case "x": return "string";
    case "table": return `[]${goType(t.row)}`;
    case "struct": return t.go;
    case "ref": return `*${typeName(t.name)}`;
    default: throw new Error(`no Go type for ${t.k}`);
  }
}

const zero = (t) => (t.k === "i" || t.k === "int8" || t.k === "f" ? "0" : t.k === "string" || t.k === "c" || t.k === "x" ? `""` : t.k === "struct" ? `${t.go}{}` : "nil");

export function emitGo(program, pkg = "main") {
  const classes = Array.isArray(program) ? program : program.classes;
  const structs = Array.isArray(program) ? new Map() : program.structs;
  const consts = Array.isArray(program) ? new Map() : program.consts;
  const out = [];
  out.push("// Code generated by tools/gogen/emit-go.mjs. DO NOT EDIT.", "", `package ${pkg}`, "", "import (",
    "\t\"math\"", "", "\t\"osg/gogen/abap\"", ")", "", "var _ = math.Sin", "var _ = abap.AddI", "");
  for (const st of structs.values()) {
    out.push(`type ${st.go} struct {`);
    for (const f of st.fields) out.push(`\t${ident(f.name)} ${goType(f.type)}`);
    out.push("}", "");
  }
  for (const c of consts.values()) out.push(`var ${c.go} ${goType(c.type)} = ${constLiteral(c)}`);
  if (consts.size > 0) out.push("");
  for (const cls of classes) {
    const inst = (cls.attributes ?? []).filter((a) => !a.static && !a.unsupported);
    out.push(`type ${typeName(cls.name)} struct {`);
    for (const a of inst) out.push(`\t${ident(a.name)} ${goType(a.type)}`);
    out.push("}", "");
    for (const a of (cls.attributes ?? []).filter((x) => x.static && !x.unsupported)) {
      out.push(`var ${typeName(`${cls.name}=>${a.name}`)} ${goType(a.type)}`);
    }
    for (const m of cls.methods) out.push(...method(cls, m), "");
    if (cls.constructor) out.push(...method(cls, {...cls.constructor, name: "CONSTRUCTOR", static: false}), "");
  }
  out.push(...dispatcher(classes));
  return out.join("\n") + "\n";
}

function constLiteral(c) {
  if (c.type.k === "i" || c.type.k === "int8") return String(Number(c.value));
  if (c.type.k === "f") return String(Number(c.value));
  if (c.type.k === "string" || c.type.k === "c") return JSON.stringify(c.type.k === "c" ? c.value.replace(/ +$/, "") : c.value);
  throw new Error(`constant of type ${c.type.k}`);
}

function signature(cls, m) {
  const params = ["s *abap.Session", ...m.params.map((p) => `${ident(p.name)} ${p.dir === "importing" ? "" : "*"}${goType(p.type)}`)];
  const ret = m.returning ? ` (${ident(m.returning.name)} ${goType(m.returning.type)})` : "";
  return m.static
    ? `func ${funcName(cls.name, m.name)}(${params.join(", ")})${ret}`
    : `func (me *${typeName(cls.name)}) ${typeName(m.name)}(${params.join(", ")})${ret}`;
}

function method(cls, m) {
  const lines = [`${signature(cls, m)} {`, "\t_ = s"];
  if (!m.static) lines.push("\t_ = me");
  for (const l of m.locals) lines.push(`\tvar ${ident(l.name)} ${goType(l.type)}`, `\t_ = ${ident(l.name)}`);
  const ctx = {cls, loop: 0};
  lines.push(...m.body.flatMap((st) => stmt(st, ctx, 1)));
  lines.push("\treturn", "}");
  return lines;
}

const tab = (n) => "\t".repeat(n);

function place(p, ctx) {
  switch (p.e) {
    case "var": return p.ref ? `(*${ident(p.name)})` : ident(p.name);
    case "attr": return `me.${ident(p.name)}`;
    case "static": return p.go;
    case "field": return `${place(p.base, ctx)}.${ident(p.name)}`;
    default: throw new Error(`not a place: ${p.e}`);
  }
}

function stmt(st, ctx, d) {
  const t = tab(d);
  switch (st.s) {
    case "assign":
      return [`${t}${place(st.target, ctx)} = ${expr(st.value, ctx)}`];
    case "clear":
      return [`${t}${place(st.target, ctx)} = ${zero(st.target.type)}`];
    case "append": {
      const tb = place(st.table, ctx);
      return [`${t}${tb} = append(${tb}, ${expr(st.value, ctx)})`, `${t}s.Sy.Tabix = int32(len(${tb}))`];
    }
    case "read_index": {
      const n = `idx${ctx.loop++}`;
      const tb = expr(st.table, ctx);
      return [
        `${t}if ${n} := ${expr(st.index, ctx)}; ${n} >= 1 && int(${n}) <= len(${tb}) {`,
        `${t}\t${place(st.into, ctx)} = ${tb}[${n}-1]`,
        `${t}\ts.Sy.Subrc = 0`,
        `${t}\ts.Sy.Tabix = ${n}`,
        `${t}} else {`,
        `${t}\ts.Sy.Subrc = 4`,
        `${t}}`,
      ];
    }
    case "translate": {
      const p = place(st.target, ctx);
      return [`${t}${p} = abap.${st.upper ? "ToUpper" : "ToLower"}(${p})`];
    }
    case "call":
      return [`${t}${expr(st.call, ctx)}`];
    case "if": {
      const lines = [];
      st.branches.forEach((b, i) => {
        lines.push(`${t}${i === 0 ? "if" : "} else if"} ${cond(b.cond, ctx)} {`);
        lines.push(...b.body.flatMap((x) => stmt(x, ctx, d + 1)));
      });
      if (st.else !== null) {
        lines.push(`${t}} else {`);
        lines.push(...st.else.flatMap((x) => stmt(x, ctx, d + 1)));
      }
      lines.push(`${t}}`);
      return lines;
    }
    case "case": {
      const lines = [`${t}{`, `${t}\t${st.temp} := ${expr(st.subject, ctx)}`, `${t}\t_ = ${st.temp}`];
      if (st.branches.length === 0 && st.else !== null) {
        lines.push(...st.else.flatMap((x) => stmt(x, ctx, d + 1)));
      } else {
        st.branches.forEach((b, i) => {
          lines.push(`${t}\t${i === 0 ? "if" : "} else if"} ${cond(b.cond, ctx)} {`);
          lines.push(...b.body.flatMap((x) => stmt(x, ctx, d + 2)));
        });
        if (st.else !== null) {
          lines.push(`${t}\t} else {`);
          lines.push(...st.else.flatMap((x) => stmt(x, ctx, d + 2)));
        }
        if (st.branches.length > 0) lines.push(`${t}\t}`);
      }
      lines.push(`${t}}`);
      return lines;
    }
    case "do": {
      // sy-index is the pass counter of the innermost DO/WHILE and comes
      // back to the enclosing loop's value after ENDDO
      const n = ctx.loop++;
      const lines = [`${t}{`, `${t}\tsave${n} := s.Sy.Index`];
      if (st.times === null) lines.push(`${t}\tfor i${n} := int32(1); ; i${n}++ {`);
      else lines.push(`${t}\tn${n} := ${expr(st.times, ctx)}`, `${t}\tfor i${n} := int32(1); i${n} <= n${n}; i${n}++ {`);
      lines.push(`${t}\t\ts.Sy.Index = i${n}`, ...st.body.flatMap((x) => stmt(x, ctx, d + 2)), `${t}\t}`, `${t}\ts.Sy.Index = save${n}`, `${t}}`);
      return lines;
    }
    case "while": {
      const n = ctx.loop++;
      return [
        `${t}{`, `${t}\tsave${n} := s.Sy.Index`,
        `${t}\tfor i${n} := int32(1); ${cond(st.cond, ctx)}; i${n}++ {`,
        `${t}\t\ts.Sy.Index = i${n}`,
        ...st.body.flatMap((x) => stmt(x, ctx, d + 2)),
        `${t}\t}`, `${t}\ts.Sy.Index = save${n}`, `${t}}`,
      ];
    }
    case "loop": {
      // index-based on purpose: a row APPENDed inside the loop is visited,
      // as in ABAP; a range over the slice would not see it
      const n = ctx.loop++;
      const tb = expr(st.table, ctx);
      return [
        `${t}{`, `${t}\tsave${n} := s.Sy.Tabix`, `${t}\ts.Sy.Subrc = 4`,
        `${t}\tfor i${n} := 0; i${n} < len(${tb}); i${n}++ {`,
        `${t}\t\ts.Sy.Tabix = int32(i${n} + 1)`, `${t}\t\ts.Sy.Subrc = 0`,
        `${t}\t\t${place(st.into, ctx)} = ${tb}[i${n}]`,
        ...st.body.flatMap((x) => stmt(x, ctx, d + 2)),
        `${t}\t}`, `${t}\ts.Sy.Tabix = save${n}`, `${t}}`,
      ];
    }
    case "exit": return [`${t}break`];
    case "continue": return [`${t}continue`];
    case "return": return [`${t}return`];
    default: throw new Error(`no Go for statement ${st.s}`);
  }
}

const I_OPS = {"+": "abap.AddI", "-": "abap.SubI", "*": "abap.MulI", "/": "abap.DivI", DIV: "abap.DivIntI", MOD: "abap.ModI"};
const I8_OPS = {"+": "abap.AddI8", "-": "abap.SubI8", "*": "abap.MulI8", "/": "abap.DivI8", DIV: "abap.DivIntI8", MOD: "abap.ModI8"};
const F_OPS = {"/": "abap.DivF", DIV: "abap.DivIntF", MOD: "abap.ModF"};
const FN_F = {SIN: "math.Sin", COS: "math.Cos", TAN: "math.Tan", SQRT: "abap.SqrtF", EXP: "math.Exp", LOG: "abap.LogF", LOG10: "math.Log10"};

function expr(e, ctx) {
  switch (e.e) {
    case "var": case "attr": case "static": case "field": return place(e, ctx);
    case "const": return e.go;
    case "temp": return e.name;
    case "sy": return `s.Sy.${e.field}`;
    case "int": return `int32(${e.value})`;
    case "float": return Number.isInteger(e.value) ? `float64(${e.value})` : String(e.value);
    case "chars": case "str": return JSON.stringify(e.value);
    case "template": {
      const parts = e.parts.map((p) => (p.text !== undefined ? JSON.stringify(p.text) : templatePart(p.value, ctx)));
      return parts.length === 0 ? `""` : `(${parts.join(" + ")})`;
    }
    case "concat": return `(${expr(e.l, ctx)} + ${expr(e.r, ctx)})`;
    case "struct":
      return `${e.type.go}{${e.fields.map((f) => `${ident(f.name)}: ${expr(f.value, ctx)}`).join(", ")}}`;
    case "neg": return e.type.k === "i" ? `abap.NegI(${expr(e.x, ctx)})` : `(-${expr(e.x, ctx)})`;
    case "bin":
      if (e.type.k === "i") return `${I_OPS[e.op]}(${expr(e.l, ctx)}, ${expr(e.r, ctx)})`;
      if (e.type.k === "int8") return `${I8_OPS[e.op]}(${expr(e.l, ctx)}, ${expr(e.r, ctx)})`;
      if (F_OPS[e.op] !== undefined) return `${F_OPS[e.op]}(${expr(e.l, ctx)}, ${expr(e.r, ctx)})`;
      return `(${expr(e.l, ctx)} ${e.op} ${expr(e.r, ctx)})`;
    case "conv": return conv(e, ctx);
    case "fn": return fn(e, ctx);
    case "lines": return `int32(len(${expr(e.table, ctx)}))`;
    case "strlen": return `abap.Strlen(${expr(e.x, ctx)})`;
    case "call": {
      const args = ["s", ...e.args.map((a) => (a.dir === "importing" ? expr(a.value, ctx)
        : a.place === null ? `new(${goType(a.type)})` : `&${place(a.place, ctx)}`))];
      return e.static ? `${funcName(ctx.cls.name, e.method)}(${args.join(", ")})` : `me.${typeName(e.method)}(${args.join(", ")})`;
    }
    default: throw new Error(`no Go for expression ${e.e}`);
  }
}

function templatePart(v, ctx) {
  const x = expr(v, ctx);
  switch (v.type.k) {
    case "i": return `abap.FmtI(${x})`;
    case "int8": return `abap.FmtI8(${x})`;
    case "f": return `abap.FmtF(${x})`;
    case "string": case "c": return x;
    case "x": return `abap.XToHex(${x})`;
    default: throw new Error(`template part ${v.type.k}`);
  }
}

function conv(e, ctx) {
  const x = expr(e.x, ctx);
  const from = e.from.k;
  const to = e.to.k;
  switch (e.kind) {
    case "num":
      if (from === "i" && to === "f") return `float64(${x})`;
      if (from === "f" && to === "i") return `abap.F2I(${x})`;
      if (from === "i" && to === "int8") return `int64(${x})`;
      if (from === "int8" && to === "i") return `abap.I8ToI(${x})`;
      if (from === "int8" && to === "f") return `float64(${x})`;
      if (from === "f" && to === "int8") return `abap.F2I8(${x})`;
      break;
    case "c2s": return x;
    case "s2c": return `abap.CFit(${x}, ${e.to.len})`;
    case "i2s": return `abap.IToString(${x})`;
    case "x2s": return `abap.XToHex(${x})`;
    case "i2x": return `abap.IToX(${x}, ${e.to.len})`;
    case "c2n":
      if (to === "f") return `abap.ParseF(${x})`;
      if (to === "i") return `abap.ParseI(${x})`;
      break;
    default: break;
  }
  throw new Error(`no Go for conversion ${e.kind} ${from}->${to}`);
}

function fn(e, ctx) {
  const args = e.args.map((a) => expr(a, ctx));
  if (FN_F[e.name]) return `${FN_F[e.name]}(${args[0]})`;
  const k = e.type.k;
  switch (e.name) {
    case "NMAX": return k === "i" ? `abap.MaxI(${args.join(", ")})` : `abap.MaxF(${args.join(", ")})`;
    case "NMIN": return k === "i" ? `abap.MinI(${args.join(", ")})` : `abap.MinF(${args.join(", ")})`;
    case "ABS": return k === "i" ? `abap.AbsI(${args[0]})` : `math.Abs(${args[0]})`;
    case "SIGN": return k === "i" ? `abap.SignI(${args[0]})` : `abap.SignF(${args[0]})`;
    case "FLOOR": return k === "i" ? args[0] : `math.Floor(${args[0]})`;
    case "CEIL": return k === "i" ? args[0] : `math.Ceil(${args[0]})`;
    case "TRUNC": return k === "i" ? args[0] : `math.Trunc(${args[0]})`;
    case "FRAC": return k === "i" ? "int32(0)" : `abap.FracF(${args[0]})`;
    default: throw new Error(`no Go for function ${e.name}`);
  }
}

function cond(c, ctx) {
  switch (c.c) {
    case "cmp": return `${expr(c.l, ctx)} ${c.op === "=" ? "==" : c.op === "<>" ? "!=" : c.op} ${expr(c.r, ctx)}`;
    case "initial": return `${expr(c.x, ctx)} == ${zero(c.x.type)}`;
    case "and": return `(${cond(c.l, ctx)} && ${cond(c.r, ctx)})`;
    case "or": return `(${cond(c.l, ctx)} || ${cond(c.r, ctx)})`;
    case "not": return `!(${cond(c.x, ctx)})`;
    default: throw new Error(`no Go for condition ${c.c}`);
  }
}

/** Call(name, session, args) for the numeric harness: numbers in, a number out */
function dispatcher(classes) {
  const lines = ["// Call runs one static method by name with numeric arguments, for the harness.",
    "func Call(name string, s *abap.Session, args []float64) float64 {", "\tswitch name {"];
  for (const cls of classes) {
    for (const m of cls.methods) {
      if (!m.static || m.returning === null || !["i", "f"].includes(m.returning.type.k)) continue;
      if (m.params.some((p) => p.dir !== "importing" || !["i", "f"].includes(p.type.k))) continue;
      const args = m.params.map((p, i) => (p.type.k === "i" ? `int32(args[${i}])` : `args[${i}]`));
      lines.push(`\tcase "${cls.name}=>${m.name}":`, `\t\treturn float64(${funcName(cls.name, m.name)}(${["s", ...args].join(", ")}))`);
    }
  }
  lines.push("\t}", "\tpanic(\"unknown method \" + name)", "}");
  return lines;
}
