// The build-time half of OSGo's system status (ultra/json): what the binary
// serves, as rows of the snapshot ZCL_OSD_STATUS=>REFRESH parses
// (tools/osd-status.mjs is the Node side and the contract). Written by
// osgo.mjs into go/cmd/osgo/zz_status.go; go/cmd/osgo/status.go adds the
// facts of the running process (pid, port, sockets, RSS, clock, the apps
// under -root) and posts the whole snapshot through the compiled REFRESH.
//
// Only what this binary serves is listed, never what the tree has:
//   - ODATA: a SEGW registration whose DPC class this program compiled;
//   - ICF: a SICF node OSGo mounts (the ones it answers with a refusal are
//     not services of this system);
//   - APC: none, OSGo serves no push channel;
//   - packs: a pack whose page OSGo serves or whose ABAP it compiled, with
//     the number of its objects in this program (none are, today).
// The texts and pack names are the ones osd-status.mjs gives the same
// rows, read from the same functions.
import {createHash} from "node:crypto";
import {existsSync, readFileSync} from "node:fs";
import {resolve} from "node:path";
import {home} from "./home.mjs";

// the paths test/start.mjs refreshes the status tables before (its
// app.all("<path>*", withFreshStatus) lines), read from the file rather than
// written out again, so OSGo refreshes before exactly the requests Node does
// (ultra/json fix round: the webgui was missing). Without the file (an echo
// build) the two paths it had on 2026-09-24.
export const FRESH_DEFAULT = ["/sap/bc/gui/sap/its/webgui", "/sap/opu/odata/sap/ZOSD_STATUS_SRV"];
export function freshPrefixes(root = home) {
  const f = `${root}/test/start.mjs`;
  if (!existsSync(f)) return FRESH_DEFAULT;
  const found = [...readFileSync(f, "utf8").matchAll(/app\.all\(\s*["']([^"'*]+)\*?["']\s*,\s*withFreshStatus\s*\)/g)].map((m) => m[1]);
  if (found.length === 0) throw new Error(`${f}: no app.all(..., withFreshStatus) found; the status refresh paths of OSGo cannot follow Node's`);
  return [...new Set(found)].sort();
}

export async function statusFacts({program, services, webapps, generated}) {
  const {servicesOf, packsInfo} = await import(`${home}/tools/osd-status.mjs`);
  const {packsOf} = await import(`${home}/tools/osd-packs.mjs`);
  const compiled = new Set(program.classes.map((c) => c.name));
  const mounted = new Set(services.map((s) => s.path.toLowerCase()));
  const rows = servicesOf(home).filter((s) => (s.kind === "ODATA" && compiled.has(String(s.handler).toUpperCase()))
    || (s.kind === "ICF" && mounted.has(String(s.path).toLowerCase())));
  // a row per path, as REFRESH keeps them (its READ ... WITH KEY path)
  const seen = new Set();
  const svc = rows.filter((s) => (seen.has(s.path) ? false : (seen.add(s.path), true)));
  // the files of the compiled global classes and interfaces, for a pack's count
  const files = [];
  for (const c of program.classes) {
    const obj = program.reg.getObject("CLAS", c.name) ?? program.reg.getObject("INTF", c.name);
    const f = obj?.getFiles?.()[0]?.getFilename?.();
    if (f) files.push(resolve(f));
  }
  const served = new Set(webapps.map((w) => resolve(w.dir)));
  const byName = new Map(packsOf(home).map((p) => [p.name, p]));
  const packs = packsInfo(home).filter((p) => {
    const pack = byName.get(p.name);
    const folders = (pack?.abap ?? []).map((f) => resolve(f) + "/");
    p.objects = files.filter((f) => folders.some((d) => f.startsWith(d))).length;
    const page = pack?.webapp ? resolve(pack.webapp) : undefined;
    return p.objects > 0 || (page !== undefined && served.has(page)) || webapps.some((w) => w.path === `/app/${p.name}`);
  });
  // the generation this process serves: the program itself, by content
  const generation = "go:" + createHash("sha256").update(generated).digest("hex").slice(0, 16);
  return {services: svc, packs, generation, fresh: freshPrefixes(home)};
}

/** zz_status.go: the facts above as Go values */
export function statusGo(facts, hasRefresh) {
  const q = JSON.stringify;
  const refresh = hasRefresh ? "\treturn ZCL_OSD_STATUS_REFRESH(s, json)"
    : `\tpanic(abap.NotCompiled("ZCL_OSD_STATUS=>REFRESH", "the class is not in this program"))`;
  return `package main

import "osg/gogen/abap"

// generated by tools/gogen/osgo.mjs (tools/gogen/status.mjs): what this
// binary serves, for the system status (status.go)

// the status writer of the program (status.go refreshStatus)
func statusRefresh(s *abap.Session, json string) int32 {
${refresh}
}

// the program this process runs, by the content of its generated code
const buildGeneration = ${q(facts.generation)}

// the paths whose requests refresh the status tables first: test/start.mjs's
// withFreshStatus mounts (status.mjs freshPrefixes)
var statusFreshPrefixes = []string{${(facts.fresh ?? FRESH_DEFAULT).map((x) => q(x)).join(", ")}}

var statusServed = []statusService{
${facts.services.map((s) => `\t{Path: ${q(s.path)}, Kind: ${q(s.kind)}, Handler: ${q(String(s.handler))}, Text: ${q(String(s.text ?? ""))}, Pack: ${q(String(s.pack ?? ""))}},`).join("\n")}
}

var statusPacksServed = []statusPack{
${facts.packs.map((p) => `\t{Name: ${q(p.name)}, Order: ${Number(p.order) | 0}, Objects: ${Number(p.objects) | 0}, Folders: ${q(String(p.folders ?? ""))}, Description: ${q(String(p.description ?? ""))}},`).join("\n")}
}
`;
}
