// open-steamgate running in the browser.
//
// test/start.mjs wires the transpiled runtime into express: initializeABAP()
// opens the database (test/setup.mjs), registers the demo services and every
// request under /sap/opu/odata/sap/ goes through CL_EXPRESS_ICF_SHIM into
// ZCL_STG_HTTP_HANDLER. This module does the same with the service worker in
// the role of express and sql.js compiled to JavaScript in the role of the
// database file. The pattern is larshp/hithub's web/preview-backend.mjs (MIT).
import "./preview-runtime.mjs";
import {Buffer} from "buffer";
import {seed, buildId} from "./generated/seed.mjs";

// test/setup.mjs looks for this before it touches the file system: the seed
// rows come from the bundle, the database from cache storage (or fresh).
const preview = {seed, buildId, stored: undefined, db: undefined};
globalThis.__stgPreview = preview;

const {initializeABAP} = await import("../output/init.mjs");
const {cl_express_icf_shim} = await import("../output/cl_express_icf_shim.clas.mjs");
const {services} = await import("./generated/services.mjs");

// which service answers a path: the longest prefix that matches, so a service
// mounted below another is found before its parent. Nothing here knows what
// any of them do.
const byLength = [...services].sort((a, b) => b.path.length - a.path.length);
function serviceFor(path) {
  const found = byLength.find((s) => path === s.path || path.startsWith(s.path + "/"));
  if (found === undefined) {
    throw new Error(`no service is mounted on ${path}`);
  }
  return found;
}
const {zcl_stg_segw_registry} = await import("../output/zcl_stg_segw_registry.clas.mjs");
const {zcl_stg_shlp_registry} = await import("../output/zcl_stg_shlp_registry.clas.mjs");

// CL_EXPRESS_ICF_SHIM keeps request and response on one static server object;
// overlapping fetch events would answer each other's requests. Serialize.
let queue = Promise.resolve();

function serialized(work) {
  const result = queue.then(work, work);
  queue = result.then(() => undefined, () => undefined);
  return result;
}

function toBytes(value) {
  if (value instanceof Uint8Array) {
    return value;
  }
  if (value instanceof ArrayBuffer) {
    return new Uint8Array(value);
  }
  return new TextEncoder().encode(String(value ?? ""));
}

async function registerServices() {
  // generated from the IWSV/IWMO objects by tools/segw-registry.mjs
  await zcl_stg_segw_registry.register();
  // the search help objects, generated by tools/segw-shlp.mjs
  await zcl_stg_shlp_registry.register();
}

async function invoke({method, path, search = "", headers = {}, body}) {
  const responseHeaders = new Headers();
  let status = 200;
  let data = new Uint8Array(0);
  const res = {
    append(name, value) {
      responseHeaders.append(name, value);
    },
    status(code) {
      status = Number(code);
      return res;
    },
    send(payload) {
      data = toBytes(payload);
    },
  };
  const service = serviceFor(path);
  await cl_express_icf_shim.run({
    req: {
      body: Buffer.from(body ?? new Uint8Array(0)),
      headers,
      method: String(method || "GET").toUpperCase(),
      path,
      url: `${path}${search}`,
    },
    res,
    class: service.handler,
    base: new abap.types.String().set(service.path),
  });
  return {status, headers: responseHeaders, body: data};
}

// A push channel, driven where the runtime already is.
//
// The page has a WebSocket-shaped object (web/preview-socket.mjs) and no
// runtime; this end has the runtime and no socket. One zcl_apc_host per
// conversation, because a stateful handler is one object per connection,
// and the messages it pushed come back through drain( ) after every
// callback — on_start is allowed to speak first and usually does.
const hosts = new Map();

export async function openChannel(id, channel, send) {
  const {zcl_apc_host} = await import("../output/zcl_apc_host.clas.mjs");
  const host = new zcl_apc_host();
  const drain = async () => {
    const pushed = await host.drain();
    for (const row of pushed.array()) {
      send({apc: "message", text: row.get()});
    }
  };
  await host.constructor_({
    iv_handler: new abap.types.String().set(channel.handler),
    it_fields: zcl_apc_host.METHODS.CONSTRUCTOR.parameters.IT_FIELDS.type(),
  });
  const accepted = await host.open();
  await drain();
  if (accepted.get() !== "X") {
    throw new Error("the handler refused the connection");
  }
  hosts.set(id, {host, drain});
}

export async function channelMessage(id, text, send) {
  const entry = hosts.get(id);
  if (entry === undefined) {
    throw new Error(`no channel ${id}`);
  }
  await entry.host.message({iv_text: new abap.types.String().set(text)});
  await entry.drain();
  void send;
}

export async function closeChannel(id) {
  const entry = hosts.get(id);
  hosts.delete(id);
  if (entry !== undefined) {
    await entry.host.close({
      iv_reason: new abap.types.String().set("closed by the page"),
      iv_code: new abap.types.Integer().set(1000),
    });
  }
}

export async function startBackend(stored) {
  preview.stored = stored;
  await initializeABAP();
  await registerServices();
}

export function handleRequest(request) {
  return serialized(() => invoke(request));
}

// Back to the seeded state: the transpiled runtime is kept, only the database
// is rebuilt through the same setup that opened it.
export function resetBackend() {
  return serialized(async () => {
    preview.stored = undefined;
    const setup = await import("../test/setup.mjs");
    await setup.setup(globalThis.abap, preview.schemas, preview.insert);
  });
}

export function exportDatabase() {
  return serialized(() => preview.db.export());
}

export {buildId};
